#pragma once

#include "mc/_HeaderOutputPredefine.h"

enum class StoreVisualStyleCategory : int {
    DescriptionSection = 0,
    SinglePageRow = 1,
    StoreRow = 2,
    ScreenshotsHeroBladeRow = 3,
    HeroRow = 4,
    HeroRowL2 = 5,
    GiftPromoBanner = 6,
    PromoRow = 7,
    PromoTimeline = 8,
    StoreOfferGrid = 9,
    NavButton = 10,
    NavButtonSection = 11,
    WorldList = 12,
    FooterSection = 13,
    Carousel = 14,
    CarouselRow = 15,
    Custom = 16,
    SearchBar = 17,
    CoinRowSection = 18,
    ImageMessageRow = 19,
    TextRow = 20,
    CoinBundleSection = 21,
    VerticalStoreOfferGrid = 22,
    VerticalLineDivider = 23,
    VerticalFillPadding = 24,
    SdlDropdownHeaderSection = 25,
    SdlDropdownDataSection = 26,
    HeightOptionsRow = 27,
    ArmSizeOptionsRow = 28,
    DarkRedirectButton = 29,
    PersonaSideSelectionRow = 30,
    LayoutSection = 31,
    SkinPackList = 32,
    SummarySection = 33,
    SkinPackSection = 34,
    ScreenshotSection = 35,
    RatingsSection = 36,
    BundlePreviewSection = 37,
    BundleSummarySection = 38,
    PanaromaSection = 39,
    RecentlyViewedSection = 40,
    RelatedItemsSection = 41,
    ChangelogSection = 42,
    CharacterSelectorRow = 43,
    ExpandedSkinPackGrid = 44,
    Count = 45,
    Invalid = 46,
};
