#pragma once

#include "mc/_HeaderOutputPredefine.h"

enum class BlockProperty : uint64 {
    // bitfield representation
    None = 0,
    Stair = 1ull << 0,
    HalfSlab = 1ull << 1,
    Hopper = 1ull << 2,
    TopSnow = 1ull << 3,
    FenceGate = 1ull << 4,
    Leaves = 1ull << 5,
    Connects2D = 1ull << 7,
    Carpet = 1ull << 8,
    Button = 1ull << 9,
    Door = 1ull << 10,
    Portal = 1ull << 11,
    CanFall = 1ull << 12,
    Snow = 1ull << 13,
    Trap = 1ull << 14,
    Sign = 1ull << 15,
    Walkable = 1ull << 16,
    PressurePlate = 1ull << 17,
    TopSolidBlocking = 1ull << 19,
    CubeShaped = 1ull << 21,
    PowerNo = 1ull << 22,
    PowerBlockDown = 1ull << 23,
    Piston = 1ull << 26,
    InfiniBurn = 1ull << 27,
    RequiresWorldBuilder = 1ull << 28,
    CausesDamage = 1ull << 29,
    BreaksWhenFallenOnByFallingBlock = 1ull << 30,
    Liquid = 1ull << 32,
    SnowRecoverable = 1ull << 34,
    Scaffolding = 1ull << 35,
    CanSupportCenterHangingBlock = 1ull << 36,
    BreaksWhenHitByArrowDeprecated = 1ull << 37,
    Unwalkable = 1ull << 38,
    Hollow = 1ull << 40,
    OperatorBlock = 1ull << 41,
    PreventsJumping = 1ull << 43,
    ContainsHoney = 1ull << 44,
    Slime = 1ull << 45,
    SculkReplaceableDeprecated = 1ull << 46,
    Climbable = 1ull << 47,
    CanHaltWhenClimbing = 1ull << 48,
    CanDamperVibrations = 1ull << 49,
    CanOccludeVibrations = 1ull << 50,
};
