#pragma once
#include <mc/Actor.h>
#include <mc/Block.h>
#include <mc/BlockSource.h>
#include <mc/Command/Command.h>
#include <mc/Core.h>
#include <mc/Dimension.h>
#include <mc/Item.h>
#include <mc/Level.h>
#include <mc/Player.h>
#include <mc/VanillaBlocks.h>