#pragma once

#include "mc/_HeaderOutputPredefine.h"

namespace GameEventConfig {

enum class GameEventType : int {
    Invalid = 0,
    BlockActivate = 1,
    BlockAttach = 2,
    BlockChange = 3,
    BlockClose = 4,
    BlockDeactivate = 5,
    BlockDestroy = 6,
    BlockDetach = 7,
    BlockOpen = 8,
    BlockPlace = 9,
    ContainerClose = 10,
    ContainerOpen = 11,
    DispenseFail = 12,
    Drink = 13,
    Eat = 14,
    ElytraGlide = 15,
    EntityDamage = 16,
    EntityDie = 17,
    EntityDismount = 18,
    EntityInteract = 19,
    EntityMount = 20,
    EntityMove = 21,
    EntityPlace = 22,
    EntityRoar = 23,
    EntityAct = 24,
    Equip = 25,
    Explode = 26,
    Flap = 27,
    FluidPickup = 28,
    FluidPlace = 29,
    HitGround = 30,
    ItemInteractFinish = 31,
    ItemInteractStart = 32,
    LightningStrike = 33,
    MultiItemSwap = 34,
    NoteBlockPlay = 35,
    PistonContract = 36,
    PistonExtend = 37,
    PrimeFuse = 38,
    ProjectileLand = 39,
    ProjectileShoot = 40,
    Resonate1 = 41,
    Resonate2 = 42,
    Resonate3 = 43,
    Resonate4 = 44,
    Resonate5 = 45,
    Resonate6 = 46,
    Resonate7 = 47,
    Resonate8 = 48,
    Resonate9 = 49,
    Resonate10 = 50,
    Resonate11 = 51,
    Resonate12 = 52,
    Resonate13 = 53,
    Resonate14 = 54,
    Resonate15 = 55,
    SculkTouch = 56,
    SculkSensorTendrilsClicking = 57,
    Shear = 58,
    Shriek = 59,
    SingleItemSwap = 60,
    Splash = 61,
    Swim = 62,
    Teleport = 63,
    Unequip = 64,
    Count = 65,
};

}
