/**
 * @file  AppLifecycleContext.hpp
 * @note  This Header is auto generated by LiteLoaderBDS Toolchain.
 *
 */
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

/**
 * @brief MC class AppLifecycleContext.
 *
 */
class AppLifecycleContext {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_APPLIFECYCLECONTEXT
public:
    class AppLifecycleContext& operator=(class AppLifecycleContext const &) = delete;
    AppLifecycleContext(class AppLifecycleContext const &) = delete;
#endif

public:
    /**
     * @symbol ??0AppLifecycleContext@@QEAA@XZ
     * @hash   718366658
     */
    MCAPI AppLifecycleContext();

};