/**
 * @file  BedBlockActor.hpp
 * @note  This Header is auto generated by LiteLoaderBDS Toolchain.
 *
 */
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "BlockActor.hpp"

#define BEFORE_EXTRA
// Include Headers or Declare Types Here

#undef BEFORE_EXTRA

/**
 * @brief MC class BedBlockActor.
 *
 */
class BedBlockActor : public BlockActor {

#define AFTER_EXTRA
// Add Member There

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_BEDBLOCKACTOR
public:
    class BedBlockActor& operator=(class BedBlockActor const &) = delete;
    BedBlockActor(class BedBlockActor const &) = delete;
    BedBlockActor() = delete;
#endif

public:
    /**
     * @vftbl  0
     * @hash   -1421302505
     */
    virtual ~BedBlockActor();
    /**
     * @vftbl  1
     * @symbol ?load@BedBlockActor@@UEAAXAEAVLevel@@AEBVCompoundTag@@AEAVDataLoadHelper@@@Z
     * @hash   1580774448
     */
    virtual void load(class Level &, class CompoundTag const &, class DataLoadHelper &);
    /**
     * @vftbl  2
     * @symbol ?save@BedBlockActor@@UEBA_NAEAVCompoundTag@@@Z
     * @hash   -1177085457
     */
    virtual bool save(class CompoundTag &) const;
    /**
     * @vftbl  3
     * @symbol ?saveItemInstanceData@BedBlockActor@@UEAA_NAEAVCompoundTag@@@Z
     * @hash   1773164590
     */
    virtual bool saveItemInstanceData(class CompoundTag &);
    /**
     * @vftbl  7
     * @symbol ?tick@BedBlockActor@@UEAAXAEAVBlockSource@@@Z
     * @hash   -1445346135
     */
    virtual void tick(class BlockSource &);
    /**
     * @vftbl  8
     * @symbol ?onChanged@BedBlockActor@@UEAAXAEAVBlockSource@@@Z
     * @hash   -246357375
     */
    virtual void onChanged(class BlockSource &);
    /**
     * @vftbl  11
     * @symbol ?onPlace@BedBlockActor@@UEAAXAEAVBlockSource@@@Z
     * @hash   -1682688466
     */
    virtual void onPlace(class BlockSource &);
    /**
     * @vftbl  12
     * @hash   -291256027
     */
    virtual void __unk_vfn_12();
    /**
     * @vftbl  18
     * @hash   -285714901
     */
    virtual void __unk_vfn_18();
    /**
     * @vftbl  21
     * @symbol ?getCrackEntity@BedBlockActor@@UEAAPEAVBlockActor@@AEAVBlockSource@@AEBVBlockPos@@@Z
     * @hash   656182793
     */
    virtual class BlockActor * getCrackEntity(class BlockSource &, class BlockPos const &);
    /**
     * @vftbl  26
     * @symbol ?getName@BedBlockActor@@UEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ
     * @hash   2015029506
     */
    virtual std::string getName() const;
    /**
     * @vftbl  31
     * @hash   -234921246
     */
    virtual void __unk_vfn_31();
    /**
     * @vftbl  32
     * @hash   -233997725
     */
    virtual void __unk_vfn_32();
    /**
     * @vftbl  33
     * @hash   -233074204
     */
    virtual void __unk_vfn_33();
    /**
     * @vftbl  34
     * @hash   -232150683
     */
    virtual void __unk_vfn_34();
    /**
     * @vftbl  35
     * @hash   -190772906
     */
    virtual void __unk_vfn_35();
    /**
     * @vftbl  36
     * @hash   -189849385
     */
    virtual void __unk_vfn_36();
    /**
     * @vftbl  37
     * @symbol ?_getUpdatePacket@BedBlockActor@@MEAA?AV?$unique_ptr@VBlockActorDataPacket@@U?$default_delete@VBlockActorDataPacket@@@std@@@std@@AEAVBlockSource@@@Z
     * @hash   552744002
     */
    virtual std::unique_ptr<class BlockActorDataPacket> _getUpdatePacket(class BlockSource &);
    /**
     * @vftbl  38
     * @symbol ?_onUpdatePacket@BedBlockActor@@MEAAXAEBVCompoundTag@@AEAVBlockSource@@@Z
     * @hash   -1168233456
     */
    virtual void _onUpdatePacket(class CompoundTag const &, class BlockSource &);
    /**
     * @symbol ??0BedBlockActor@@QEAA@AEBVBlockPos@@@Z
     * @hash   917777740
     */
    MCAPI BedBlockActor(class BlockPos const &);
    /**
     * @symbol ?claimPetSleepOnBed@BedBlockActor@@QEAA_NUActorUniqueID@@@Z
     * @hash   1922882701
     */
    MCAPI bool claimPetSleepOnBed(struct ActorUniqueID);
    /**
     * @symbol ?startSleepingOn@BedBlockActor@@QEAAXXZ
     * @hash   -499867699
     */
    MCAPI void startSleepingOn();
    /**
     * @symbol ?stopSleepingOn@BedBlockActor@@QEAAXAEAVBlockSource@@_N@Z
     * @hash   1748448277
     */
    MCAPI void stopSleepingOn(class BlockSource &, bool);

};