/**
 * @file  BehaviorComponent.hpp
 * @note  This Header is auto generated by LiteLoaderBDS Toolchain.
 *
 */
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA
// Include Headers or Declare Types Here

#undef BEFORE_EXTRA

/**
 * @brief MC class BehaviorComponent.
 *
 */
class BehaviorComponent {

#define AFTER_EXTRA
// Add Member There

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_BEHAVIORCOMPONENT
public:
    class BehaviorComponent& operator=(class BehaviorComponent const &) = delete;
    BehaviorComponent(class BehaviorComponent const &) = delete;
#endif

public:
    /**
     * @symbol ??0BehaviorComponent@@QEAA@XZ
     * @hash   -580644457
     */
    MCAPI BehaviorComponent();
    /**
     * @symbol ??0BehaviorComponent@@QEAA@$$QEAV0@@Z
     * @hash   1142750287
     */
    MCAPI BehaviorComponent(class BehaviorComponent &&);
    /**
     * @symbol ??4BehaviorComponent@@QEAAAEAV0@$$QEAV0@@Z
     * @hash   -1555665750
     */
    MCAPI class BehaviorComponent & operator=(class BehaviorComponent &&);
    /**
     * @symbol ??1BehaviorComponent@@QEAA@XZ
     * @hash   -696036329
     */
    MCAPI ~BehaviorComponent();

};