/**
 * @file  BlockLegacy.hpp
 * @note  This Header is auto generated by LiteLoaderBDS Toolchain.
 *
 */
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA
// Add include headers & pre-declares
class Block;
class BlockSource;
class ItemStack;

#undef BEFORE_EXTRA

/**
 * @brief MC class BlockLegacy.
 *
 */
class BlockLegacy {

#define AFTER_EXTRA
// Add new members to class
public:
    struct NameInfo;

    LIAPI Block* toBlock(unsigned short tileData);
    LIAPI string getTypeName();
    LIAPI bool applyBoneMeal(class BlockSource* a1, class BlockPos const& a2);
    LIAPI ItemStack* getBlockDrops();
#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_BLOCKLEGACY
public:
    class BlockLegacy& operator=(class BlockLegacy const &) = delete;
    BlockLegacy(class BlockLegacy const &) = delete;
    BlockLegacy() = delete;
#endif

public:
    /**
     * @vftbl  0
     * @hash   1067080964
     */
    virtual ~BlockLegacy();
    /**
     * @vftbl  1
     * @symbol ?getStateFromLegacyData@BlockLegacy@@UEBAAEBVBlock@@G@Z
     * @hash   -652772495
     */
    virtual class Block const & getStateFromLegacyData(unsigned short) const;
    /**
     * @vftbl  2
     * @symbol ?newBlockEntity@BlockLegacy@@UEBA?AV?$shared_ptr@VBlockActor@@@std@@AEBVBlockPos@@AEBVBlock@@@Z
     * @hash   1557132498
     */
    virtual class std::shared_ptr<class BlockActor> newBlockEntity(class BlockPos const &, class Block const &) const;
    /**
     * @vftbl  3
     * @symbol ?getNextBlockPermutation@BlockLegacy@@UEBAPEBVBlock@@AEBV2@@Z
     * @hash   2096545922
     */
    virtual class Block const * getNextBlockPermutation(class Block const &) const;
    /**
     * @vftbl  4
     * @symbol ?hasTag@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z
     * @hash   -1048399784
     */
    virtual bool hasTag(class BlockSource &, class BlockPos const &, class Block const &, std::string const &) const;
    /**
     * @vftbl  5
     * @symbol ?getCollisionShape@BlockLegacy@@UEBA_NAEAVAABB@@AEBVBlock@@AEBVIConstBlockSource@@AEBVBlockPos@@V?$optional_ref@$$CBVGetCollisionShapeInterface@@@@@Z
     * @hash   -1025839124
     */
    virtual bool getCollisionShape(class AABB &, class Block const &, class IConstBlockSource const &, class BlockPos const &, class optional_ref<class GetCollisionShapeInterface const>) const;
    /**
     * @vftbl  6
     * @symbol ?isObstructingChests@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@@Z
     * @hash   988196960
     */
    virtual bool isObstructingChests(class BlockSource &, class BlockPos const &, class Block const &) const;
    /**
     * @vftbl  7
     * @symbol ?randomlyModifyPosition@BlockLegacy@@UEBA?AVVec3@@AEBVBlockPos@@AEAH@Z
     * @hash   -1729677168
     */
    virtual class Vec3 randomlyModifyPosition(class BlockPos const &, int &) const;
    /**
     * @vftbl  8
     * @symbol ?randomlyModifyPosition@BlockLegacy@@UEBA?AVVec3@@AEBVBlockPos@@@Z
     * @hash   617759019
     */
    virtual class Vec3 randomlyModifyPosition(class BlockPos const &) const;
    /**
     * @vftbl  9
     * @symbol ?addAABBs@BlockLegacy@@UEBAXAEBVBlock@@AEBVBlockSource@@AEBVBlockPos@@PEBVAABB@@AEAV?$vector@VAABB@@V?$allocator@VAABB@@@std@@@std@@@Z
     * @hash   1374717302
     */
    virtual void addAABBs(class Block const &, class BlockSource const &, class BlockPos const &, class AABB const *, std::vector<class AABB> &) const;
    /**
     * @vftbl  10
     * @symbol ?getAABB@BlockLegacy@@UEBAAEBVAABB@@AEBVIConstBlockSource@@AEBVBlockPos@@AEBVBlock@@AEAV2@_N@Z
     * @hash   -1893309898
     */
    virtual class AABB const & getAABB(class IConstBlockSource const &, class BlockPos const &, class Block const &, class AABB &, bool) const;
    /**
     * @vftbl  11
     * @symbol ?addCollisionShapes@BlockLegacy@@UEBA_NAEBVBlock@@AEBVBlockSource@@AEBVBlockPos@@PEBVAABB@@AEAV?$vector@VAABB@@V?$allocator@VAABB@@@std@@@std@@V?$optional_ref@$$CBVGetCollisionShapeInterface@@@@@Z
     * @hash   680254791
     */
    virtual bool addCollisionShapes(class Block const &, class BlockSource const &, class BlockPos const &, class AABB const *, std::vector<class AABB> &, class optional_ref<class GetCollisionShapeInterface const>) const;
    /**
     * @vftbl  12
     * @symbol ?updateTallestCollisionShape@BlockLegacy@@UEBA_NAEBVBlock@@AEBVBlockSource@@AEBVBlockPos@@AEBVAABB@@V?$optional_ref@$$CBVGetCollisionShapeInterface@@@@AEAV5@AEBVVec3@@AEAM@Z
     * @hash   -692448381
     */
    virtual bool updateTallestCollisionShape(class Block const &, class BlockSource const &, class BlockPos const &, class AABB const &, class optional_ref<class GetCollisionShapeInterface const>, class AABB &, class Vec3 const &, float &) const;
    /**
     * @vftbl  13
     * @symbol ?getOutline@BlockLegacy@@UEBAAEBVAABB@@AEAVBlockSource@@AEBVBlockPos@@AEAV2@@Z
     * @hash   -617263095
     */
    virtual class AABB const & getOutline(class BlockSource &, class BlockPos const &, class AABB &) const;
    /**
     * @vftbl  14
     * @symbol ?getLiquidClipVolume@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@AEAVAABB@@@Z
     * @hash   1418497502
     */
    virtual bool getLiquidClipVolume(class BlockSource &, class BlockPos const &, class AABB &) const;
    /**
     * @vftbl  15
     * @symbol ?onProjectileHit@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@AEBVActor@@@Z
     * @hash   -1495779327
     */
    virtual void onProjectileHit(class BlockSource &, class BlockPos const &, class Actor const &) const;
    /**
     * @vftbl  16
     * @symbol ?onLightningHit@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@@Z
     * @hash   -570981586
     */
    virtual void onLightningHit(class BlockSource &, class BlockPos const &) const;
    /**
     * @vftbl  17
     * @symbol ?liquidCanFlowIntoFromDirection@BlockLegacy@@UEBA_NEAEBV?$function@$$A6AAEBVBlock@@AEBVBlockPos@@@Z@std@@AEBVBlockPos@@@Z
     * @hash   -22969463
     */
    virtual bool liquidCanFlowIntoFromDirection(unsigned char, class std::function<class Block const & (class BlockPos const &)> const &, class BlockPos const &) const;
    /**
     * @vftbl  18
     * @symbol ?isSolid@BlockLegacy@@UEBA_NXZ
     * @hash   -1869636669
     */
    virtual bool isSolid() const;
    /**
     * @vftbl  19
     * @hash   -227039124
     */
    virtual void __unk_vfn_19();
    /**
     * @vftbl  20
     * @symbol ?isStrippable@BlockLegacy@@UEBA_NAEBVBlock@@@Z
     * @hash   1424579932
     */
    virtual bool isStrippable(class Block const &) const;
    /**
     * @vftbl  21
     * @symbol ?getStrippedBlock@BlockLegacy@@UEBAAEBVBlock@@AEBV2@@Z
     * @hash   -390713696
     */
    virtual class Block const & getStrippedBlock(class Block const &) const;
    /**
     * @vftbl  22
     * @symbol ?canProvideSupport@BlockLegacy@@UEBA_NAEBVBlock@@EW4BlockSupportType@@@Z
     * @hash   -2022024747
     */
    virtual bool canProvideSupport(class Block const &, unsigned char, enum class BlockSupportType) const;
    /**
     * @vftbl  23
     * @symbol ?canProvideFullSupport@BlockLegacy@@UEBA_NAEBVBlock@@E@Z
     * @hash   -372448334
     */
    virtual bool canProvideFullSupport(class Block const &, unsigned char) const;
    /**
     * @vftbl  24
     * @symbol ?canProvideMultifaceSupport@BlockLegacy@@UEBA_NAEBVBlock@@E@Z
     * @hash   -384133907
     */
    virtual bool canProvideMultifaceSupport(class Block const &, unsigned char) const;
    /**
     * @vftbl  25
     * @symbol ?canConnect@BlockLegacy@@UEBA_NAEBVBlock@@E0@Z
     * @hash   2005056941
     */
    virtual bool canConnect(class Block const &, unsigned char, class Block const &) const;
    /**
     * @vftbl  26
     * @symbol ?getConnectedDirections@BlockLegacy@@UEBAXAEBVBlock@@AEBVBlockPos@@AEBVIConstBlockSource@@AEA_N333@Z
     * @hash   -1125601068
     */
    virtual void getConnectedDirections(class Block const &, class BlockPos const &, class IConstBlockSource const &, bool &, bool &, bool &, bool &) const;
    /**
     * @vftbl  27
     * @symbol ?isAir@BlockLegacy@@UEBA_NXZ
     * @hash   1157113698
     */
    virtual bool isAir() const;
    /**
     * @vftbl  28
     * @symbol ?tryGetCopperBehavior@BlockLegacy@@UEBAPEBVCopperBehavior@@XZ
     * @hash   -2034895218
     */
    virtual class CopperBehavior const * tryGetCopperBehavior() const;
    /**
     * @vftbl  29
     * @hash   -198409973
     */
    virtual void __unk_vfn_29();
    /**
     * @vftbl  30
     * @hash   -178092511
     */
    virtual void __unk_vfn_30();
    /**
     * @vftbl  31
     * @symbol ?isClimbable@BlockLegacy@@UEBA_NAEBUIActorMovementProxy@@@Z
     * @hash   -812785376
     */
    virtual bool isClimbable(struct IActorMovementProxy const &) const;
    /**
     * @vftbl  32
     * @hash   -176245469
     */
    virtual void __unk_vfn_32();
    /**
     * @vftbl  33
     * @hash   -175321948
     */
    virtual void __unk_vfn_33();
    /**
     * @vftbl  34
     * @hash   -174398427
     */
    virtual void __unk_vfn_34();
    /**
     * @vftbl  35
     * @symbol ?isWaterBlocking@BlockLegacy@@UEBA_NXZ
     * @hash   21826948
     */
    virtual bool isWaterBlocking() const;
    /**
     * @vftbl  36
     * @hash   -172551385
     */
    virtual void __unk_vfn_36();
    /**
     * @vftbl  37
     * @hash   -171627864
     */
    virtual void __unk_vfn_37();
    /**
     * @vftbl  38
     * @hash   -170704343
     */
    virtual void __unk_vfn_38();
    /**
     * @vftbl  39
     * @hash   -169780822
     */
    virtual void __unk_vfn_39();
    /**
     * @vftbl  40
     * @hash   -149463360
     */
    virtual void __unk_vfn_40();
    /**
     * @vftbl  41
     * @hash   -148539839
     */
    virtual void __unk_vfn_41();
    /**
     * @vftbl  42
     * @hash   -147616318
     */
    virtual void __unk_vfn_42();
    /**
     * @vftbl  43
     * @symbol ?isDoubleSlabBlock@BlockLegacy@@UEBA_NXZ
     * @hash   -1570888326
     */
    virtual bool isDoubleSlabBlock() const;
    /**
     * @vftbl  44
     * @hash   -145769276
     */
    virtual void __unk_vfn_44();
    /**
     * @vftbl  45
     * @hash   -144845755
     */
    virtual void __unk_vfn_45();
    /**
     * @vftbl  46
     * @hash   -143922234
     */
    virtual void __unk_vfn_46();
    /**
     * @vftbl  47
     * @hash   -142998713
     */
    virtual void __unk_vfn_47();
    /**
     * @vftbl  48
     * @hash   -142075192
     */
    virtual void __unk_vfn_48();
    /**
     * @vftbl  49
     * @hash   -141151671
     */
    virtual void __unk_vfn_49();
    /**
     * @vftbl  50
     * @symbol ?canHurtAndBreakItem@BlockLegacy@@UEBA_NXZ
     * @hash   -1301927844
     */
    virtual bool canHurtAndBreakItem() const;
    /**
     * @vftbl  51
     * @symbol ?isSignalSource@BlockLegacy@@UEBA_NXZ
     * @hash   1899241327
     */
    virtual bool isSignalSource() const;
    /**
     * @vftbl  52
     * @symbol ?canBeOriginalSurface@BlockLegacy@@UEBA_NXZ
     * @hash   196240507
     */
    virtual bool canBeOriginalSurface() const;
    /**
     * @vftbl  53
     * @symbol ?canBeAscendedByJumping@BlockLegacy@@UEBA_NAEBVActor@@AEBVBlockPos@@@Z
     * @hash   655794201
     */
    virtual bool canBeAscendedByJumping(class Actor const &, class BlockPos const &) const;
    /**
     * @vftbl  54
     * @hash   -117140125
     */
    virtual void __unk_vfn_54();
    /**
     * @vftbl  55
     * @symbol ?isValidAuxValue@BlockLegacy@@UEBA_NH@Z
     * @hash   -2116431876
     */
    virtual bool isValidAuxValue(int) const;
    /**
     * @vftbl  56
     * @symbol ?canFillAtPos@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@@Z
     * @hash   -1339077388
     */
    virtual bool canFillAtPos(class BlockSource &, class BlockPos const &, class Block const &) const;
    /**
     * @vftbl  57
     * @symbol ?sanitizeFillBlock@BlockLegacy@@UEBAAEBVBlock@@AEAVBlockSource@@AEBVBlockPos@@AEBV2@@Z
     * @hash   1712892825
     */
    virtual class Block const & sanitizeFillBlock(class BlockSource &, class BlockPos const &, class Block const &) const;
    /**
     * @vftbl  58
     * @symbol ?onFillBlock@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@@Z
     * @hash   915704585
     */
    virtual void onFillBlock(class BlockSource &, class BlockPos const &, class Block const &) const;
    /**
     * @vftbl  59
     * @symbol ?getDirectSignal@BlockLegacy@@UEBAHAEAVBlockSource@@AEBVBlockPos@@H@Z
     * @hash   931365803
     */
    virtual int getDirectSignal(class BlockSource &, class BlockPos const &, int) const;
    /**
     * @vftbl  60
     * @hash   -92205058
     */
    virtual void __unk_vfn_60();
    /**
     * @vftbl  61
     * @hash   -91281537
     */
    virtual void __unk_vfn_61();
    /**
     * @vftbl  62
     * @symbol ?canContainLiquid@BlockLegacy@@UEBA_NXZ
     * @hash   1025336530
     */
    virtual bool canContainLiquid() const;
    /**
     * @vftbl  63
     * @symbol ?getRequiredMedium@BlockLegacy@@UEBA?AV?$optional@VHashedString@@@std@@XZ
     * @hash   -493772844
     */
    virtual class std::optional<class HashedString> getRequiredMedium() const;
    /**
     * @vftbl  64
     * @symbol ?shouldConnectToRedstone@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@H@Z
     * @hash   1687758111
     */
    virtual bool shouldConnectToRedstone(class BlockSource &, class BlockPos const &, int) const;
    /**
     * @vftbl  65
     * @symbol ?handlePrecipitation@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@MM@Z
     * @hash   1963531681
     */
    virtual void handlePrecipitation(class BlockSource &, class BlockPos const &, float, float) const;
    /**
     * @vftbl  66
     * @symbol ?canBeUsedInCommands@BlockLegacy@@UEBA_NAEBVBaseGameVersion@@@Z
     * @hash   -290135789
     */
    virtual bool canBeUsedInCommands(class BaseGameVersion const &) const;
    /**
     * @vftbl  67
     * @symbol ?getThickness@BlockLegacy@@UEBAMXZ
     * @hash   -819820730
     */
    virtual float getThickness() const;
    /**
     * @vftbl  68
     * @symbol ?getFlexibility@BlockLegacy@@UEBAMAEAVBlockSource@@AEBVBlockPos@@@Z
     * @hash   -1236969535
     */
    virtual float getFlexibility(class BlockSource &, class BlockPos const &) const;
    /**
     * @vftbl  69
     * @symbol ?checkIsPathable@BlockLegacy@@UEBA_NAEAVActor@@AEBVBlockPos@@1@Z
     * @hash   1020568778
     */
    virtual bool checkIsPathable(class Actor &, class BlockPos const &, class BlockPos const &) const;
    /**
     * @vftbl  70
     * @symbol ?shouldDispense@BlockLegacy@@UEBA_NAEAVBlockSource@@AEAVContainer@@@Z
     * @hash   -735438263
     */
    virtual bool shouldDispense(class BlockSource &, class Container &) const;
    /**
     * @vftbl  71
     * @symbol ?dispense@BlockLegacy@@UEBA_NAEAVBlockSource@@AEAVContainer@@HAEBVVec3@@E@Z
     * @hash   112034386
     */
    virtual bool dispense(class BlockSource &, class Container &, int, class Vec3 const &, unsigned char) const;
    /**
     * @vftbl  72
     * @symbol ?transformOnFall@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@PEAVActor@@M@Z
     * @hash   -1519104933
     */
    virtual void transformOnFall(class BlockSource &, class BlockPos const &, class Actor *, float) const;
    /**
     * @vftbl  73
     * @symbol ?onRedstoneUpdate@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@H_N@Z
     * @hash   1520425663
     */
    virtual void onRedstoneUpdate(class BlockSource &, class BlockPos const &, int, bool) const;
    /**
     * @vftbl  74
     * @symbol ?onMove@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@1@Z
     * @hash   -1433885542
     */
    virtual void onMove(class BlockSource &, class BlockPos const &, class BlockPos const &) const;
    /**
     * @vftbl  75
     * @hash   -58958302
     */
    virtual void __unk_vfn_75();
    /**
     * @vftbl  76
     * @symbol ?movedByPiston@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@@Z
     * @hash   1390694185
     */
    virtual void movedByPiston(class BlockSource &, class BlockPos const &) const;
    /**
     * @vftbl  77
     * @symbol ?onStructureBlockPlace@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@@Z
     * @hash   -1297316428
     */
    virtual void onStructureBlockPlace(class BlockSource &, class BlockPos const &) const;
    /**
     * @vftbl  78
     * @symbol ?onStructureNeighborBlockPlace@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@@Z
     * @hash   -1965457658
     */
    virtual void onStructureNeighborBlockPlace(class BlockSource &, class BlockPos const &) const;
    /**
     * @vftbl  79
     * @symbol ?setupRedstoneComponent@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@@Z
     * @hash   847733938
     */
    virtual void setupRedstoneComponent(class BlockSource &, class BlockPos const &) const;
    /**
     * @vftbl  80
     * @symbol ?getRedstoneProperty@BlockLegacy@@UEBA?AW4BlockProperty@@AEAVBlockSource@@AEBVBlockPos@@@Z
     * @hash   -1076256669
     */
    virtual enum class BlockProperty getRedstoneProperty(class BlockSource &, class BlockPos const &) const;
    /**
     * @vftbl  81
     * @symbol ?updateEntityAfterFallOn@BlockLegacy@@UEBAXAEBVBlockPos@@AEAUUpdateEntityAfterFallOnInterface@@@Z
     * @hash   -434550446
     */
    virtual void updateEntityAfterFallOn(class BlockPos const &, struct UpdateEntityAfterFallOnInterface &) const;
    /**
     * @vftbl  82
     * @hash   -33099714
     */
    virtual void __unk_vfn_82();
    /**
     * @vftbl  83
     * @symbol ?isFilteredOut@BlockLegacy@@UEBA_NW4BlockRenderLayer@@@Z
     * @hash   -843515147
     */
    virtual bool isFilteredOut(enum class BlockRenderLayer) const;
    /**
     * @vftbl  84
     * @symbol ?isPreservingMediumWhenPlaced@BlockLegacy@@UEBA_NPEBV1@@Z
     * @hash   -392278188
     */
    virtual bool isPreservingMediumWhenPlaced(class BlockLegacy const *) const;
    /**
     * @vftbl  85
     * @symbol ?ignoreEntitiesOnPistonMove@BlockLegacy@@UEBA_NAEBVBlock@@@Z
     * @hash   -1186858916
     */
    virtual bool ignoreEntitiesOnPistonMove(class Block const &) const;
    /**
     * @vftbl  86
     * @symbol ?onFertilized@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@PEAVActor@@W4FertilizerType@@@Z
     * @hash   1738625920
     */
    virtual bool onFertilized(class BlockSource &, class BlockPos const &, class Actor *, enum class FertilizerType) const;
    /**
     * @vftbl  87
     * @symbol ?mayConsumeFertilizer@BlockLegacy@@UEBA_NAEAVBlockSource@@@Z
     * @hash   1533091927
     */
    virtual bool mayConsumeFertilizer(class BlockSource &) const;
    /**
     * @vftbl  88
     * @symbol ?canBeFertilized@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@@Z
     * @hash   575227819
     */
    virtual bool canBeFertilized(class BlockSource &, class BlockPos const &, class Block const &) const;
    /**
     * @vftbl  89
     * @symbol ?mayPick@BlockLegacy@@UEBA_NXZ
     * @hash   864734200
     */
    virtual bool mayPick() const;
    /**
     * @vftbl  90
     * @symbol ?mayPick@BlockLegacy@@UEBA_NAEBVBlockSource@@AEBVBlock@@_N@Z
     * @hash   -2051124441
     */
    virtual bool mayPick(class BlockSource const &, class Block const &, bool) const;
    /**
     * @vftbl  91
     * @symbol ?mayPlace@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@E@Z
     * @hash   2090956785
     */
    virtual bool mayPlace(class BlockSource &, class BlockPos const &, unsigned char) const;
    /**
     * @vftbl  92
     * @symbol ?mayPlace@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@@Z
     * @hash   -985183782
     */
    virtual bool mayPlace(class BlockSource &, class BlockPos const &) const;
    /**
     * @vftbl  93
     * @symbol ?mayPlaceOn@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@@Z
     * @hash   1831318777
     */
    virtual bool mayPlaceOn(class BlockSource &, class BlockPos const &) const;
    /**
     * @vftbl  94
     * @symbol ?tryToPlace@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@PEBUActorBlockSyncMessage@@@Z
     * @hash   1105243553
     */
    virtual bool tryToPlace(class BlockSource &, class BlockPos const &, class Block const &, struct ActorBlockSyncMessage const *) const;
    /**
     * @vftbl  95
     * @symbol ?tryToTill@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@AEAVActor@@AEAVItemStack@@@Z
     * @hash   -1981500365
     */
    virtual bool tryToTill(class BlockSource &, class BlockPos const &, class Actor &, class ItemStack &) const;
    /**
     * @vftbl  96
     * @symbol ?breaksFallingBlocks@BlockLegacy@@UEBA_NAEBVBlock@@VBaseGameVersion@@@Z
     * @hash   -1464163851
     */
    virtual bool breaksFallingBlocks(class Block const &, class BaseGameVersion) const;
    /**
     * @vftbl  97
     * @symbol ?destroy@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@PEAVActor@@@Z
     * @hash   -1410808521
     */
    virtual void destroy(class BlockSource &, class BlockPos const &, class Block const &, class Actor *) const;
    /**
     * @vftbl  98
     * @symbol ?playerWillDestroy@BlockLegacy@@UEBA_NAEAVPlayer@@AEBVBlockPos@@AEBVBlock@@@Z
     * @hash   1066865002
     */
    virtual bool playerWillDestroy(class Player &, class BlockPos const &, class Block const &) const;
    /**
     * @vftbl  99
     * @symbol ?getIgnoresDestroyPermissions@BlockLegacy@@UEBA_NAEAVActor@@AEBVBlockPos@@@Z
     * @hash   -2084289430
     */
    virtual bool getIgnoresDestroyPermissions(class Actor &, class BlockPos const &) const;
    /**
     * @vftbl  100
     * @symbol ?neighborChanged@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@1@Z
     * @hash   957106376
     */
    virtual void neighborChanged(class BlockSource &, class BlockPos const &, class BlockPos const &) const;
    /**
     * @vftbl  101
     * @symbol ?getSecondPart@BlockLegacy@@UEBA_NAEBVBlockSource@@AEBVBlockPos@@AEAV3@@Z
     * @hash   359578723
     */
    virtual bool getSecondPart(class BlockSource const &, class BlockPos const &, class BlockPos &) const;
    /**
     * @vftbl  102
     * @symbol ?asItemInstance@BlockLegacy@@UEBA?AVItemInstance@@AEBVBlock@@PEBVBlockActor@@@Z
     * @hash   -1445819388
     */
    virtual class ItemInstance asItemInstance(class Block const &, class BlockActor const *) const;
    /**
     * @vftbl  103
     * @symbol ?spawnResources@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@AEAVRandomize@@AEBUResourceDropsContext@@PEAV?$vector@PEBVItem@@V?$allocator@PEBVItem@@@std@@@std@@@Z
     * @hash   -382978648
     */
    virtual void spawnResources(class BlockSource &, class BlockPos const &, class Block const &, class Randomize &, struct ResourceDropsContext const &, std::vector<class Item const *> *) const;
    /**
     * @vftbl  104
     * @symbol ?trySpawnResourcesOnExplosion@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@AEAVRandomize@@PEAV?$vector@PEBVItem@@V?$allocator@PEBVItem@@@std@@@std@@M@Z
     * @hash   1185551978
     */
    virtual void trySpawnResourcesOnExplosion(class BlockSource &, class BlockPos const &, class Block const &, class Randomize &, std::vector<class Item const *> *, float) const;
    /**
     * @vftbl  105
     * @hash   1432640646
     */
    virtual void __unk_vfn_105();
    /**
     * @vftbl  106
     * @symbol ?getPlacementBlock@BlockLegacy@@UEBAAEBVBlock@@AEAVActor@@AEBVBlockPos@@EAEBVVec3@@H@Z
     * @hash   1439859621
     */
    virtual class Block const & getPlacementBlock(class Actor &, class BlockPos const &, unsigned char, class Vec3 const &, int) const;
    /**
     * @vftbl  107
     * @symbol ?calcVariant@BlockLegacy@@UEBAHAEAVBlockSource@@AEBVBlockPos@@AEBVColor@mce@@@Z
     * @hash   -1552788632
     */
    virtual int calcVariant(class BlockSource &, class BlockPos const &, class mce::Color const &) const;
    /**
     * @vftbl  108
     * @symbol ?isAttachedTo@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@AEAV3@@Z
     * @hash   -1709393958
     */
    virtual bool isAttachedTo(class BlockSource &, class BlockPos const &, class BlockPos &) const;
    /**
     * @vftbl  109
     * @symbol ?attack@BlockLegacy@@UEBA_NPEAVPlayer@@AEBVBlockPos@@@Z
     * @hash   -1020814795
     */
    virtual bool attack(class Player *, class BlockPos const &) const;
    /**
     * @vftbl  110
     * @symbol ?handleEntityInside@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@PEAVActor@@AEAVVec3@@@Z
     * @hash   203923439
     */
    virtual void handleEntityInside(class BlockSource &, class BlockPos const &, class Actor *, class Vec3 &) const;
    /**
     * @vftbl  111
     * @symbol ?shouldTriggerOnStandOn@BlockLegacy@@UEBA_NAEAVActor@@AEBVBlockPos@@@Z
     * @hash   314797446
     */
    virtual bool shouldTriggerOnStandOn(class Actor &, class BlockPos const &) const;
    /**
     * @vftbl  112
     * @symbol ?shouldTriggerEntityInside@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@AEAVActor@@@Z
     * @hash   453604521
     */
    virtual bool shouldTriggerEntityInside(class BlockSource &, class BlockPos const &, class Actor &) const;
    /**
     * @vftbl  113
     * @symbol ?entityInside@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@AEAVActor@@@Z
     * @hash   -1942152816
     */
    virtual void entityInside(class BlockSource &, class BlockPos const &, class Actor &) const;
    /**
     * @vftbl  114
     * @symbol ?canBeBuiltOver@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@AEBVBlockItem@@@Z
     * @hash   -455363984
     */
    virtual bool canBeBuiltOver(class BlockSource &, class BlockPos const &, class BlockItem const &) const;
    /**
     * @vftbl  115
     * @symbol ?canBeBuiltOver@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@@Z
     * @hash   47568903
     */
    virtual bool canBeBuiltOver(class BlockSource &, class BlockPos const &) const;
    /**
     * @vftbl  116
     * @symbol ?triggerEvent@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@HH@Z
     * @hash   870072936
     */
    virtual void triggerEvent(class BlockSource &, class BlockPos const &, int, int) const;
    /**
     * @vftbl  117
     * @symbol ?executeEvent@BlockLegacy@@UEBAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAVRenderParams@@@Z
     * @hash   -144941071
     */
    virtual void executeEvent(std::string const &, class RenderParams &) const;
    /**
     * @vftbl  118
     * @symbol ?executeEvent@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAVActor@@@Z
     * @hash   172780122
     */
    virtual void executeEvent(class BlockSource &, class BlockPos const &, class Block const &, std::string const &, class Actor &) const;
    /**
     * @vftbl  119
     * @symbol ?executeTrigger@BlockLegacy@@UEBA_NAEBVDefinitionTrigger@@AEAVRenderParams@@@Z
     * @hash   -1912207559
     */
    virtual bool executeTrigger(class DefinitionTrigger const &, class RenderParams &) const;
    /**
     * @vftbl  120
     * @symbol ?forceExecuteTrigger@BlockLegacy@@UEBAXAEBVDefinitionTrigger@@AEAVRenderParams@@@Z
     * @hash   1226059410
     */
    virtual void forceExecuteTrigger(class DefinitionTrigger const &, class RenderParams &) const;
    /**
     * @vftbl  121
     * @symbol ?getMobToSpawn@BlockLegacy@@UEBAPEBVMobSpawnerData@@AEBVSpawnConditions@@AEAVBlockSource@@@Z
     * @hash   -948450299
     */
    virtual class MobSpawnerData const * getMobToSpawn(class SpawnConditions const &, class BlockSource &) const;
    /**
     * @vftbl  122
     * @symbol ?shouldStopFalling@BlockLegacy@@UEBA_NAEAVActor@@@Z
     * @hash   -1005779135
     */
    virtual bool shouldStopFalling(class Actor &) const;
    /**
     * @vftbl  123
     * @hash   1488051906
     */
    virtual void __unk_vfn_123();
    /**
     * @vftbl  124
     * @symbol ?calcGroundFriction@BlockLegacy@@UEBAMAEBUIMobMovementProxy@@AEBVBlockPos@@@Z
     * @hash   -156423964
     */
    virtual float calcGroundFriction(struct IMobMovementProxy const &, class BlockPos const &) const;
    /**
     * @vftbl  125
     * @hash   1489898948
     */
    virtual void __unk_vfn_125();
    /**
     * @vftbl  126
     * @hash   1490822469
     */
    virtual void __unk_vfn_126();
    /**
     * @vftbl  127
     * @symbol ?getComparatorSignal@BlockLegacy@@UEBAHAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@E@Z
     * @hash   -1832896752
     */
    virtual int getComparatorSignal(class BlockSource &, class BlockPos const &, class Block const &, unsigned char) const;
    /**
     * @vftbl  128
     * @symbol ?canSlide@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@@Z
     * @hash   -1836001319
     */
    virtual bool canSlide(class BlockSource &, class BlockPos const &) const;
    /**
     * @vftbl  129
     * @symbol ?canSpawnAt@BlockLegacy@@UEBA_NAEBVBlockSource@@AEBVBlockPos@@@Z
     * @hash   1528550729
     */
    virtual bool canSpawnAt(class BlockSource const &, class BlockPos const &) const;
    /**
     * @vftbl  130
     * @symbol ?notifySpawnedAt@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@@Z
     * @hash   780557290
     */
    virtual void notifySpawnedAt(class BlockSource &, class BlockPos const &) const;
    /**
     * @vftbl  131
     * @hash   1514834015
     */
    virtual void __unk_vfn_131();
    /**
     * @vftbl  132
     * @symbol ?getIconYOffset@BlockLegacy@@UEBAHXZ
     * @hash   -1488451806
     */
    virtual int getIconYOffset() const;
    /**
     * @vftbl  133
     * @symbol ?buildDescriptionId@BlockLegacy@@UEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBVBlock@@@Z
     * @hash   -2143028083
     */
    virtual std::string buildDescriptionId(class Block const &) const;
    /**
     * @vftbl  134
     * @symbol ?isAuxValueRelevantForPicking@BlockLegacy@@UEBA_NXZ
     * @hash   -2079379730
     */
    virtual bool isAuxValueRelevantForPicking() const;
    /**
     * @vftbl  135
     * @symbol ?getColor@BlockLegacy@@UEBAHAEBVBlock@@@Z
     * @hash   -791953160
     */
    virtual int getColor(class Block const &) const;
    /**
     * @vftbl  136
     * @symbol ?getColor@BlockLegacy@@UEBAHAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@@Z
     * @hash   -1670626110
     */
    virtual int getColor(class BlockSource &, class BlockPos const &, class Block const &) const;
    /**
     * @vftbl  137
     * @symbol ?getColorAtPos@BlockLegacy@@UEBAHAEAVBlockSource@@AEBVBlockPos@@@Z
     * @hash   -1208413473
     */
    virtual int getColorAtPos(class BlockSource &, class BlockPos const &) const;
    /**
     * @vftbl  138
     * @symbol ?getColorForParticle@BlockLegacy@@UEBAHAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@@Z
     * @hash   1713216813
     */
    virtual int getColorForParticle(class BlockSource &, class BlockPos const &, class Block const &) const;
    /**
     * @vftbl  139
     * @symbol ?isSeasonTinted@BlockLegacy@@UEBA_NAEBVBlock@@AEAVBlockSource@@AEBVBlockPos@@@Z
     * @hash   -1454148185
     */
    virtual bool isSeasonTinted(class Block const &, class BlockSource &, class BlockPos const &) const;
    /**
     * @vftbl  140
     * @symbol ?onGraphicsModeChanged@BlockLegacy@@UEAAXAEBUBlockGraphicsModeChangeContext@@@Z
     * @hash   822908034
     */
    virtual void onGraphicsModeChanged(struct BlockGraphicsModeChangeContext const &);
    /**
     * @vftbl  141
     * @symbol ?getShadeBrightness@BlockLegacy@@UEBAMAEBVBlock@@@Z
     * @hash   8566218
     */
    virtual float getShadeBrightness(class Block const &) const;
    /**
     * @vftbl  142
     * @symbol ?getVisualShapeInWorld@BlockLegacy@@UEBAAEBVAABB@@AEBVBlock@@AEBVIConstBlockSource@@AEBVBlockPos@@AEAV2@_N@Z
     * @hash   1535993768
     */
    virtual class AABB const & getVisualShapeInWorld(class Block const &, class IConstBlockSource const &, class BlockPos const &, class AABB &, bool) const;
    /**
     * @vftbl  143
     * @symbol ?getVisualShape@BlockLegacy@@UEBAAEBVAABB@@AEBVBlock@@AEAV2@_N@Z
     * @hash   -810569168
     */
    virtual class AABB const & getVisualShape(class Block const &, class AABB &, bool) const;
    /**
     * @vftbl  144
     * @symbol ?getUIShape@BlockLegacy@@UEBAAEBVAABB@@AEBVBlock@@AEAV2@@Z
     * @hash   -146050970
     */
    virtual class AABB const & getUIShape(class Block const &, class AABB &) const;
    /**
     * @vftbl  145
     * @symbol ?telemetryVariant@BlockLegacy@@UEBAHAEAVBlockSource@@AEBVBlockPos@@@Z
     * @hash   -1112619977
     */
    virtual int telemetryVariant(class BlockSource &, class BlockPos const &) const;
    /**
     * @vftbl  146
     * @symbol ?getVariant@BlockLegacy@@UEBAHAEBVBlock@@@Z
     * @hash   -282568698
     */
    virtual int getVariant(class Block const &) const;
    /**
     * @vftbl  147
     * @symbol ?canSpawnOn@BlockLegacy@@UEBA_NPEAVActor@@@Z
     * @hash   -1414085771
     */
    virtual bool canSpawnOn(class Actor *) const;
    /**
     * @vftbl  148
     * @symbol ?getRenderBlock@BlockLegacy@@UEBAAEBVBlock@@XZ
     * @hash   -273188237
     */
    virtual class Block const & getRenderBlock() const;
    /**
     * @vftbl  149
     * @symbol ?getMappedFace@BlockLegacy@@UEBAEEAEBVBlock@@@Z
     * @hash   765539352
     */
    virtual unsigned char getMappedFace(unsigned char, class Block const &) const;
    /**
     * @vftbl  150
     * @symbol ?getFaceFlip@BlockLegacy@@UEBA?AW4Flip@@EAEBVBlock@@@Z
     * @hash   1240583644
     */
    virtual enum class Flip getFaceFlip(unsigned char, class Block const &) const;
    /**
     * @vftbl  151
     * @symbol ?animateTick@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@AEAVRandom@@@Z
     * @hash   2120671003
     */
    virtual void animateTick(class BlockSource &, class BlockPos const &, class Random &) const;
    /**
     * @vftbl  152
     * @symbol ?init@BlockLegacy@@UEAAAEAV1@XZ
     * @hash   133549109
     */
    virtual class BlockLegacy & init();
    /**
     * @vftbl  153
     * @symbol ?getLightEmission@BlockLegacy@@MEBA?AUBrightness@@AEBVBlock@@@Z
     * @hash   1768654037
     */
    virtual struct Brightness getLightEmission(class Block const &) const;
    /**
     * @vftbl  154
     * @symbol ?addState@BlockLegacy@@UEAAAEAV1@AEBVItemState@@@Z
     * @hash   1998625030
     */
    virtual class BlockLegacy & addState(class ItemState const &);
    /**
     * @vftbl  155
     * @symbol ?addState@BlockLegacy@@UEAAAEAV1@AEBVItemState@@_K@Z
     * @hash   -1093274226
     */
    virtual class BlockLegacy & addState(class ItemState const &, unsigned __int64);
    /**
     * @vftbl  156
     * @hash   1569252562
     */
    virtual void __unk_vfn_156();
    /**
     * @vftbl  157
     * @symbol ?getSilkTouchItemInstance@BlockLegacy@@UEBA?AVItemInstance@@AEBVBlock@@@Z
     * @hash   1057478861
     */
    virtual class ItemInstance getSilkTouchItemInstance(class Block const &) const;
    /**
     * @vftbl  158
     * @symbol ?tryLegacyUpgrade@BlockLegacy@@UEBAPEBVBlock@@G@Z
     * @hash   -1367088379
     */
    virtual class Block const * tryLegacyUpgrade(unsigned short) const;
    /**
     * @vftbl  159
     * @symbol ?dealsContactDamage@BlockLegacy@@UEBA_NAEBVActor@@AEBVBlock@@_N@Z
     * @hash   1930942120
     */
    virtual bool dealsContactDamage(class Actor const &, class Block const &, bool) const;
    /**
     * @vftbl  160
     * @symbol ?tryGetInfested@BlockLegacy@@UEBAPEBVBlock@@AEBV2@@Z
     * @hash   -2016779195
     */
    virtual class Block const * tryGetInfested(class Block const &) const;
    /**
     * @vftbl  161
     * @symbol ?tryGetUninfested@BlockLegacy@@UEBAPEBVBlock@@AEBV2@@Z
     * @hash   1278587372
     */
    virtual class Block const * tryGetUninfested(class Block const &) const;
    /**
     * @vftbl  162
     * @symbol ?_addHardCodedBlockComponents@BlockLegacy@@UEAAXXZ
     * @hash   -34671382
     */
    virtual void _addHardCodedBlockComponents();
    /**
     * @vftbl  163
     * @symbol ?onRemove@BlockLegacy@@MEBAXAEAVBlockSource@@AEBVBlockPos@@@Z
     * @hash   -1477022750
     */
    virtual void onRemove(class BlockSource &, class BlockPos const &) const;
    /**
     * @vftbl  164
     * @symbol ?onExploded@BlockLegacy@@MEBAXAEAVBlockSource@@AEBVBlockPos@@PEAVActor@@@Z
     * @hash   2053500848
     */
    virtual void onExploded(class BlockSource &, class BlockPos const &, class Actor *) const;
    /**
     * @vftbl  165
     * @symbol ?onStandOn@BlockLegacy@@MEBAXAEAVEntityContext@@AEBVBlockPos@@@Z
     * @hash   -866643527
     */
    virtual void onStandOn(class EntityContext &, class BlockPos const &) const;
    /**
     * @vftbl  166
     * @hash   1547586817
     */
    virtual void __unk_vfn_166();
    /**
     * @vftbl  167
     * @hash   1548510338
     */
    virtual void __unk_vfn_167();
    /**
     * @vftbl  168
     * @hash   1549433859
     */
    virtual void __unk_vfn_168();
    /**
     * @vftbl  169
     * @symbol ?onPlace@BlockLegacy@@MEBAXAEAVBlockSource@@AEBVBlockPos@@@Z
     * @hash   -1259327833
     */
    virtual void onPlace(class BlockSource &, class BlockPos const &) const;
    /**
     * @vftbl  170
     * @symbol ?onFallOn@BlockLegacy@@MEBAXAEAVBlockSource@@AEBVBlockPos@@AEAVActor@@M@Z
     * @hash   640514675
     */
    virtual void onFallOn(class BlockSource &, class BlockPos const &, class Actor &, float) const;
    /**
     * @vftbl  171
     * @symbol ?playerDestroy@BlockLegacy@@MEBAXAEAVPlayer@@AEBVBlockPos@@AEBVBlock@@@Z
     * @hash   1393336145
     */
    virtual void playerDestroy(class Player &, class BlockPos const &, class Block const &) const;
    /**
     * @vftbl  172
     * @hash   1630274140
     */
    virtual void __unk_vfn_172();
    /**
     * @vftbl  173
     * @symbol ?tick@BlockLegacy@@MEBAXAEAVBlockSource@@AEBVBlockPos@@AEAVRandom@@@Z
     * @hash   1488913331
     */
    virtual void tick(class BlockSource &, class BlockPos const &, class Random &) const;
    /**
     * @vftbl  174
     * @symbol ?randomTick@BlockLegacy@@MEBAXAEAVBlockSource@@AEBVBlockPos@@AEAVRandom@@@Z
     * @hash   -1769892112
     */
    virtual void randomTick(class BlockSource &, class BlockPos const &, class Random &) const;
    /**
     * @vftbl  175
     * @symbol ?shouldRandomTick@BlockLegacy@@MEBA_NXZ
     * @hash   1133135406
     */
    virtual bool shouldRandomTick() const;
    /**
     * @vftbl  176
     * @hash   1633968224
     */
    virtual void __unk_vfn_176();
    /**
     * @vftbl  177
     * @symbol ?clip@BlockLegacy@@MEBA?AVHitResult@@AEBVBlockSource@@AEBVBlockPos@@AEBVVec3@@2_N@Z
     * @hash   43206703
     */
    virtual class HitResult clip(class BlockSource const &, class BlockPos const &, class Vec3 const &, class Vec3 const &, bool) const;
    /**
     * @vftbl  178
     * @symbol ?use@BlockLegacy@@MEBA_NAEAVPlayer@@AEBVBlockPos@@E@Z
     * @hash   -313067230
     */
    virtual bool use(class Player &, class BlockPos const &, unsigned char) const;
    /**
     * @vftbl  179
     * @symbol ?canSurvive@BlockLegacy@@MEBA_NAEAVBlockSource@@AEBVBlockPos@@@Z
     * @hash   -903419709
     */
    virtual bool canSurvive(class BlockSource &, class BlockPos const &) const;
    /**
     * @vftbl  180
     * @symbol ?getRenderLayer@BlockLegacy@@MEBA?AW4BlockRenderLayer@@XZ
     * @hash   -1375088950
     */
    virtual enum class BlockRenderLayer getRenderLayer() const;
    /**
     * @vftbl  181
     * @symbol ?getRenderLayer@BlockLegacy@@MEBA?AW4BlockRenderLayer@@AEBVBlock@@AEAVBlockSource@@AEBVBlockPos@@@Z
     * @hash   -1223788810
     */
    virtual enum class BlockRenderLayer getRenderLayer(class Block const &, class BlockSource &, class BlockPos const &) const;
    /**
     * @vftbl  182
     * @symbol ?getExtraRenderLayers@BlockLegacy@@MEBAHXZ
     * @hash   -459845248
     */
    virtual int getExtraRenderLayers() const;
    /**
     * @vftbl  183
     * @symbol ?getExplosionResistance@BlockLegacy@@MEBAMPEAVActor@@@Z
     * @hash   1290018168
     */
    virtual float getExplosionResistance(class Actor *) const;
    /**
     * @vftbl  184
     * @symbol ?getEmissiveBrightness@BlockLegacy@@MEBA?AUBrightness@@AEBVBlock@@@Z
     * @hash   2022284014
     */
    virtual struct Brightness getEmissiveBrightness(class Block const &) const;
    /**
     * @vftbl  185
     * @symbol ?getMapColor@BlockLegacy@@MEBA?AVColor@mce@@AEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@@Z
     * @hash   -2053261599
     */
    virtual class mce::Color getMapColor(class BlockSource &, class BlockPos const &, class Block const &) const;
    /**
     * @vftbl  186
     * @hash   1662597375
     */
    virtual void __unk_vfn_186();
    /**
     * @vftbl  187
     * @symbol ?getResourceCount@BlockLegacy@@MEBAHAEAVRandomize@@AEBVBlock@@H@Z
     * @hash   1674995267
     */
    virtual int getResourceCount(class Randomize &, class Block const &, int) const;
    /**
     * @vftbl  188
     * @symbol ?getResourceItem@BlockLegacy@@MEBA?AVItemInstance@@AEAVRandomize@@AEBVBlock@@H@Z
     * @hash   1615881371
     */
    virtual class ItemInstance getResourceItem(class Randomize &, class Block const &, int) const;
    /**
     * @vftbl  189
     * @symbol ?_executeEvent@BlockLegacy@@EEBAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAV?$vector@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@$$CBV12@@std@@V?$allocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@$$CBV12@@std@@@2@@3@AEAVRenderParams@@@Z
     * @hash   462577818
     */
    virtual void _executeEvent(std::string const &, std::vector<struct std::pair<std::string const, std::string const>> &, class RenderParams &) const;
    /**
     * @vftbl  190
     * @symbol ?_executeTrigger@BlockLegacy@@EEBA_NAEBVDefinitionTrigger@@AEAV?$vector@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@$$CBV12@@std@@V?$allocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@$$CBV12@@std@@@2@@std@@AEAVRenderParams@@@Z
     * @hash   1084506714
     */
    virtual bool _executeTrigger(class DefinitionTrigger const &, std::vector<struct std::pair<std::string const, std::string const>> &, class RenderParams &) const;
    /**
     * @vftbl  191
     * @symbol ?_forceExecuteTrigger@BlockLegacy@@EEBAXAEBVDefinitionTrigger@@AEAV?$vector@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@$$CBV12@@std@@V?$allocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@$$CBV12@@std@@@2@@std@@AEAVRenderParams@@@Z
     * @hash   -1428651073
     */
    virtual void _forceExecuteTrigger(class DefinitionTrigger const &, std::vector<struct std::pair<std::string const, std::string const>> &, class RenderParams &) const;
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_BLOCKLEGACY
    /**
     * @symbol ?canBeDestroyedByWaterSpread@BlockLegacy@@UEBA_NXZ
     * @hash   -81639537
     */
    MCVAPI bool canBeDestroyedByWaterSpread() const;
    /**
     * @symbol ?canBeSilkTouched@BlockLegacy@@UEBA_NXZ
     * @hash   1956103272
     */
    MCVAPI bool canBeSilkTouched() const;
    /**
     * @symbol ?canDamperVibrations@BlockLegacy@@UEBA_NXZ
     * @hash   -1322861152
     */
    MCVAPI bool canDamperVibrations() const;
    /**
     * @symbol ?canHaveExtraData@BlockLegacy@@UEBA_NXZ
     * @hash   -323993148
     */
    MCVAPI bool canHaveExtraData() const;
    /**
     * @symbol ?canOccludeVibrations@BlockLegacy@@UEBA_NXZ
     * @hash   -1152791092
     */
    MCVAPI bool canOccludeVibrations() const;
    /**
     * @symbol ?causesFreezeEffect@BlockLegacy@@UEBA_NXZ
     * @hash   -2020910156
     */
    MCVAPI bool causesFreezeEffect() const;
    /**
     * @symbol ?detachesOnPistonMove@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@@Z
     * @hash   -1320353390
     */
    MCVAPI bool detachesOnPistonMove(class BlockSource &, class BlockPos const &) const;
    /**
     * @symbol ?hasComparatorSignal@BlockLegacy@@UEBA_NXZ
     * @hash   1512445498
     */
    MCVAPI bool hasComparatorSignal() const;
    /**
     * @symbol ?hasVariableLighting@BlockLegacy@@UEBA_NXZ
     * @hash   1469198596
     */
    MCVAPI bool hasVariableLighting() const;
    /**
     * @symbol ?isBounceBlock@BlockLegacy@@UEBA_NXZ
     * @hash   -1487594851
     */
    MCVAPI bool isBounceBlock() const;
    /**
     * @symbol ?isButtonBlock@BlockLegacy@@UEBA_NXZ
     * @hash   -1357730829
     */
    MCVAPI bool isButtonBlock() const;
    /**
     * @symbol ?isCandleCakeBlock@BlockLegacy@@UEBA_NXZ
     * @hash   -1373574080
     */
    MCVAPI bool isCandleCakeBlock() const;
    /**
     * @symbol ?isContainerBlock@BlockLegacy@@UEBA_NXZ
     * @hash   -373417672
     */
    MCVAPI bool isContainerBlock() const;
    /**
     * @symbol ?isCraftingBlock@BlockLegacy@@UEBA_NXZ
     * @hash   -593435677
     */
    MCVAPI bool isCraftingBlock() const;
    /**
     * @symbol ?isCropBlock@BlockLegacy@@MEBA_NXZ
     * @hash   529748750
     */
    MCVAPI bool isCropBlock() const;
    /**
     * @symbol ?isDoorBlock@BlockLegacy@@UEBA_NXZ
     * @hash   2114836727
     */
    MCVAPI bool isDoorBlock() const;
    /**
     * @symbol ?isFenceBlock@BlockLegacy@@UEBA_NXZ
     * @hash   357034632
     */
    MCVAPI bool isFenceBlock() const;
    /**
     * @symbol ?isFenceGateBlock@BlockLegacy@@UEBA_NXZ
     * @hash   -1012792291
     */
    MCVAPI bool isFenceGateBlock() const;
    /**
     * @symbol ?isHurtableBlock@BlockLegacy@@UEBA_NXZ
     * @hash   -1803710788
     */
    MCVAPI bool isHurtableBlock() const;
    /**
     * @symbol ?isInteractiveBlock@BlockLegacy@@MEBA_NXZ
     * @hash   685602896
     */
    MCVAPI bool isInteractiveBlock() const;
    /**
     * @symbol ?isLeverBlock@BlockLegacy@@UEBA_NXZ
     * @hash   -1475570641
     */
    MCVAPI bool isLeverBlock() const;
    /**
     * @symbol ?isMultifaceBlock@BlockLegacy@@UEBA_NXZ
     * @hash   -930996317
     */
    MCVAPI bool isMultifaceBlock() const;
    /**
     * @symbol ?isRailBlock@BlockLegacy@@UEBA_NXZ
     * @hash   -1225947885
     */
    MCVAPI bool isRailBlock() const;
    /**
     * @symbol ?isSignalSource@BlockLegacy@@UEBA_NXZ
     * @hash   1899241327
     */
    MCVAPI bool isSignalSource() const;
    /**
     * @symbol ?isSilentWhenJumpingOff@BlockLegacy@@UEBA_NXZ
     * @hash   -1583013802
     */
    MCVAPI bool isSilentWhenJumpingOff() const;
    /**
     * @symbol ?isSlabBlock@BlockLegacy@@UEBA_NXZ
     * @hash   -43650965
     */
    MCVAPI bool isSlabBlock() const;
    /**
     * @symbol ?isStairBlock@BlockLegacy@@UEBA_NXZ
     * @hash   -1037447312
     */
    MCVAPI bool isStairBlock() const;
    /**
     * @symbol ?isStemBlock@BlockLegacy@@UEBA_NXZ
     * @hash   -2118794020
     */
    MCVAPI bool isStemBlock() const;
    /**
     * @symbol ?isThinFenceBlock@BlockLegacy@@UEBA_NXZ
     * @hash   -704751711
     */
    MCVAPI bool isThinFenceBlock() const;
    /**
     * @symbol ?isWallBlock@BlockLegacy@@UEBA_NXZ
     * @hash   -1382181157
     */
    MCVAPI bool isWallBlock() const;
    /**
     * @symbol ?onPlayerPlacing@BlockLegacy@@MEBAXAEAVBlockSource@@AEBVBlockPos@@AEAVActor@@E@Z
     * @hash   -274139127
     */
    MCVAPI void onPlayerPlacing(class BlockSource &, class BlockPos const &, class Actor &, unsigned char) const;
    /**
     * @symbol ?onStepOff@BlockLegacy@@MEBAXAEAVActor@@AEBVBlockPos@@@Z
     * @hash   895989104
     */
    MCVAPI void onStepOff(class Actor &, class BlockPos const &) const;
    /**
     * @symbol ?onStepOn@BlockLegacy@@MEBAXAEAVActor@@AEBVBlockPos@@@Z
     * @hash   18287062
     */
    MCVAPI void onStepOn(class Actor &, class BlockPos const &) const;
    /**
     * @symbol ?pushesUpFallingBlocks@BlockLegacy@@UEBA_NXZ
     * @hash   -1304402100
     */
    MCVAPI bool pushesUpFallingBlocks() const;
    /**
     * @symbol ?shouldTickOnSetBlock@BlockLegacy@@MEBA_NXZ
     * @hash   -93042507
     */
    MCVAPI bool shouldTickOnSetBlock() const;
    /**
     * @symbol ?spawnBurnResources@BlockLegacy@@UEBA_NAEAVBlockSource@@MMM@Z
     * @hash   -409733381
     */
    MCVAPI bool spawnBurnResources(class BlockSource &, float, float, float) const;
    /**
     * @symbol ?waterSpreadCausesSpawn@BlockLegacy@@UEBA_NXZ
     * @hash   -1380877527
     */
    MCVAPI bool waterSpreadCausesSpawn() const;
#endif
    /**
     * @symbol ??0BlockLegacy@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HAEBVMaterial@@@Z
     * @hash   255165405
     */
    MCAPI BlockLegacy(std::string const &, int, class Material const &);
    /**
     * @symbol ?_isDataDrivingVanillaBlocksAndItems@BlockLegacy@@QEBA_NXZ
     * @hash   2037309698
     */
    MCAPI bool _isDataDrivingVanillaBlocksAndItems() const;
    /**
     * @symbol ?addAABB@BlockLegacy@@QEBA_NAEBVAABB@@PEBV2@AEAV?$vector@VAABB@@V?$allocator@VAABB@@@std@@@std@@@Z
     * @hash   1095123400
     */
    MCAPI bool addAABB(class AABB const &, class AABB const *, std::vector<class AABB> &) const;
    /**
     * @symbol ?addBlockProperties@BlockLegacy@@QEAAAEAV1@W4BlockProperty@@@Z
     * @hash   369207658
     */
    MCAPI class BlockLegacy & addBlockProperties(enum class BlockProperty);
    /**
     * @symbol ?addTag@BlockLegacy@@QEAAAEAV1@AEBVHashedString@@@Z
     * @hash   55905080
     */
    MCAPI class BlockLegacy & addTag(class HashedString const &);
    /**
     * @symbol ?buildDescriptionName@BlockLegacy@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBVBlock@@@Z
     * @hash   991886343
     */
    MCAPI std::string buildDescriptionName(class Block const &) const;
    /**
     * @symbol ?canInstatick@BlockLegacy@@QEBA_NXZ
     * @hash   -1692894828
     */
    MCAPI bool canInstatick() const;
    /**
     * @symbol ?createBlockPermutations@BlockLegacy@@QEAAXI@Z
     * @hash   246684580
     */
    MCAPI void createBlockPermutations(unsigned int);
    /**
     * @symbol ?createWeakPtr@BlockLegacy@@QEBA?AV?$WeakPtr@VBlockLegacy@@@@XZ
     * @hash   -1184968497
     */
    MCAPI class WeakPtr<class BlockLegacy> createWeakPtr() const;
    /**
     * @symbol ?forEachBlockPermutation@BlockLegacy@@QEBAXV?$function@$$A6A_NAEBVBlock@@@Z@std@@@Z
     * @hash   1870910754
     */
    MCAPI void forEachBlockPermutation(class std::function<bool (class Block const &)>) const;
    /**
     * @symbol ?forEachItemStateInstance@BlockLegacy@@QEBAXV?$function@$$A6A_NAEBVItemStateInstance@@@Z@std@@@Z
     * @hash   -1114757676
     */
    MCAPI void forEachItemStateInstance(class std::function<bool (class ItemStateInstance const &)>) const;
    /**
     * @symbol ?getAllowsRunes@BlockLegacy@@QEBA_NXZ
     * @hash   -1929636428
     */
    MCAPI bool getAllowsRunes() const;
    /**
     * @symbol ?getBlockEntityType@BlockLegacy@@QEBA?AW4BlockActorType@@XZ
     * @hash   -1475255736
     */
    MCAPI enum class BlockActorType getBlockEntityType() const;
    /**
     * @symbol ?getBlockItemId@BlockLegacy@@QEBAFXZ
     * @hash   1929932101
     */
    MCAPI short getBlockItemId() const;
    /**
     * @symbol ?getBlockState@BlockLegacy@@QEBAPEBVItemState@@AEBVHashedString@@@Z
     * @hash   -1975293058
     */
    MCAPI class ItemState const * getBlockState(class HashedString const &) const;
    /**
     * @symbol ?getBlockStateGroup@BlockLegacy@@QEAAPEAVBlockStateGroup@@XZ
     * @hash   376207959
     */
    MCAPI class BlockStateGroup * getBlockStateGroup();
    /**
     * @symbol ?getCommandNames@BlockLegacy@@QEBA?AV?$vector@UCommandName@@V?$allocator@UCommandName@@@std@@@std@@XZ
     * @hash   1897950710
     */
    MCAPI std::vector<struct CommandName> getCommandNames() const;
    /**
     * @symbol ?getCreativeCategory@BlockLegacy@@QEBA?AW4CreativeItemCategory@@XZ
     * @hash   676153306
     */
    MCAPI enum class CreativeItemCategory getCreativeCategory() const;
    /**
     * @symbol ?getDebugText@BlockLegacy@@QEBAXAEAV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@std@@AEBVBlockPos@@@Z
     * @hash   863688994
     */
    MCAPI void getDebugText(std::vector<std::string> &, class BlockPos const &) const;
    /**
     * @symbol ?getDefaultState@BlockLegacy@@QEBAAEBVBlock@@XZ
     * @hash   2126757300
     */
    MCAPI class Block const & getDefaultState() const;
    /**
     * @symbol ?getDescriptionId@BlockLegacy@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ
     * @hash   -1835214722
     */
    MCAPI std::string const & getDescriptionId() const;
    /**
     * @symbol ?getEntity@BlockLegacy@@QEBAAEBVEntityContext@@XZ
     * @hash   -1903582388
     */
    MCAPI class EntityContext const & getEntity() const;
    /**
     * @symbol ?getEntityForModification@BlockLegacy@@QEBAAEAVEntityContext@@XZ
     * @hash   581956628
     */
    MCAPI class EntityContext & getEntityForModification() const;
    /**
     * @symbol ?getEntityNoCheck@BlockLegacy@@QEBAAEBVEntityContext@@XZ
     * @hash   1971791124
     */
    MCAPI class EntityContext const & getEntityNoCheck() const;
    /**
     * @symbol ?getExperienceDrop@BlockLegacy@@QEBAHAEAVRandom@@@Z
     * @hash   -1008007429
     */
    MCAPI int getExperienceDrop(class Random &) const;
    /**
     * @symbol ?getMaterial@BlockLegacy@@QEBAAEBVMaterial@@XZ
     * @hash   2010900304
     */
    MCAPI class Material const & getMaterial() const;
    /**
     * @symbol ?getNamespace@BlockLegacy@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ
     * @hash   1803045974
     */
    MCAPI std::string const & getNamespace() const;
    /**
     * @symbol ?getRawNameHash@BlockLegacy@@QEBAAEBVHashedString@@XZ
     * @hash   458064324
     */
    MCAPI class HashedString const & getRawNameHash() const;
    /**
     * @symbol ?getRawNameId@BlockLegacy@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ
     * @hash   -303648164
     */
    MCAPI std::string const & getRawNameId() const;
    /**
     * @symbol ?getRequiredBaseGameVersion@BlockLegacy@@QEBAAEBVBaseGameVersion@@XZ
     * @hash   1260196310
     */
    MCAPI class BaseGameVersion const & getRequiredBaseGameVersion() const;
    /**
     * @symbol ?getResourceDrops@BlockLegacy@@QEBA?AV?$vector@VItemStack@@V?$allocator@VItemStack@@@std@@@std@@AEBVBlock@@AEAVRandomize@@AEBUResourceDropsContext@@@Z
     * @hash   -1356894795
     */
    MCAPI std::vector<class ItemStack> getResourceDrops(class Block const &, class Randomize &, struct ResourceDropsContext const &) const;
    /**
     * @symbol ?hasBlockEntity@BlockLegacy@@QEBA_NXZ
     * @hash   -1648664812
     */
    MCAPI bool hasBlockEntity() const;
    /**
     * @symbol ?hasProperty@BlockLegacy@@QEBA_NW4BlockProperty@@@Z
     * @hash   1175767459
     */
    MCAPI bool hasProperty(enum class BlockProperty) const;
    /**
     * @symbol ?hasState@BlockLegacy@@QEBA_NAEBVHashedString@@@Z
     * @hash   -375959817
     */
    MCAPI bool hasState(class HashedString const &) const;
    /**
     * @symbol ?hasState@BlockLegacy@@QEBA_NAEBVItemState@@@Z
     * @hash   -98337053
     */
    MCAPI bool hasState(class ItemState const &) const;
    /**
     * @symbol ?hasTag@BlockLegacy@@QEBA_NAEBVHashedString@@@Z
     * @hash   -119038267
     */
    MCAPI bool hasTag(class HashedString const &) const;
    /**
     * @symbol ?hasTag@BlockLegacy@@QEBA_NAEB_K@Z
     * @hash   -1292055085
     */
    MCAPI bool hasTag(unsigned __int64 const &) const;
    /**
     * @symbol ?initEntity@BlockLegacy@@QEAAXAEAVEntityRegistry@@@Z
     * @hash   -1424207322
     */
    MCAPI void initEntity(class EntityRegistry &);
    /**
     * @symbol ?initializeBlockStateGroup@BlockLegacy@@QEAAXXZ
     * @hash   -518202645
     */
    MCAPI void initializeBlockStateGroup();
    /**
     * @symbol ?isEmpty@BlockLegacy@@QEBA_NXZ
     * @hash   -333276606
     */
    MCAPI bool isEmpty() const;
    /**
     * @symbol ?isFullAndOpaque@BlockLegacy@@QEBA_NXZ
     * @hash   1341150018
     */
    MCAPI bool isFullAndOpaque() const;
    /**
     * @symbol ?isHeavy@BlockLegacy@@QEBA_NXZ
     * @hash   1214429234
     */
    MCAPI bool isHeavy() const;
    /**
     * @symbol ?isMotionBlockingBlock@BlockLegacy@@QEBA_NXZ
     * @hash   -1978776014
     */
    MCAPI bool isMotionBlockingBlock() const;
    /**
     * @symbol ?isSolidBlockingBlock@BlockLegacy@@QEBA_NXZ
     * @hash   346908884
     */
    MCAPI bool isSolidBlockingBlock() const;
    /**
     * @symbol ?isVanilla@BlockLegacy@@QEBA_NXZ
     * @hash   961622194
     */
    MCAPI bool isVanilla() const;
    /**
     * @symbol ?matchesStates@BlockLegacy@@QEBA_NAEBV1@@Z
     * @hash   -2070280336
     */
    MCAPI bool matchesStates(class BlockLegacy const &) const;
    /**
     * @symbol ??8BlockLegacy@@QEBA_NAEBVHashedString@@@Z
     * @hash   495416139
     */
    MCAPI bool operator==(class HashedString const &) const;
    /**
     * @symbol ?overrideBlockProperties@BlockLegacy@@QEAAAEAV1@W4BlockProperty@@@Z
     * @hash   -145555828
     */
    MCAPI class BlockLegacy & overrideBlockProperties(enum class BlockProperty);
    /**
     * @symbol ?setAllowsRunes@BlockLegacy@@QEAAAEAV1@_N@Z
     * @hash   1797063392
     */
    MCAPI class BlockLegacy & setAllowsRunes(bool);
    /**
     * @symbol ?setBlockTintType@BlockLegacy@@QEAAAEAV1@W4BlockTintType@@@Z
     * @hash   -2081998678
     */
    MCAPI class BlockLegacy & setBlockTintType(enum class BlockTintType);
    /**
     * @symbol ?setCanBeExtraBlock@BlockLegacy@@QEAAAEAV1@_N@Z
     * @hash   402304894
     */
    MCAPI class BlockLegacy & setCanBeExtraBlock(bool);
    /**
     * @symbol ?setCanBeOriginalSurface@BlockLegacy@@QEAAAEAV1@_N@Z
     * @hash   547801906
     */
    MCAPI class BlockLegacy & setCanBeOriginalSurface(bool);
    /**
     * @symbol ?setCategory@BlockLegacy@@QEAAAEAV1@W4CreativeItemCategory@@@Z
     * @hash   1844139458
     */
    MCAPI class BlockLegacy & setCategory(enum class CreativeItemCategory);
    /**
     * @symbol ?setCreativeEnumState@BlockLegacy@@QEAAAEAV1@AEBVItemState@@@Z
     * @hash   1197885324
     */
    MCAPI class BlockLegacy & setCreativeEnumState(class ItemState const &);
    /**
     * @symbol ?setCreativeGroup@BlockLegacy@@QEAAAEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z
     * @hash   -1071878172
     */
    MCAPI class BlockLegacy & setCreativeGroup(std::string const &);
    /**
     * @symbol ?setDefaultState@BlockLegacy@@QEAAXAEBVBlock@@@Z
     * @hash   863840162
     */
    MCAPI void setDefaultState(class Block const &);
    /**
     * @symbol ?setDestroyTime@BlockLegacy@@QEAAAEAV1@M@Z
     * @hash   850334172
     */
    MCAPI class BlockLegacy & setDestroyTime(float);
    /**
     * @symbol ?setExperienceDrop@BlockLegacy@@QEAAAEAV1@UIntRange@@@Z
     * @hash   -172067672
     */
    MCAPI class BlockLegacy & setExperienceDrop(struct IntRange);
    /**
     * @symbol ?setExplodeable@BlockLegacy@@QEAAAEAV1@M@Z
     * @hash   1635188892
     */
    MCAPI class BlockLegacy & setExplodeable(float);
    /**
     * @symbol ?setFlammable@BlockLegacy@@QEAAAEAV1@W4FlameOdds@@W4BurnOdds@@W4LavaFlammable@@@Z
     * @hash   752989856
     */
    MCAPI class BlockLegacy & setFlammable(enum class FlameOdds, enum class BurnOdds, enum class LavaFlammable);
    /**
     * @symbol ?setIgnoreBlockForInsideCubeRenderer@BlockLegacy@@QEAAX_N@Z
     * @hash   711011994
     */
    MCAPI void setIgnoreBlockForInsideCubeRenderer(bool);
    /**
     * @symbol ?setIsHiddenInCommands@BlockLegacy@@QEAAAEAV1@_N@Z
     * @hash   151089106
     */
    MCAPI class BlockLegacy & setIsHiddenInCommands(bool);
    /**
     * @symbol ?setIsInteraction@BlockLegacy@@QEAAX_N@Z
     * @hash   2101549784
     */
    MCAPI void setIsInteraction(bool);
    /**
     * @symbol ?setIsVanillaBlock@BlockLegacy@@QEAAX_N@Z
     * @hash   1701835594
     */
    MCAPI void setIsVanillaBlock(bool);
    /**
     * @symbol ?setLightBlock@BlockLegacy@@QEAAAEAV1@UBrightness@@@Z
     * @hash   -1963259086
     */
    MCAPI class BlockLegacy & setLightBlock(struct Brightness);
    /**
     * @symbol ?setLightEmission@BlockLegacy@@QEAAAEAV1@UBrightness@@@Z
     * @hash   40351904
     */
    MCAPI class BlockLegacy & setLightEmission(struct Brightness);
    /**
     * @symbol ?setMapColor@BlockLegacy@@QEAAAEAV1@AEBVColor@mce@@@Z
     * @hash   1165671716
     */
    MCAPI class BlockLegacy & setMapColor(class mce::Color const &);
    /**
     * @symbol ?setMinRequiredBaseGameVersion@BlockLegacy@@QEAAAEAV1@AEBVBaseGameVersion@@@Z
     * @hash   -306675488
     */
    MCAPI class BlockLegacy & setMinRequiredBaseGameVersion(class BaseGameVersion const &);
    /**
     * @symbol ?setNameId@BlockLegacy@@QEAAAEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z
     * @hash   421431174
     */
    MCAPI class BlockLegacy & setNameId(std::string const &);
    /**
     * @symbol ?setOnlyPermutationandDefaultState@BlockLegacy@@QEAAXV?$unique_ptr@VBlock@@U?$default_delete@VBlock@@@std@@@std@@@Z
     * @hash   -1512267640
     */
    MCAPI void setOnlyPermutationandDefaultState(std::unique_ptr<class Block>);
    /**
     * @symbol ?setPushesOutItems@BlockLegacy@@QEAAX_N@Z
     * @hash   -1109305654
     */
    MCAPI void setPushesOutItems(bool);
    /**
     * @symbol ?setRandomTicking@BlockLegacy@@QEBAX_N@Z
     * @hash   -603742522
     */
    MCAPI void setRandomTicking(bool) const;
    /**
     * @symbol ?setRandomTickingExtraLayer@BlockLegacy@@QEBAX_N@Z
     * @hash   -763302890
     */
    MCAPI void setRandomTickingExtraLayer(bool) const;
    /**
     * @symbol ?setReturnDefaultBlockOnUnidentifiedBlockState@BlockLegacy@@QEAAAEAV1@XZ
     * @hash   448153899
     */
    MCAPI class BlockLegacy & setReturnDefaultBlockOnUnidentifiedBlockState();
    /**
     * @symbol ?setSolid@BlockLegacy@@QEAAX_N@Z
     * @hash   588870072
     */
    MCAPI void setSolid(bool);
    /**
     * @symbol ?setVisualShape@BlockLegacy@@QEAAXAEBVAABB@@@Z
     * @hash   -1950794620
     */
    MCAPI void setVisualShape(class AABB const &);
    /**
     * @symbol ?setVisualShape@BlockLegacy@@QEAAXAEBVVec3@@0@Z
     * @hash   -615665728
     */
    MCAPI void setVisualShape(class Vec3 const &, class Vec3 const &);
    /**
     * @symbol ?tryGetStateFromLegacyData@BlockLegacy@@QEBAPEBVBlock@@G@Z
     * @hash   -996537747
     */
    MCAPI class Block const * tryGetStateFromLegacyData(unsigned short) const;
    /**
     * @symbol ?BLOCK_DESCRIPTION_PREFIX@BlockLegacy@@2V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@B
     * @hash   -129816167
     */
    MCAPI static std::string const BLOCK_DESCRIPTION_PREFIX;
    /**
     * @symbol ?SIZE_OFFSET@BlockLegacy@@2MB
     * @hash   1705602003
     */
    MCAPI static float const SIZE_OFFSET;
    /**
     * @symbol ?buildDescriptionIdFromNameInfo@BlockLegacy@@SA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBUNameInfo@1@@Z
     * @hash   1349240602
     */
    MCAPI static std::string buildDescriptionIdFromNameInfo(struct BlockLegacy::NameInfo const &);
    /**
     * @symbol ?extractBlockNameInfo@BlockLegacy@@SA?AUNameInfo@1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z
     * @hash   -1292894408
     */
    MCAPI static struct BlockLegacy::NameInfo extractBlockNameInfo(std::string const &);
    /**
     * @symbol ?getPlacementFacingAll@BlockLegacy@@SAEAEAVActor@@AEBVBlockPos@@M@Z
     * @hash   -334106876
     */
    MCAPI static unsigned char getPlacementFacingAll(class Actor &, class BlockPos const &, float);
    /**
     * @symbol ?getPlacementFacingAllExceptAxisY@BlockLegacy@@SAEAEAVActor@@AEBVBlockPos@@M@Z
     * @hash   964756866
     */
    MCAPI static unsigned char getPlacementFacingAllExceptAxisY(class Actor &, class BlockPos const &, float);
    /**
     * @symbol ?popResource@BlockLegacy@@SAPEAVItemActor@@AEAVBlockSource@@AEBVBlockPos@@AEBVItemInstance@@@Z
     * @hash   -1867082800
     */
    MCAPI static class ItemActor * popResource(class BlockSource &, class BlockPos const &, class ItemInstance const &);
    /**
     * @symbol ?popResource@BlockLegacy@@SAPEAVItemActor@@AEAVBlockSource@@AEBVBlockPos@@AEBVItemStack@@@Z
     * @hash   -64833846
     */
    MCAPI static class ItemActor * popResource(class BlockSource &, class BlockPos const &, class ItemStack const &);
    /**
     * @symbol ?spawnResources@BlockLegacy@@SAXAEAVBlockSource@@AEBVBlockPos@@AEAVRandomize@@PEAV?$vector@PEBVItem@@V?$allocator@PEBVItem@@@std@@@std@@M@Z
     * @hash   -717257039
     */
    MCAPI static void spawnResources(class BlockSource &, class BlockPos const &, class Randomize &, std::vector<class Item const *> *, float);

//protected:
    /**
     * @symbol ?_getBlockShape@BlockLegacy@@IEBA?AW4BlockShape@@XZ
     * @hash   -1435659339
     */
    MCAPI enum class BlockShape _getBlockShape() const;
    /**
     * @symbol ?clip@BlockLegacy@@IEBA?AVHitResult@@AEBVBlockSource@@AEBVBlockPos@@AEBVVec3@@2_NAEBVAABB@@@Z
     * @hash   -650936501
     */
    MCAPI class HitResult clip(class BlockSource const &, class BlockPos const &, class Vec3 const &, class Vec3 const &, bool, class AABB const &) const;
    /**
     * @symbol ?forEachBlockPermutationMutable@BlockLegacy@@IEAA_NV?$function@$$A6A_NAEAVBlock@@@Z@std@@@Z
     * @hash   1595723596
     */
    MCAPI bool forEachBlockPermutationMutable(class std::function<bool (class Block &)>);
    /**
     * @symbol ?getBurnOdds@BlockLegacy@@IEBAHXZ
     * @hash   889527738
     */
    MCAPI int getBurnOdds() const;
    /**
     * @symbol ?getDestroySpeed@BlockLegacy@@IEBAMXZ
     * @hash   -1305803689
     */
    MCAPI float getDestroySpeed() const;
    /**
     * @symbol ?getFlameOdds@BlockLegacy@@IEBAHXZ
     * @hash   320207362
     */
    MCAPI int getFlameOdds() const;
    /**
     * @symbol ?getFriction@BlockLegacy@@IEBAMXZ
     * @hash   -173352972
     */
    MCAPI float getFriction() const;
    /**
     * @symbol ?getLight@BlockLegacy@@IEBA?AUBrightness@@XZ
     * @hash   1175714641
     */
    MCAPI struct Brightness getLight() const;
    /**
     * @symbol ?isLavaFlammable@BlockLegacy@@IEBA_NXZ
     * @hash   576795425
     */
    MCAPI bool isLavaFlammable() const;
    /**
     * @symbol ?createAABBWithPixelCoordinates@BlockLegacy@@KA?AVAABB@@MMMMMM@Z
     * @hash   -738452751
     */
    MCAPI static class AABB createAABBWithPixelCoordinates(float, float, float, float, float, float);

//private:
    /**
     * @symbol ?initParams@BlockLegacy@@AEBAXAEAVRenderParams@@AEAVBlockSource@@AEBVBlockPos@@PEAVActor@@@Z
     * @hash   2084155440
     */
    MCAPI void initParams(class RenderParams &, class BlockSource &, class BlockPos const &, class Actor *) const;

protected:

private:

};