/**
 * @file  CelebrateHuntComponent.hpp
 * @note  This Header is auto generated by LiteLoaderBDS Toolchain.
 *
 */
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA
// Include Headers or Declare Types Here

#undef BEFORE_EXTRA

/**
 * @brief MC class CelebrateHuntComponent.
 *
 */
class CelebrateHuntComponent {

#define AFTER_EXTRA
// Add Member There

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_CELEBRATEHUNTCOMPONENT
public:
    class CelebrateHuntComponent& operator=(class CelebrateHuntComponent const &) = delete;
    CelebrateHuntComponent(class CelebrateHuntComponent const &) = delete;
    CelebrateHuntComponent() = delete;
#endif

public:
    /**
     * @symbol ?getCelebrateSound@CelebrateHuntComponent@@QEBA?BW4LevelSoundEvent@@AEBVMob@@@Z
     * @hash   -2051290581
     */
    MCAPI enum class LevelSoundEvent const getCelebrateSound(class Mob const &) const;
    /**
     * @symbol ?getCelebrateUntil@CelebrateHuntComponent@@QEBA?BUTick@@XZ
     * @hash   -1274128080
     */
    MCAPI struct Tick const getCelebrateUntil() const;
    /**
     * @symbol ?getNextSoundEventTick@CelebrateHuntComponent@@QEBA?BUTick@@XZ
     * @hash   -20876320
     */
    MCAPI struct Tick const getNextSoundEventTick() const;
    /**
     * @symbol ?isCelebrating@CelebrateHuntComponent@@QEBA_NXZ
     * @hash   1555004590
     */
    MCAPI bool isCelebrating() const;
    /**
     * @symbol ?setNextSoundEventTick@CelebrateHuntComponent@@QEAAXAEBVMob@@@Z
     * @hash   -1780933790
     */
    MCAPI void setNextSoundEventTick(class Mob const &);
    /**
     * @symbol ?startCelebrating@CelebrateHuntComponent@@QEAAXAEBUTick@@@Z
     * @hash   1110926736
     */
    MCAPI void startCelebrating(struct Tick const &);
    /**
     * @symbol ?stopCelebrating@CelebrateHuntComponent@@QEAAXXZ
     * @hash   1653632067
     */
    MCAPI void stopCelebrating();

};