/**
 * @file  ChestBlockActor.hpp
 * @note  This Header is auto generated by LiteLoaderBDS Toolchain.
 *
 */
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA
// Include Headers or Declare Types Here

#undef BEFORE_EXTRA

/**
 * @brief MC class ChestBlockActor.
 *
 */
class ChestBlockActor {

#define AFTER_EXTRA
// Add Member There

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_CHESTBLOCKACTOR
public:
    class ChestBlockActor& operator=(class ChestBlockActor const &) = delete;
    ChestBlockActor(class ChestBlockActor const &) = delete;
    ChestBlockActor() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_CHESTBLOCKACTOR
    /**
     * @symbol ?_canOpenThis@ChestBlockActor@@MEBA_NAEAVBlockSource@@@Z
     * @hash   415444177
     */
    MCVAPI bool _canOpenThis(class BlockSource &) const;
    /**
     * @symbol ?_detectEntityObstruction@ChestBlockActor@@MEBA_NAEAVBlockSource@@@Z
     * @hash   1621130431
     */
    MCVAPI bool _detectEntityObstruction(class BlockSource &) const;
    /**
     * @symbol ?_getUpdatePacket@ChestBlockActor@@MEAA?AV?$unique_ptr@VBlockActorDataPacket@@U?$default_delete@VBlockActorDataPacket@@@std@@@std@@AEAVBlockSource@@@Z
     * @hash   1501129362
     */
    MCVAPI std::unique_ptr<class BlockActorDataPacket> _getUpdatePacket(class BlockSource &);
    /**
     * @symbol ?_onUpdatePacket@ChestBlockActor@@MEAAXAEBVCompoundTag@@AEAVBlockSource@@@Z
     * @hash   -1375515072
     */
    MCVAPI void _onUpdatePacket(class CompoundTag const &, class BlockSource &);
    /**
     * @symbol ?addContentChangeListener@ChestBlockActor@@UEAAXPEAVContainerContentChangeListener@@@Z
     * @hash   -198869446
     */
    MCVAPI void addContentChangeListener(class ContainerContentChangeListener *);
    /**
     * @symbol ?canPullOutItem@ChestBlockActor@@UEBA_NAEAVBlockSource@@HHAEBVItemInstance@@@Z
     * @hash   -1938414640
     */
    MCVAPI bool canPullOutItem(class BlockSource &, int, int, class ItemInstance const &) const;
    /**
     * @symbol ?canPushInItem@ChestBlockActor@@UEBA_NAEAVBlockSource@@HHAEBVItemInstance@@@Z
     * @hash   -748346
     */
    MCVAPI bool canPushInItem(class BlockSource &, int, int, class ItemInstance const &) const;
    /**
     * @symbol ?clearCache@ChestBlockActor@@UEAAXXZ
     * @hash   965886883
     */
    MCVAPI void clearCache();
    /**
     * @symbol ?clearInventory@ChestBlockActor@@UEAAHH@Z
     * @hash   -1522491107
     */
    MCVAPI int clearInventory(int);
    /**
     * @symbol ?eraseLootTable@ChestBlockActor@@UEAAXXZ
     * @hash   272367182
     */
    MCVAPI void eraseLootTable();
    /**
     * @symbol ?getContainer@ChestBlockActor@@UEAAPEAVContainer@@XZ
     * @hash   -1602742410
     */
    MCVAPI class Container * getContainer();
    /**
     * @symbol ?getContainer@ChestBlockActor@@UEBAPEBVContainer@@XZ
     * @hash   -2030464270
     */
    MCVAPI class Container const * getContainer() const;
    /**
     * @symbol ?getContainerSize@ChestBlockActor@@UEBAHXZ
     * @hash   300671550
     */
    MCVAPI int getContainerSize() const;
    /**
     * @symbol ?getCrackEntity@ChestBlockActor@@UEAAPEAVBlockActor@@AEAVBlockSource@@AEBVBlockPos@@@Z
     * @hash   1780057577
     */
    MCVAPI class BlockActor * getCrackEntity(class BlockSource &, class BlockPos const &);
    /**
     * @symbol ?getDebugText@ChestBlockActor@@UEAAXAEAV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@std@@AEBVBlockPos@@@Z
     * @hash   -1460071448
     */
    MCVAPI void getDebugText(std::vector<std::string> &, class BlockPos const &);
    /**
     * @symbol ?getItem@ChestBlockActor@@UEBAAEBVItemStack@@H@Z
     * @hash   -2100763219
     */
    MCVAPI class ItemStack const & getItem(int) const;
    /**
     * @symbol ?getMaxStackSize@ChestBlockActor@@UEBAHXZ
     * @hash   1961401437
     */
    MCVAPI int getMaxStackSize() const;
    /**
     * @symbol ?getName@ChestBlockActor@@UEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ
     * @hash   1167199074
     */
    MCVAPI std::string getName() const;
    /**
     * @symbol ?getObstructionAABB@ChestBlockActor@@MEBA?AVAABB@@XZ
     * @hash   611956857
     */
    MCVAPI class AABB getObstructionAABB() const;
    /**
     * @symbol ?initializeContainerContents@ChestBlockActor@@UEAAXAEAVBlockSource@@@Z
     * @hash   -1676877413
     */
    MCVAPI void initializeContainerContents(class BlockSource &);
    /**
     * @symbol ?load@ChestBlockActor@@UEAAXAEAVLevel@@AEBVCompoundTag@@AEAVDataLoadHelper@@@Z
     * @hash   -1001396720
     */
    MCVAPI void load(class Level &, class CompoundTag const &, class DataLoadHelper &);
    /**
     * @symbol ?loadItems@ChestBlockActor@@UEAAXAEBVCompoundTag@@AEAVLevel@@@Z
     * @hash   149411798
     */
    MCVAPI void loadItems(class CompoundTag const &, class Level &);
    /**
     * @symbol ?onChanged@ChestBlockActor@@UEAAXAEAVBlockSource@@@Z
     * @hash   -375807519
     */
    MCVAPI void onChanged(class BlockSource &);
    /**
     * @symbol ?onMove@ChestBlockActor@@UEAAXXZ
     * @hash   1823120318
     */
    MCVAPI void onMove();
    /**
     * @symbol ?onNeighborChanged@ChestBlockActor@@UEAAXAEAVBlockSource@@AEBVBlockPos@@@Z
     * @hash   -331268425
     */
    MCVAPI void onNeighborChanged(class BlockSource &, class BlockPos const &);
    /**
     * @symbol ?onPlace@ChestBlockActor@@UEAAXAEAVBlockSource@@@Z
     * @hash   -596865330
     */
    MCVAPI void onPlace(class BlockSource &);
    /**
     * @symbol ?onRemoved@ChestBlockActor@@UEAAXAEAVBlockSource@@@Z
     * @hash   -2048971963
     */
    MCVAPI void onRemoved(class BlockSource &);
    /**
     * @symbol ?playCloseSound@ChestBlockActor@@MEAAXAEAVBlockSource@@@Z
     * @hash   1792833122
     */
    MCVAPI void playCloseSound(class BlockSource &);
    /**
     * @symbol ?playOpenSound@ChestBlockActor@@MEAAXAEAVBlockSource@@@Z
     * @hash   482443404
     */
    MCVAPI void playOpenSound(class BlockSource &);
    /**
     * @symbol ?removeContentChangeListener@ChestBlockActor@@UEAAXPEAVContainerContentChangeListener@@@Z
     * @hash   -782256339
     */
    MCVAPI void removeContentChangeListener(class ContainerContentChangeListener *);
    /**
     * @symbol ?save@ChestBlockActor@@UEBA_NAEAVCompoundTag@@@Z
     * @hash   610288527
     */
    MCVAPI bool save(class CompoundTag &) const;
    /**
     * @symbol ?saveItemInstanceData@ChestBlockActor@@UEAA_NAEAVCompoundTag@@@Z
     * @hash   1348766190
     */
    MCVAPI bool saveItemInstanceData(class CompoundTag &);
    /**
     * @symbol ?saveItems@ChestBlockActor@@UEBA_NAEAVCompoundTag@@@Z
     * @hash   213330153
     */
    MCVAPI bool saveItems(class CompoundTag &) const;
    /**
     * @symbol ?serverInitItemStackIds@ChestBlockActor@@UEAAXHHV?$function@$$A6AXHAEBVItemStack@@@Z@std@@@Z
     * @hash   -1599389630
     */
    MCVAPI void serverInitItemStackIds(int, int, class std::function<void (int, class ItemStack const &)>);
    /**
     * @symbol ?setContainerChanged@ChestBlockActor@@UEAAXH@Z
     * @hash   1863276556
     */
    MCVAPI void setContainerChanged(int);
    /**
     * @symbol ?setItem@ChestBlockActor@@UEAAXHAEBVItemStack@@@Z
     * @hash   1978412728
     */
    MCVAPI void setItem(int, class ItemStack const &);
    /**
     * @symbol ?setItemWithForceBalance@ChestBlockActor@@UEAAXHAEBVItemStack@@_N@Z
     * @hash   803327261
     */
    MCVAPI void setItemWithForceBalance(int, class ItemStack const &, bool);
    /**
     * @symbol ?startOpen@ChestBlockActor@@UEAAXAEAVPlayer@@@Z
     * @hash   -258908711
     */
    MCVAPI void startOpen(class Player &);
    /**
     * @symbol ?stopOpen@ChestBlockActor@@UEAAXAEAVPlayer@@@Z
     * @hash   -721050647
     */
    MCVAPI void stopOpen(class Player &);
    /**
     * @symbol ?tick@ChestBlockActor@@UEAAXAEAVBlockSource@@@Z
     * @hash   927190121
     */
    MCVAPI void tick(class BlockSource &);
    /**
     * @symbol ?triggerEvent@ChestBlockActor@@UEAAXHH@Z
     * @hash   -1448886400
     */
    MCVAPI void triggerEvent(int, int);
    /**
     * @symbol ??1ChestBlockActor@@UEAA@XZ
     * @hash   -761959448
     */
    MCVAPI ~ChestBlockActor();
#endif
    /**
     * @symbol ??0ChestBlockActor@@QEAA@W4BlockActorType@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4BlockActorRendererId@@AEBVBlockPos@@_N@Z
     * @hash   1712214164
     */
    MCAPI ChestBlockActor(enum class BlockActorType, std::string const &, enum class BlockActorRendererId, class BlockPos const &, bool);
    /**
     * @symbol ?canOpen@ChestBlockActor@@QEBA_NAEAVBlockSource@@@Z
     * @hash   -475234773
     */
    MCAPI bool canOpen(class BlockSource &) const;
    /**
     * @symbol ?canPairWith@ChestBlockActor@@QEAA_NPEAVBlockActor@@AEAVBlockSource@@@Z
     * @hash   -1546515163
     */
    MCAPI bool canPairWith(class BlockActor *, class BlockSource &);
    /**
     * @symbol ?forceCloseChest@ChestBlockActor@@QEAAXAEAVBlockSource@@@Z
     * @hash   1023864876
     */
    MCAPI void forceCloseChest(class BlockSource &);
    /**
     * @symbol ?getOpenCount@ChestBlockActor@@QEBAHXZ
     * @hash   729403044
     */
    MCAPI int getOpenCount() const;
    /**
     * @symbol ?getOpenness@ChestBlockActor@@QEBAMXZ
     * @hash   662285172
     */
    MCAPI float getOpenness() const;
    /**
     * @symbol ?getPairedChestPosition@ChestBlockActor@@QEAAAEBVBlockPos@@XZ
     * @hash   1229747676
     */
    MCAPI class BlockPos const & getPairedChestPosition();
    /**
     * @symbol ?isFindable@ChestBlockActor@@QEBA_NXZ
     * @hash   -394264178
     */
    MCAPI bool isFindable() const;
    /**
     * @symbol ?isLargeChest@ChestBlockActor@@QEBA_NXZ
     * @hash   -1314719746
     */
    MCAPI bool isLargeChest() const;
    /**
     * @symbol ?onMove@ChestBlockActor@@QEAAXAEAVBlockSource@@AEBVBlockPos@@1@Z
     * @hash   -1278191670
     */
    MCAPI void onMove(class BlockSource &, class BlockPos const &, class BlockPos const &);
    /**
     * @symbol ?openBy@ChestBlockActor@@QEAAXAEAVPlayer@@@Z
     * @hash   -247466022
     */
    MCAPI void openBy(class Player &);
    /**
     * @symbol ?pairWith@ChestBlockActor@@QEAAXPEAV1@_N@Z
     * @hash   -1153386376
     */
    MCAPI void pairWith(class ChestBlockActor *, bool);
    /**
     * @symbol ?setFindable@ChestBlockActor@@QEAAX_N@Z
     * @hash   -2091414176
     */
    MCAPI void setFindable(bool);
    /**
     * @symbol ?unpair@ChestBlockActor@@QEAAXAEAVBlockSource@@@Z
     * @hash   2033952816
     */
    MCAPI void unpair(class BlockSource &);

//protected:
    /**
     * @symbol ?_getCenter@ChestBlockActor@@IEAAXAEAM00@Z
     * @hash   -1769963294
     */
    MCAPI void _getCenter(float &, float &, float &);

//private:
    /**
     * @symbol ?_closeChest@ChestBlockActor@@AEAAXAEAVBlockSource@@PEAVPlayer@@@Z
     * @hash   1535409742
     */
    MCAPI void _closeChest(class BlockSource &, class Player *);
    /**
     * @symbol ?_saveClientSideState@ChestBlockActor@@AEBA_NAEAVCompoundTag@@@Z
     * @hash   791280156
     */
    MCAPI bool _saveClientSideState(class CompoundTag &) const;
    /**
     * @symbol ?_tryToPairWith@ChestBlockActor@@AEAAXAEAVBlockSource@@AEBVBlockPos@@@Z
     * @hash   1152004296
     */
    MCAPI void _tryToPairWith(class BlockSource &, class BlockPos const &);
    /**
     * @symbol ?_unpair@ChestBlockActor@@AEAAXXZ
     * @hash   1064866149
     */
    MCAPI void _unpair();

protected:

private:

};