/**
 * @file  ChunkKey.hpp
 * @note  This Header is auto generated by LiteLoaderBDS Toolchain.
 *
 */
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

/**
 * @brief MC class ChunkKey.
 *
 */
class ChunkKey {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_CHUNKKEY
public:
    class ChunkKey& operator=(class ChunkKey const &) = delete;
    ChunkKey(class ChunkKey const &) = delete;
    ChunkKey() = delete;
#endif

public:
    /**
     * @symbol ??0ChunkKey@@QEAA@AEBVLevelChunk@@@Z
     * @hash   -242611903
     */
    MCAPI ChunkKey(class LevelChunk const &);
    /**
     * @symbol ??0ChunkKey@@QEAA@AEBVChunkPos@@V?$AutomaticID@VDimension@@H@@@Z
     * @hash   484481962
     */
    MCAPI ChunkKey(class ChunkPos const &, class AutomaticID<class Dimension, int>);
    /**
     * @symbol ?asSpan@ChunkKey@@QEBA?AV?$basic_string_span@$$CBD$0?0@gsl@@XZ
     * @hash   1016255160
     */
    MCAPI class gsl::basic_string_span<char const, -1> asSpan() const;
    /**
     * @symbol ?hashCode@ChunkKey@@QEBA_KXZ
     * @hash   1253700827
     */
    MCAPI unsigned __int64 hashCode() const;

};