/**
 * @file  CircleAroundAnchorDefinition.hpp
 * @note  This Header is auto generated by LiteLoaderBDS Toolchain.
 *
 */
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "JsonUtil.hpp"

#define BEFORE_EXTRA
// Include Headers or Declare Types Here

#undef BEFORE_EXTRA

/**
 * @brief MC class CircleAroundAnchorDefinition.
 *
 */
class CircleAroundAnchorDefinition {

#define AFTER_EXTRA
// Add Member There

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_CIRCLEAROUNDANCHORDEFINITION
public:
    class CircleAroundAnchorDefinition& operator=(class CircleAroundAnchorDefinition const &) = delete;
    CircleAroundAnchorDefinition(class CircleAroundAnchorDefinition const &) = delete;
#endif

public:
    /**
     * @symbol ??0CircleAroundAnchorDefinition@@QEAA@XZ
     * @hash   -719355567
     */
    MCAPI CircleAroundAnchorDefinition();
    /**
     * @symbol ?initialize@CircleAroundAnchorDefinition@@QEAAXAEAVEntityContext@@AEAVCircleAroundAnchorGoal@@@Z
     * @hash   -1738373425
     */
    MCAPI void initialize(class EntityContext &, class CircleAroundAnchorGoal &);
    /**
     * @symbol ?buildSchema@CircleAroundAnchorDefinition@@SAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAV?$shared_ptr@V?$JsonSchemaObjectNode@VEmptyClass@JsonUtil@@VCircleAroundAnchorDefinition@@@JsonUtil@@@3@@Z
     * @hash   -1076979489
     */
    MCAPI static void buildSchema(std::string const &, class std::shared_ptr<class JsonUtil::JsonSchemaObjectNode<class JsonUtil::EmptyClass, class CircleAroundAnchorDefinition>> &);

};