/**
 * @file  CompletedUsingItemPacket.hpp
 * @note  This Header is auto generated by LiteLoaderBDS Toolchain.
 *
 */
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "Packet.hpp"

#define BEFORE_EXTRA
// Include Headers or Declare Types Here

#undef BEFORE_EXTRA

/**
 * @brief MC class CompletedUsingItemPacket.
 *
 */
class CompletedUsingItemPacket : public Packet {

#define AFTER_EXTRA
// Add Member There

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_COMPLETEDUSINGITEMPACKET
public:
    class CompletedUsingItemPacket& operator=(class CompletedUsingItemPacket const &) = delete;
    CompletedUsingItemPacket(class CompletedUsingItemPacket const &) = delete;
#endif

public:
    /**
     * @vftbl  0
     * @hash   -1739671906
     */
    virtual ~CompletedUsingItemPacket();
    /**
     * @vftbl  1
     * @symbol ?getId@CompletedUsingItemPacket@@UEBA?AW4MinecraftPacketIds@@XZ
     * @hash   1956422986
     */
    virtual enum class MinecraftPacketIds getId() const;
    /**
     * @vftbl  2
     * @symbol ?getName@CompletedUsingItemPacket@@UEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ
     * @hash   -1712000009
     */
    virtual std::string getName() const;
    /**
     * @vftbl  3
     * @symbol ?write@CompletedUsingItemPacket@@UEBAXAEAVBinaryStream@@@Z
     * @hash   -327015216
     */
    virtual void write(class BinaryStream &) const;
    /**
     * @vftbl  6
     * @symbol ?_read@CompletedUsingItemPacket@@EEAA?AW4StreamReadResult@@AEAVReadOnlyBinaryStream@@@Z
     * @hash   -358582096
     */
    virtual enum class StreamReadResult _read(class ReadOnlyBinaryStream &);
    /**
     * @symbol ??0CompletedUsingItemPacket@@QEAA@XZ
     * @hash   809998816
     */
    MCAPI CompletedUsingItemPacket();
    /**
     * @symbol ??0CompletedUsingItemPacket@@QEAA@FH@Z
     * @hash   563813299
     */
    MCAPI CompletedUsingItemPacket(short, int);

};