/**
 * @file  EntityGlobalComponentsUtility.hpp
 * @note  This Header is auto generated by LiteLoaderBDS Toolchain.
 *
 */
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA
// Include Headers or Declare Types Here

#undef BEFORE_EXTRA

/**
 * @brief MC namespace EntityGlobalComponentsUtility.
 *
 */
namespace EntityGlobalComponentsUtility {

#define AFTER_EXTRA
// Add Member There

#undef AFTER_EXTRA
    /**
     * @symbol ?initializeGlobalComponents@EntityGlobalComponentsUtility@@YAXAEAVEntityRegistry@@@Z
     * @hash   -640227027
     */
    MCAPI void initializeGlobalComponents(class EntityRegistry &);
    /**
     * @symbol ?removeGlobalComponents@EntityGlobalComponentsUtility@@YAXAEAVEntityRegistry@@@Z
     * @hash   -670259811
     */
    MCAPI void removeGlobalComponents(class EntityRegistry &);

};