/**
 * @file  FoodItemComponentLegacy.hpp
 * @note  This Header is auto generated by LiteLoaderBDS Toolchain.
 *
 */
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "Json.hpp"

#define BEFORE_EXTRA
// Include Headers or Declare Types Here

#undef BEFORE_EXTRA

/**
 * @brief MC class FoodItemComponentLegacy.
 *
 */
class FoodItemComponentLegacy {

#define AFTER_EXTRA
// Add Member There

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_FOODITEMCOMPONENTLEGACY
public:
    class FoodItemComponentLegacy& operator=(class FoodItemComponentLegacy const &) = delete;
    FoodItemComponentLegacy(class FoodItemComponentLegacy const &) = delete;
    FoodItemComponentLegacy() = delete;
#endif

public:
    /**
     * @vftbl  0
     * @hash   -1770349021
     */
    virtual ~FoodItemComponentLegacy();
    /**
     * @vftbl  1
     * @symbol ?getNutrition@FoodItemComponentLegacy@@UEBAHXZ
     * @hash   -13565528
     */
    virtual int getNutrition() const;
    /**
     * @vftbl  2
     * @symbol ?getSaturationModifier@FoodItemComponentLegacy@@UEBAMXZ
     * @hash   1662899032
     */
    virtual float getSaturationModifier() const;
    /**
     * @vftbl  3
     * @symbol ?canAlwaysEat@FoodItemComponentLegacy@@UEBA_NXZ
     * @hash   2113221916
     */
    virtual bool canAlwaysEat() const;
    /**
     * @vftbl  4
     * @symbol ?eatItem@FoodItemComponentLegacy@@UEAAPEBVItem@@AEAVItemStack@@AEAVActor@@AEAVLevel@@@Z
     * @hash   -437054693
     */
    virtual class Item const * eatItem(class ItemStack &, class Actor &, class Level &);
    /**
     * @vftbl  5
     * @symbol ?use@FoodItemComponentLegacy@@UEAA_NAEAVItemStack@@AEAVPlayer@@@Z
     * @hash   -758873689
     */
    virtual bool use(class ItemStack &, class Player &);
    /**
     * @vftbl  6
     * @symbol ?useTimeDepleted@FoodItemComponentLegacy@@UEAAPEBVItem@@AEAVItemStack@@AEAVPlayer@@AEAVLevel@@@Z
     * @hash   -1551660981
     */
    virtual class Item const * useTimeDepleted(class ItemStack &, class Player &, class Level &);
    /**
     * @symbol ??0FoodItemComponentLegacy@@QEAA@AEAVItem@@@Z
     * @hash   -1715714942
     */
    MCAPI FoodItemComponentLegacy(class Item &);
    /**
     * @symbol ?buildNetworkTag@FoodItemComponentLegacy@@QEBA?AV?$unique_ptr@VCompoundTag@@U?$default_delete@VCompoundTag@@@std@@@std@@XZ
     * @hash   849066552
     */
    MCAPI std::unique_ptr<class CompoundTag> buildNetworkTag() const;
    /**
     * @symbol ?init@FoodItemComponentLegacy@@QEAA_NAEAVValue@Json@@AEBVSemVersion@@@Z
     * @hash   -405077326
     */
    MCAPI bool init(class Json::Value &, class SemVersion const &);
    /**
     * @symbol ?initializeFromNetwork@FoodItemComponentLegacy@@SA?AVValue@Json@@AEBVCompoundTag@@@Z
     * @hash   -724681357
     */
    MCAPI static class Json::Value initializeFromNetwork(class CompoundTag const &);

//private:
    /**
     * @symbol ?_applyEatEffects@FoodItemComponentLegacy@@AEAAXAEBVItemStack@@AEAVActor@@AEAVLevel@@@Z
     * @hash   1060311829
     */
    MCAPI void _applyEatEffects(class ItemStack const &, class Actor &, class Level &);
    /**
     * @symbol ?_loadEffects@FoodItemComponentLegacy@@AEAAXAEAVValue@Json@@@Z
     * @hash   -1150741153
     */
    MCAPI void _loadEffects(class Json::Value &);
    /**
     * @symbol ?_loadRemoveEffects@FoodItemComponentLegacy@@AEAAXAEAVValue@Json@@@Z
     * @hash   -1381436029
     */
    MCAPI void _loadRemoveEffects(class Json::Value &);

private:

};