/**
 * @file  GetRidingHeightUtility.hpp
 * @note  This Header is auto generated by LiteLoaderBDS Toolchain.
 *
 */
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

/**
 * @brief MC namespace GetRidingHeightUtility.
 *
 */
namespace GetRidingHeightUtility {

#define AFTER_EXTRA

#undef AFTER_EXTRA
    /**
     * @symbol ?getRidingHeight@GetRidingHeightUtility@@YAMAEBVSynchedActorData@@PEBURidingHeightComponent@@PEBUAdultRidingHeightOffsetComponent@@M@Z
     * @hash   -912157799
     */
    MCAPI float getRidingHeight(class SynchedActorData const &, struct RidingHeightComponent const *, struct AdultRidingHeightOffsetComponent const *, float);

};