/**
 * @file  HitDetection.hpp
 * @note  This Header is auto generated by LiteLoaderBDS Toolchain.
 *
 */
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA
// Include Headers or Declare Types Here

#undef BEFORE_EXTRA

/**
 * @brief MC namespace HitDetection.
 *
 */
namespace HitDetection {

#define AFTER_EXTRA
// Add Member There

#undef AFTER_EXTRA
    /**
     * @symbol ?searchActors@HitDetection@@YAXAEBVVec3@@M0AEBVAABB@@PEAVActor@@PEAVPlayer@@AEAMAEAPEAV4@AEAV2@_N@Z
     * @hash   1897985702
     */
    MCAPI void searchActors(class Vec3 const &, float, class Vec3 const &, class AABB const &, class Actor *, class Player *, float &, class Actor *&, class Vec3 &, bool);

};