/**
 * @file  PushThroughDefinition.hpp
 * @note  This Header is auto generated by LiteLoaderBDS Toolchain.
 *
 */
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "JsonUtil.hpp"

#define BEFORE_EXTRA
// Include Headers or Declare Types Here

#undef BEFORE_EXTRA

/**
 * @brief MC structure PushThroughDefinition.
 *
 */
struct PushThroughDefinition {

#define AFTER_EXTRA
// Add Member There

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_PUSHTHROUGHDEFINITION
public:
    struct PushThroughDefinition& operator=(struct PushThroughDefinition const &) = delete;
    PushThroughDefinition(struct PushThroughDefinition const &) = delete;
    PushThroughDefinition() = delete;
#endif

public:
    /**
     * @symbol ?initialize@PushThroughDefinition@@QEAAXAEAVEntityContext@@@Z
     * @hash   515388526
     */
    MCAPI void initialize(class EntityContext &);
    /**
     * @symbol ?buildSchema@PushThroughDefinition@@SAXAEAV?$shared_ptr@V?$JsonSchemaObjectNode@VEmptyClass@JsonUtil@@UPushThroughDefinition@@@JsonUtil@@@std@@@Z
     * @hash   1990825402
     */
    MCAPI static void buildSchema(class std::shared_ptr<class JsonUtil::JsonSchemaObjectNode<class JsonUtil::EmptyClass, struct PushThroughDefinition>> &);

};