/**
 * @file  RideCommand.hpp
 * @note  This Header is auto generated by LiteLoaderBDS Toolchain.
 *
 */
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "Command.hpp"

#define BEFORE_EXTRA
// Include Headers or Declare Types Here

#undef BEFORE_EXTRA

/**
 * @brief MC class RideCommand.
 *
 */
class RideCommand : public Command {

#define AFTER_EXTRA
// Add Member There

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_RIDECOMMAND
public:
    class RideCommand& operator=(class RideCommand const &) = delete;
    RideCommand(class RideCommand const &) = delete;
    RideCommand() = delete;
#endif

public:
    /**
     * @vftbl  0
     * @hash   1288705793
     */
    virtual ~RideCommand();
    /**
     * @vftbl  1
     * @symbol ?execute@RideCommand@@UEBAXAEBVCommandOrigin@@AEAVCommandOutput@@@Z
     * @hash   233897520
     */
    virtual void execute(class CommandOrigin const &, class CommandOutput &) const;
    /**
     * @symbol ?setup@RideCommand@@SAXAEAVCommandRegistry@@@Z
     * @hash   -1761640640
     */
    MCAPI static void setup(class CommandRegistry &);

//private:
    /**
     * @symbol ?evictPassengers@RideCommand@@AEBAXAEBVCommandOrigin@@AEAVCommandOutput@@@Z
     * @hash   1661616674
     */
    MCAPI void evictPassengers(class CommandOrigin const &, class CommandOutput &) const;
    /**
     * @symbol ?startRiding@RideCommand@@AEBAXAEBVCommandOrigin@@AEAVCommandOutput@@@Z
     * @hash   177534935
     */
    MCAPI void startRiding(class CommandOrigin const &, class CommandOutput &) const;
    /**
     * @symbol ?stopRiding@RideCommand@@AEBAXAEBVCommandOrigin@@AEAVCommandOutput@@@Z
     * @hash   1757325271
     */
    MCAPI void stopRiding(class CommandOrigin const &, class CommandOutput &) const;
    /**
     * @symbol ?summonPassenger@RideCommand@@AEBAXAEBVCommandOrigin@@AEAVCommandOutput@@@Z
     * @hash   -157613015
     */
    MCAPI void summonPassenger(class CommandOrigin const &, class CommandOutput &) const;
    /**
     * @symbol ?summonVehicle@RideCommand@@AEBAXAEBVCommandOrigin@@AEAVCommandOutput@@@Z
     * @hash   817801035
     */
    MCAPI void summonVehicle(class CommandOrigin const &, class CommandOutput &) const;

private:

};