/**
 * @file  TimerComponent.hpp
 * @note  This Header is auto generated by LiteLoaderBDS Toolchain.
 *
 */
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA
// Include Headers or Declare Types Here

#undef BEFORE_EXTRA

/**
 * @brief MC class TimerComponent.
 *
 */
class TimerComponent {

#define AFTER_EXTRA
// Add Member There

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_TIMERCOMPONENT
public:
    class TimerComponent& operator=(class TimerComponent const &) = delete;
    TimerComponent(class TimerComponent const &) = delete;
#endif

public:
    /**
     * @symbol ??0TimerComponent@@QEAA@XZ
     * @hash   -1609995356
     */
    MCAPI TimerComponent();
    /**
     * @symbol ?addAdditionalSaveData@TimerComponent@@QEBAXAEAVCompoundTag@@@Z
     * @hash   2068490520
     */
    MCAPI void addAdditionalSaveData(class CompoundTag &) const;
    /**
     * @symbol ?getHasExecuted@TimerComponent@@QEBA_NXZ
     * @hash   1775484452
     */
    MCAPI bool getHasExecuted() const;
    /**
     * @symbol ?getLooping@TimerComponent@@QEBA_NXZ
     * @hash   -1296074626
     */
    MCAPI bool getLooping() const;
    /**
     * @symbol ?getTimeStamp@TimerComponent@@QEAA_KAEBVLevel@@@Z
     * @hash   2136803236
     */
    MCAPI unsigned __int64 getTimeStamp(class Level const &);
    /**
     * @symbol ??4TimerComponent@@QEAAAEAV0@$$QEAV0@@Z
     * @hash   1268358332
     */
    MCAPI class TimerComponent & operator=(class TimerComponent &&);
    /**
     * @symbol ?readAdditionalSaveData@TimerComponent@@QEAAXAEAVActor@@AEBVCompoundTag@@AEAVDataLoadHelper@@@Z
     * @hash   -1266462486
     */
    MCAPI void readAdditionalSaveData(class Actor &, class CompoundTag const &, class DataLoadHelper &);
    /**
     * @symbol ?restartTimer@TimerComponent@@QEAAXAEAVActor@@@Z
     * @hash   -1002382966
     */
    MCAPI void restartTimer(class Actor &);
    /**
     * @symbol ?setHasExecuted@TimerComponent@@QEAAX_N@Z
     * @hash   765321200
     */
    MCAPI void setHasExecuted(bool);

//private:
    /**
     * @symbol ?getRandomTime@TimerComponent@@AEAAHAEAVActor@@@Z
     * @hash   1359668408
     */
    MCAPI int getRandomTime(class Actor &);

private:

};