#pragma once

#include "mc/_HeaderOutputPredefine.h"

enum class BlockProperty : uint64 {
    // bitfield representation
    None                             = 0,
    Stair                            = 1ull << 0,
    HalfSlab                         = 1ull << 1,
    Hopper                           = 1ull << 2,
    TopSnow                          = 1ull << 3,
    FenceGate                        = 1ull << 4,
    Leaves                           = 1ull << 5,
    Connects2D                       = 1ull << 6,
    Carpet                           = 1ull << 7,
    Button                           = 1ull << 8,
    Door                             = 1ull << 9,
    Portal                           = 1ull << 10,
    CanFall                          = 1ull << 11,
    Snow                             = 1ull << 12,
    Trapdoor                         = 1ull << 13,
    Sign                             = 1ull << 14,
    Walkable                         = 1ull << 15,
    PressurePlate                    = 1ull << 16,
    TopSolidBlocking                 = 1ull << 17,
    CubeShaped                       = 1ull << 18,
    Piston                           = 1ull << 19,
    InfiniBurn                       = 1ull << 20,
    RequiresWorldBuilder             = 1ull << 21,
    CausesDamage                     = 1ull << 22,
    BreaksWhenFallenOnByFallingBlock = 1ull << 23,
    Liquid                           = 1ull << 24,
    Scaffolding                      = 1ull << 25,
    CanSupportCenterHangingBlock     = 1ull << 26,
    Unwalkable                       = 1ull << 27,
    Hollow                           = 1ull << 28,
    OperatorBlock                    = 1ull << 29,
    PreventsJumping                  = 1ull << 30,
    ContainsHoney                    = 1ull << 31,
    Slime                            = 1ull << 32,
    Climbable                        = 1ull << 33,
    CanHaltWhenClimbing              = 1ull << 34,
    CanDamperVibrations              = 1ull << 35,
    CanOccludeVibrations             = 1ull << 36,
};
