#pragma once

#include "mc/_HeaderOutputPredefine.h"

enum class BlockProperty : uint64 {
    None                             = 0,
    Stair                            = 0,
    HalfSlab                         = 0,
    Hopper                           = 0,
    TopSnow                          = 0,
    FenceGate                        = 0,
    Leaves                           = 0,
    ThinConnects2D                   = 0,
    Connects2D                       = 0,
    Carpet                           = 0,
    Button                           = 0,
    Door                             = 0,
    Portal                           = 0,
    CanFall                          = 0,
    Snow                             = 0,
    Trap                             = 0,
    Sign                             = 0,
    Walkable                         = 0,
    PressurePlate                    = 0,
    PistonBlockGrabber               = 0,
    TopSolidBlocking                 = 0,
    CubeShaped                       = 0,
    PowerNo                          = 0,
    PowerBlockDown                   = 0,
    Immovable                        = 0,
    BreakOnPush                      = 0,
    Piston                           = 0,
    InfiniBurn                       = 0,
    RequiresWorldBuilder             = 0,
    CausesDamage                     = 0,
    BreaksWhenFallenOnByFallingBlock = 0,
    OnlyPistonPush                   = 0,
    Liquid                           = 0,
    CanBeBuiltOver                   = 0,
    SnowRecoverable                  = 0,
    Scaffolding                      = 0,
    CanSupportCenterHangingBlock     = 0,
    BreaksWhenHitByArrowDeprecated   = 0,
    Unwalkable                       = 0,
    Hollow                           = 0,
    OperatorBlock                    = 0,
    SupportedByFlowerPot             = 0,
    PreventsJumping                  = 0,
    ContainsHoney                    = 0,
    Slime                            = 0,
    SculkReplaceableDeprecated       = 0,
    Climbable                        = 0,
    CanHaltWhenClimbing              = 0,
    CanDamperVibrations              = 0,
    CanOccludeVibrations             = 0,
};
