#pragma once

#include "mc/_HeaderOutputPredefine.h"

enum class PackParseErrorType : int {
    None = 0,
    NoPackAccess = 1,
    UnsupportedFileFormat = 2,
    IncompletePack = 3,
    NoManifest = 4,
    ParseError = 5,
    PuvError = 6,
    MissingProperty = 7,
    MissingPropertyUpgraded = 8,
    WrongTypeProperty = 9,
    EmptyProperty = 10,
    EmptyPropertyUpgraded = 11,
    InvalidProperty = 12,
    MalformedPropertyUUID = 13,
    MalformedPropertyUUIDUpgraded = 14,
    MalformedPropertyVERSION = 15,
    MalformedPropertyVERSIONUpgraded = 16,
    DuplicateUUIDUpgraded = 17,
    DuplicateUUID = 18,
    InvalidPackTypeUpgraded = 19,
    MissingModules = 20,
    MissingDependency = 21,
    MultipleModules = 22,
    MultipleModulesUpgraded = 23,
    UnsupportedFormatVersion = 24,
    PackUpgraded = 25,
    InvalidCapability = 26,
    UnsupportedBaseGameVersionPatch = 27,
    IgnoredProperty = 28,
    VersionTooHigh = 29,
    VersionTooLow = 30,
    MinEngineVersionCapFormatVersion1 = 31,
    FolderStructureTooDeep = 32,
    Count = 33,
};
