#pragma once

enum class BlockActorType {
    Furnace          = 0x1,
    Chest            = 0x2,
    NetherReactor    = 0x3,
    Sign             = 0x4,
    MobSpawner       = 0x5,
    Skull            = 0x6,
    FlowerPot        = 0x7,
    BrewingStand     = 0x8,
    EnchantTable     = 0x9,
    DaylightDetector = 0xa,
    Music            = 0xb,
    Comparator       = 0xc,
    Dispenser        = 0xd,
    Dropper          = 0xe,
    Hopper           = 0xf,
    Cauldron         = 0x10,
    ItemFrame        = 0x11,
    PistonArm        = 0x12,
    MovingBlock      = 0x13,
    ChalkboardBlock  = 0x14,
    Beacon           = 0x15,
    EndPortal        = 0x16,
    EnderChest       = 0x17,
    EndGateway       = 0x18,
    ShulkerBox       = 0x19,
    CommandBlock     = 0x1a,
    Bed              = 0x1b,
    Banner           = 0x1c,
    StructureBlock   = 0x20,
    Jukebox          = 0x21,
    ChemistryTable   = 0x22,
    Conduit          = 0x23,
    JigsawBlock      = 0x24,
    Lectern          = 0x25,
    BlastFurnace     = 0x26,
    Smoker           = 0x27,
    Bell             = 0x28,
    Campfire         = 0x29,
    Barrel           = 0x2a,
    Beehive          = 0x2b,
    Lodestone        = 0x2c,
    SculkSensor      = 0x2d,
    SporeBlossom     = 0x2e,
    GlowItemFrame    = 0x2f
};