#pragma once

#include "mc/_HeaderOutputPredefine.h"

enum class BlockActorRendererId : uchar {
    Default = 0,
    Chest = 1,
    Sign = 2,
    MobSpawner = 3,
    Skull = 4,
    Enchanter = 5,
    PistonArm = 6,
    ItemFrame = 7,
    MovingBlock = 8,
    Chalkboard = 9,
    Beacon = 10,
    EndGateway = 11,
    EnderChest = 12,
    ShulkerBox = 13,
    CommandBlock = 14,
    Bed = 15,
    Banner = 16,
    Conduit = 17,
    Lectern = 18,
    Bell = 19,
    Campfire = 20,
    HangingSign = 21,
    DecoratedPot = 22,
    BrushableBlock = 23,
    TrialSpawner = 24,
    Vault = 25,
    Shelf = 26,
    CopperGolemStatue = 27,
    Count = 28,
};
