#pragma once

#include "mc/_HeaderOutputPredefine.h"

enum class BlockActorType : uchar {
    Undefined             = 0,
    Furnace               = 1,
    Chest                 = 2,
    NetherReactor         = 3,
    Sign                  = 4,
    MobSpawner            = 5,
    Skull                 = 6,
    FlowerPot             = 7,
    BrewingStand          = 8,
    EnchantingTable       = 9,
    DaylightDetector      = 10,
    Music                 = 11,
    Comparator            = 12,
    Dispenser             = 13,
    Dropper               = 14,
    Hopper                = 15,
    Cauldron              = 16,
    ItemFrame             = 17,
    PistonArm             = 18,
    MovingBlock           = 19,
    Chalkboard            = 20,
    Beacon                = 21,
    EndPortal             = 22,
    EnderChest            = 23,
    EndGateway            = 24,
    ShulkerBox            = 25,
    CommandBlock          = 26,
    Bed                   = 27,
    Banner                = 28,
    StructureBlock        = 32,
    Jukebox               = 33,
    ChemistryTable        = 34,
    Conduit               = 35,
    JigsawBlock           = 36,
    Lectern               = 37,
    BlastFurnace          = 38,
    Smoker                = 39,
    Bell                  = 40,
    Campfire              = 41,
    BarrelBlock           = 42,
    Beehive               = 43,
    Lodestone             = 44,
    SculkSensor           = 45,
    SporeBlossom          = 46,
    GlowItemFrame         = 47,
    SculkCatalyst         = 48,
    SculkShrieker         = 49,
    HangingSign           = 50,
    ChiseledBookshelf     = 51,
    BrushableBlock        = 52,
    DecoratedPot          = 53,
    CalibratedSculkSensor = 54,
    Crafter               = 55,
    TrialSpawner          = 56,
    Vault                 = 57,
    CreakingHeart         = 58,
    Shelf                 = 59,
    CopperGolemStatue     = 60,
    Count                 = 61,
};
