// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#include <Global.h>
class CommandPropertyBag {
public:
    virtual ~CommandPropertyBag();

public:
    MCAPI void addToResultList(std::string const&, std::string const&);
    MCAPI void set(std::string const&, class BlockPos const&);
    MCAPI void set(std::string const&, class Vec3);
};