// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#include <Global.h>
namespace CopperUtil {

MCAPI class mce::Color const WAX_OFF_COLOR;
MCAPI class mce::Color const WAX_ON_COLOR;
MCAPI void trySendWaxingTelemetryEventToClient(class Player&, class BlockLegacy const&);

} // namespace CopperUtil