// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#include <Global.h>
class ScriptCommandFactory {

private:
    MCAPI static unsigned int mCurrentId;
    MCAPI static class std::mutex mIdMutex;
};