#pragma once

#include "mc/_HeaderOutputPredefine.h"

enum class NodeId : int {
    None                           = 0,
    Idle                           = 1,
    TakeAll                        = 2,
    TakeHalf                       = 3,
    TakeOne                        = 4,
    PlaceAll                       = 5,
    PlaceOne                       = 6,
    Split                          = 7,
    Coalesce                       = 8,
    DropAll                        = 9,
    DropOne                        = 10,
    AutoPlaceAll                   = 11,
    AutoPlaceOne                   = 12,
    SelectSlot                     = 13,
    UnselectSlot                   = 14,
    ProgressiveTake                = 15,
    ProgressiveSelect              = 16,
    Swap                           = 17,
    TouchProgressiveSelect         = 18,
    TouchProgressiveSelectComplete = 19,
    TouchSplit                     = 20,
    CreativeTakeAll                = 21,
    CreativeTakeOne                = 22,
    CreativeHotbarPlaceAll         = 23,
    CreativeHotbarPlaceOne         = 24,
    SelectRecipe                   = 25,
    DeselectRecipe                 = 26,
    AutoDestroyAll                 = 27,
    DestroyAll                     = 28,
    DestroyOne                     = 29,
    Craft                          = 30,
    CraftAll                       = 31,
    AutoCraftAll                   = 32,
    AutoCraftOne                   = 33,
    ClearHotbar                    = 34,
    SwitchExpando                  = 35,
    AutoPlaceAllHotbar             = 36,
    AutoPlaceOneHotbar             = 37,
    AddAllToCursor                 = 38,
    AddHalfToCursor                = 39,
    PlaceOneWithoutDeselect        = 40,
    UpdateOutputPreview            = 41,
    TouchRepeatCraftOne            = 42,
    TouchRepeatCraftOneComplete    = 43,
    TouchRepeatCraftOneCancel      = 44,
    TouchSlotDeciding              = 45,
    TouchOutputSlotDeciding        = 46,
    TouchRepeatCraft               = 47,
    TouchScrollingPassSlot         = 48,
    BundleActive                   = 49,
    BundleItemTransferIn           = 50,
    BundleItemTransferOut          = 51,
    BundleItemSelected             = 52,
};
