#pragma once

#include "mc/_HeaderOutputPredefine.h"

namespace ui {

enum class GameEventNotification : uint {
    Empty                             = 0,
    PlayerDeath                       = 1,
    PlayerListChanged                 = 2,
    PlayerSignedIn                    = 3,
    PlayerSignedOut                   = 4,
    PlayerDisconnected                = 5,
    NewMessage                        = 6,
    NewConsoleMessage                 = 7,
    ResourcePackConfirmation          = 8,
    ResourcePackDownloadFinished      = 9,
    PlayerExperienceChanged           = 10,
    PlayerArmorChanged                = 11,
    TitleChanged                      = 12,
    TitleCleared                      = 13,
    SubtitleChanged                   = 14,
    ServerSettingsChanged             = 15,
    ActionBarMessageChanged           = 16,
    StoreUpdated                      = 17,
    StoreSalesUpdated                 = 18,
    LanguageChanged                   = 19,
    ScreenPushed                      = 20,
    ScreenPopped                      = 21,
    ScreenSizeChanged                 = 22,
    SavingStart                       = 23,
    SavingFinished                    = 24,
    StructureRendered                 = 25,
    StructureNotRendered              = 26,
    AnimationsEnabledChanged          = 27,
    NewContentLogMessage              = 28,
    ContentMessagesCleared            = 29,
    NewPerfTurtleMessage              = 30,
    IdentityGained                    = 31,
    PersonaSynced                     = 32,
    StructureDataExportSuccess        = 33,
    StructureDataExportFailed         = 34,
    StructureDataImport               = 35,
    StructureDataQuerySuccess         = 36,
    StructureDataQueryFailed          = 37,
    WebviewDismissed                  = 38,
    EntitlementsChanged               = 39,
    PlayerRespawnBlocked              = 40,
    PlayerReadyToRespawn              = 41,
    EduResourceUriModified            = 42,
    OnScreenKeyboardTruncation        = 43,
    RevertToLegacyWorldPackDownloader = 44,
    HudElementVisibilityUpdated       = 45,
};

}
