#pragma once

#include "mc/_HeaderOutputPredefine.h"

namespace Editor::Settings {

enum class ThemeSettingsColorKey : int {
    TitleBarBackground           = 0,
    PanelBackground              = 1,
    HeaderBackground             = 2,
    PanelBorder                  = 3,
    ElementBorder                = 4,
    PrimaryActive                = 5,
    PrimaryAttention             = 6,
    PrimaryDefault               = 7,
    PrimaryMute                  = 8,
    PrimaryDisable               = 9,
    PrimaryBackground1           = 10,
    PrimaryBackground2           = 11,
    PrimaryBackground3           = 12,
    PrimaryBackground4           = 13,
    SecondaryActive              = 14,
    SecondaryAttention           = 15,
    SecondaryDefault             = 16,
    SecondaryMute                = 17,
    SecondaryDisable             = 18,
    SecondaryBackground1         = 19,
    SecondaryBackground2         = 20,
    SecondaryBackground3         = 21,
    DropDown1                    = 22,
    DropDown2                    = 23,
    DropDown3                    = 24,
    ScrollBar                    = 25,
    FocusOutline                 = 26,
    FocusErrorOutline            = 27,
    Warning                      = 28,
    Error                        = 29,
    HotbarOutline                = 30,
    ViewportOutline              = 31,
    DisableBackground            = 32,
    DisableOutline               = 33,
    DisableText                  = 34,
    DisableFill                  = 35,
    Coordinate1                  = 36,
    Coordinate2                  = 37,
    Coordinate3                  = 38,
    ConfirmFill                  = 39,
    Confirm1                     = 40,
    Confirm2                     = 41,
    Confirm3                     = 42,
    DestroyFill                  = 43,
    Destroy1                     = 44,
    Destroy2                     = 45,
    Destroy3                     = 46,
    InfoFill                     = 47,
    Info1                        = 48,
    Info2                        = 49,
    Info3                        = 50,
    Caret                        = 51,
    CursorVolumeBorder           = 52,
    CursorVolumeFill             = 53,
    SelectionVolumeBorder        = 54,
    SelectionVolumeFill          = 55,
    SelectionVolumeOutlineBorder = 56,
    SelectionVolumeOutlineFill   = 57,
    PrefillVolumeBorder          = 58,
    PrefillVolumeFill            = 59,
    PlacementVolumeBorder        = 60,
    PlacementVolumeFill          = 61,
    ControlsGeneralFill          = 62,
    ControlsGeneralHighlight     = 63,
    CoordinateControlX           = 64,
    CoordinateControlY           = 65,
    CoordinateControlZ           = 66,
};

}
