name: "Bug Report 报告Bug"
description: "Report a bug to us to make LiteLoader better. 向我们报告一个Bug以让LiteLoader变得更好"
title: ""
labels: ["bug"]
body:
- type: markdown
  value: |
    Thanks for taking the time to fill out this bug report!
    感谢您花时间填写这份错误报告!
- type: dropdown
  id: module
  attributes:
    label: Exceptions module 异常模块
    description: The module with problems 出现问题的模块
    options:
      - Core 核心
      - ScriptEngine 脚本引擎
      - SymDB2
  validations:
    required: true
- type: dropdown
  id: os
  attributes:
    label: Operating System 操作系统
    multiple: false
    options:
      - Windows Server 2019
      - Windows Server 2016
      - Windows Server 2012
      - Other Windows Server/其他版本的Windows Server
      - Windows 10
      - Windows 11
      - Linux(Ubuntu/CentOS/...) with docker
      - Linux(Ubuntu/CentOS/...) with wine
      - Other 其他
    validations:
      required: true
- type: input
  id: llversion
  attributes:
    label: LiteLoader version  LiteLoader版本
    description: |
      If you are using a beta LiteLoader downloaded from Actions, please type the corresponding Actions run ID (starting with #) or commit hash.
      如果您正在使用一个从Actions下载的beta版LiteLoader，请输入对应的Actions运行ID(#开头)或commit hash
      e.g. 2.1.0     #1479     4f404a72af8a252f0e411f9fe7c846a834a024df     4f404a7
    validations:
      requierd: true
- type: input
  id: bdsversion
  attributes:
    label: BDS version  BDS版本
    value: "1.18.11"
    placeholder: Type your BDS version. 输入您的BDS版本
    validations:
      requierd: true
- type: textarea
  id: what-happened
  attributes:
    label: What happened? Please describe your problem. 发生了什么?请描述你的问题
    description: Also tell us, what did you expect to happen? 并告诉我们,您期待发生什么
    placeholder: Describe your problem clearly. 清晰地描述你的问题
  validations:
    required: true
 - type: textarea
  id: reproduce
  attributes:
    label: Steps to reproduce? 复现此问题的步骤
    description: Describe in as clear and detailed a manner as possible how to reproduce. 尽可能清晰且详细的描述如何复现
    value: |
      1. Do something
      2. ...
      3. 
- type: textarea
  id: logs
  attributes:
    label: Relevant log output 有关的日志/输出
    description: Please copy and paste any relevant log output. 请粘贴有关此问题的日志到此处
    render: shell
- type: markdown
  value: |
    **If you have pictures or other content, please comment below. Screenshots,logs and dmp files are very important and helpful for solving your problem**
    **如果你有图片或其他内容，请在下面评论(comment)。截图，日志和dmp文件对解决你的问题很重要、很有帮助**
    ******
    Thank you again for your contribution to LiteLoader!
    再次感谢您对LiteLoader的贡献!
