#pragma once

#include "mc/_HeaderOutputPredefine.h"

// auto generated inclusion list
#include "mc/common/wrapper/Exclude.h"
#include "mc/common/wrapper/Include.h"
#include "mc/common/wrapper/ViewT.h"
#include "mc/world/components/FlagComponent.h"

namespace ActorNormalTick {
// NOLINTBEGIN
// symbol:
// ?_tickEach@ActorNormalTick@@YAX_NAEBV?$ViewT@VStrictEntityContext@@U?$Include@V?$FlagComponent@UActorMovementTickNeededFlag@@@@@@U?$Exclude@V?$FlagComponent@UActorRemovedFlag@@@@@@VActorOwnerComponent@@@@AEBV?$ViewT@VStrictEntityContext@@U?$Include@V?$FlagComponent@UBeeFlag@@@@@@@@AEBV?$ViewT@VStrictEntityContext@@U?$Include@V?$FlagComponent@UBatFlag@@@@@@@@AEBV?$ViewT@VStrictEntityContext@@U?$Include@V?$FlagComponent@UExperienceOrbFlag@@@@@@@@AEBV?$ViewT@VStrictEntityContext@@U?$Include@V?$FlagComponent@UFireworksRocketFlag@@@@@@@@AEBV?$ViewT@VStrictEntityContext@@U?$Include@V?$FlagComponent@UFishingHookFlag@@@@@@@@AEBV?$ViewT@VStrictEntityContext@@U?$Include@V?$FlagComponent@UHorseFlag@@@@@@@@AEBV?$ViewT@VStrictEntityContext@@U?$Include@V?$FlagComponent@UItemActorFlag@@@@@@@@AEBV?$ViewT@VStrictEntityContext@@U?$Include@V?$FlagComponent@UMinecartFlag@@@@@@@@AEBV?$ViewT@VStrictEntityContext@@U?$Include@V?$FlagComponent@UPandaFlag@@@@@@@@AEBV?$ViewT@VStrictEntityContext@@U?$Include@V?$FlagComponent@UPrimedTntFlag@@@@@@@@AEBV?$ViewT@VStrictEntityContext@@U?$Include@V?$FlagComponent@USlimeFlag@@@@@@@@AEBV?$ViewT@VStrictEntityContext@@U?$Include@V?$FlagComponent@UWolfFlag@@@@@@@@AEBV?$ViewT@VStrictEntityContext@@U?$Include@V?$FlagComponent@UShulkerFlag@@@@@@@@AEBV?$ViewT@VStrictEntityContext@@$$CBUMinecartPreNormalTickBlockPosComponent@@@@AEBV?$ViewT@VStrictEntityContext@@U?$Include@V?$FlagComponent@USlimeWasOnGroundPreNormalTick@@@@@@@@@Z
MCAPI void _tickEach(bool, class ViewT<class StrictEntityContext, struct Include<class FlagComponent<struct ActorMovementTickNeededFlag>>, struct Exclude<class FlagComponent<struct ActorRemovedFlag>>, class ActorOwnerComponent> const&, class ViewT<class StrictEntityContext, struct Include<class FlagComponent<struct BeeFlag>>> const&, class ViewT<class StrictEntityContext, struct Include<class FlagComponent<struct BatFlag>>> const&, class ViewT<class StrictEntityContext, struct Include<class FlagComponent<struct ExperienceOrbFlag>>> const&, class ViewT<class StrictEntityContext, struct Include<class FlagComponent<struct FireworksRocketFlag>>> const&, class ViewT<class StrictEntityContext, struct Include<class FlagComponent<struct FishingHookFlag>>> const&, class ViewT<class StrictEntityContext, struct Include<class FlagComponent<struct HorseFlag>>> const&, class ViewT<class StrictEntityContext, struct Include<class FlagComponent<struct ItemActorFlag>>> const&, class ViewT<class StrictEntityContext, struct Include<class FlagComponent<struct MinecartFlag>>> const&, class ViewT<class StrictEntityContext, struct Include<class FlagComponent<struct PandaFlag>>> const&, class ViewT<class StrictEntityContext, struct Include<class FlagComponent<struct PrimedTntFlag>>> const&, class ViewT<class StrictEntityContext, struct Include<class FlagComponent<struct SlimeFlag>>> const&, class ViewT<class StrictEntityContext, struct Include<class FlagComponent<struct WolfFlag>>> const&, class ViewT<class StrictEntityContext, struct Include<class FlagComponent<struct ShulkerFlag>>> const&, class ViewT<class StrictEntityContext, struct MinecartPreNormalTickBlockPosComponent const> const&, class ViewT<class StrictEntityContext, struct Include<class FlagComponent<struct SlimeWasOnGroundPreNormalTick>>> const&);
// NOLINTEND

}; // namespace ActorNormalTick
