/**
 * @file  DynamicJumpControl.hpp
 * @note  This Header is auto generated by LiteLoaderBDS Toolchain.
 *
 */
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA
// Include Headers or Declare Types Here

#undef BEFORE_EXTRA

/**
 * @brief MC class DynamicJumpControl.
 *
 */
class DynamicJumpControl {

#define AFTER_EXTRA
// Add Member There

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_DYNAMICJUMPCONTROL
public:
    class DynamicJumpControl& operator=(class DynamicJumpControl const &) = delete;
    DynamicJumpControl(class DynamicJumpControl const &) = delete;
#endif

public:
    /**
     * @vftbl  0
     * @hash   1664015194
     */
    virtual ~DynamicJumpControl();
    /**
     * @vftbl  1
     * @symbol ?initializeInternal@DynamicJumpControl@@UEAAXAEAVMob@@PEAUJumpControlDescription@@@Z
     * @hash   -689670632
     */
    virtual void initializeInternal(class Mob &, struct JumpControlDescription *);
    /**
     * @vftbl  2
     * @symbol ?clone@DynamicJumpControl@@UEBA?AV?$unique_ptr@VJumpControl@@U?$default_delete@VJumpControl@@@std@@@std@@XZ
     * @hash   689653542
     */
    virtual std::unique_ptr<class JumpControl> clone() const;
    /**
     * @vftbl  3
     * @symbol ?tick@DynamicJumpControl@@MEAAXAEAVJumpControlComponent@@AEAVMob@@@Z
     * @hash   1139287043
     */
    virtual void tick(class JumpControlComponent &, class Mob &);
    /**
     * @vftbl  4
     * @symbol ?getJumpDelay@DynamicJumpControl@@MEBAHAEBVJumpControlComponent@@@Z
     * @hash   -2145233362
     */
    virtual int getJumpDelay(class JumpControlComponent const &) const;
    /**
     * @vftbl  5
     * @symbol ?getJumpPower@DynamicJumpControl@@MEBAMAEBVJumpControlComponent@@@Z
     * @hash   -2126102951
     */
    virtual float getJumpPower(class JumpControlComponent const &) const;
    /**
     * @vftbl  6
     * @symbol ?getJumpType@DynamicJumpControl@@MEBA?AW4JumpType@@AEBVJumpControlComponent@@@Z
     * @hash   666799042
     */
    virtual enum class JumpType getJumpType(class JumpControlComponent const &) const;
    /**
     * @vftbl  7
     * @symbol ?setJumpType@DynamicJumpControl@@MEAAXAEAVJumpControlComponent@@W4JumpType@@@Z
     * @hash   -2061732352
     */
    virtual void setJumpType(class JumpControlComponent &, enum class JumpType);
    /**
     * @vftbl  8
     * @symbol ?resetSpeedModifier@DynamicJumpControl@@MEAAXAEBVJumpControlComponent@@AEAVMob@@@Z
     * @hash   118780232
     */
    virtual void resetSpeedModifier(class JumpControlComponent const &, class Mob &);
    /**
     * @symbol ??0DynamicJumpControl@@QEAA@XZ
     * @hash   1429088060
     */
    MCAPI DynamicJumpControl();

};