/**
 * @file  FlyDefinition.hpp
 * @note  This Header is auto generated by LiteLoaderBDS Toolchain.
 *
 */
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "Json.hpp"
#include "BehaviorDefinition.hpp"

#define BEFORE_EXTRA
// Include Headers or Declare Types Here

#undef BEFORE_EXTRA

/**
 * @brief MC class FlyDefinition.
 *
 */
class FlyDefinition : public BehaviorDefinition {

#define AFTER_EXTRA
// Add Member There

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_FLYDEFINITION
public:
    class FlyDefinition& operator=(class FlyDefinition const &) = delete;
    FlyDefinition(class FlyDefinition const &) = delete;
    FlyDefinition() = delete;
#endif

public:
    /**
     * @vftbl  0
     * @hash   -1785370636
     */
    virtual ~FlyDefinition();
    /**
     * @vftbl  1
     * @symbol ?load@FlyDefinition@@UEAAXVValue@Json@@AEBVBehaviorFactory@@@Z
     * @hash   -509456850
     */
    virtual void load(class Json::Value, class BehaviorFactory const &);

};