// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "JsonUtil.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class AddRiderDefinition {

#define AFTER_EXTRA

#undef AFTER_EXTRA

#ifndef DISABLE_CONSTRUCTOR_PREVENTION_ADDRIDERDEFINITION
public:
    class AddRiderDefinition& operator=(class AddRiderDefinition const &) = delete;
    AddRiderDefinition(class AddRiderDefinition const &) = delete;
    AddRiderDefinition() = delete;
#endif

public:
    MCAPI void initialize(class EntityContext &, class AddRiderComponent &);
    MCAPI static void buildSchema(class std::shared_ptr<class JsonUtil::JsonSchemaObjectNode<class JsonUtil::EmptyClass, class AddRiderDefinition>> &);

protected:

private:

};