// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#include <Global.h>
#include "Json.hpp"
#include "MobEffectSubcomponent.hpp"
#define EXTRA_INCLUDE_PART_ARROWEFFECTSUBCOMPONENT
#include "Extra/ArrowEffectSubcomponentAPI.hpp"
#undef EXTRA_INCLUDE_PART_ARROWEFFECTSUBCOMPONENT
class ArrowEffectSubcomponent : public MobEffectSubcomponent {
#include "Extra/ArrowEffectSubcomponentAPI.hpp"
public:
    virtual ~ArrowEffectSubcomponent();
    virtual void writetoJSON(class Json::Value&) const;
    virtual void doOnHitEffect(class Actor&, class ProjectileComponent&);
    virtual char const* getName();
};