// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#include "../Global.h"
#define EXTRA_INCLUDE_PART_ATLASITEMMANAGER
#include "Extra/AtlasItemManagerAPI.hpp"
#undef EXTRA_INCLUDE_PART_ATLASITEMMANAGER
class AtlasItemManager {
#include "Extra/AtlasItemManagerAPI.hpp"
public:
    MCAPI class TextureAtlasItem const& getTextureItem(std::string const&) const;

protected:

private:
};