// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#include "../Global.h"
#define EXTRA_INCLUDE_PART_BRIBEABLECOMPONENT
#include "Extra/BribeableComponentAPI.hpp"
#undef EXTRA_INCLUDE_PART_BRIBEABLECOMPONENT
class BribeableComponent {
#include "Extra/BribeableComponentAPI.hpp"
public:
    MCAPI void addAdditionalSaveData(class CompoundTag&);
    MCAPI bool clientBribeCheck(class Actor&);
    MCAPI int& getBribeCooldown();
    MCAPI int& getBribeTimer();
    MCAPI bool getInteraction(class Actor&, class Player&, class ActorInteraction&);
    MCAPI void readAdditionalSaveData(class Actor&, class CompoundTag const&, class DataLoadHelper&);
    MCAPI void resetBribe(class Actor&);

protected:

private:
};