// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#include <Global.h>
#define EXTRA_INCLUDE_PART_CLASSSCRIPTACTORCOMPONENT
#include "Extra/class ScriptActorComponentAPI.hpp"
#undef EXTRA_INCLUDE_PART_CLASSSCRIPTACTORCOMPONENT
namespace class ScriptActorComponent {
#include "Extra/class ScriptActorComponentAPI.hpp"

	MCAPI   `RTTI Type Descriptor';






}