// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#include "../Global.h"
#include "BaseCircuitComponent.hpp"
#define EXTRA_INCLUDE_PART_CONSUMERCOMPONENT
#include "Extra/ConsumerComponentAPI.hpp"
#undef EXTRA_INCLUDE_PART_CONSUMERCOMPONENT
class ConsumerComponent : public BaseCircuitComponent {
#include "Extra/ConsumerComponentAPI.hpp"
public:
    /*0*/ virtual ~ConsumerComponent();
    /*1*/ virtual int getStrength() const;
    /*2*/ virtual int getDirection() const;
    /*3*/ virtual void setStrength(int);
    /*4*/ virtual void setDirection(unsigned char);
    /*5*/ virtual void __unk_vfn_0();
    /*6*/ virtual bool canStopPower() const;
    /*7*/ virtual void setStopPower(bool);
    /*8*/ virtual bool addSource(class CircuitSceneGraph&, class CircuitTrackingInfo const&, int&, bool&);
    /*9*/ virtual bool allowConnection(class CircuitSceneGraph&, class CircuitTrackingInfo const&, bool&);
    /*10*/ virtual void checkLock(class CircuitSystem&, class BlockPos const&);
    /*11*/ virtual bool evaluate(class CircuitSystem&, class BlockPos const&);
    /*12*/ virtual void cacheValues(class CircuitSystem&, class BlockPos const&);
    /*13*/ virtual void updateDependencies(class CircuitSceneGraph&, class BlockPos const&);
    /*14*/ virtual void __unk_vfn_1();
    /*15*/ virtual bool isHalfPulse() const;
    /*16*/ virtual void __unk_vfn_2();
    /*17*/ virtual bool isSecondaryPowered() const;
    /*18*/ virtual int /*enum enum CircuitComponentType*/ getCircuitComponentType() const;
    /*
    inline bool canConsumerPower() const{
        bool (ConsumerComponent::*rv)() const;
        *((void**)&rv) = dlsym("?canConsumerPower@ConsumerComponent@@UEBA_NXZ");
        return (this->*rv)();
    }
    */

protected:

private:
};