// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#include <Global.h>
#define EXTRA_INCLUDE_PART
#include "Extra/DefaultLookAngleDefinitionAPI.hpp"
#undef EXTRA_INCLUDE_PART
namespace DefaultLookAngleDefinition {
#include "Extra/DefaultLookAngleDefinitionAPI.hpp"

public:
MCAPI static void buildSchema(class std::shared_ptr<class JsonUtil::JsonSchemaObjectNode<class JsonUtil::EmptyClass, struct DefaultLookAngleDefinition>>&);


} // namespace DefaultLookAngleDefinition