// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#include <Global.h>
#define EXTRA_INCLUDE_PART_ERRORPATHSTACK
#include "Extra/ErrorPathStackAPI.hpp"
#undef EXTRA_INCLUDE_PART_ERRORPATHSTACK
class ErrorPathStack {
#include "Extra/ErrorPathStackAPI.hpp"

public:
    MCAPI ~ErrorPathStack();
};