/**
 * @file  ExpiringTick.hpp
 * @note  This Header is auto generated by LiteLoaderBDS Toolchain.
 *
 */
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

/**
 * @brief MC class ExpiringTick.
 *
 */
class ExpiringTick {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_EXPIRINGTICK
public:
    class ExpiringTick& operator=(class ExpiringTick const &) = delete;
    ExpiringTick(class ExpiringTick const &) = delete;
    ExpiringTick() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_EXPIRINGTICK
#endif
    /**
     * @symbol ??0ExpiringTick@@QEAA@UTick@@G@Z
     */
    MCAPI ExpiringTick(struct Tick, unsigned short);
    /**
     * @symbol ?getExpireAtTick@ExpiringTick@@QEBA?AUTick@@XZ
     */
    MCAPI struct Tick getExpireAtTick() const;
    /**
     * @symbol ?isActive@ExpiringTick@@QEBA_NUTick@@@Z
     */
    MCAPI bool isActive(struct Tick) const;
    /**
     * @symbol ?isExpired@ExpiringTick@@QEBA_NUTick@@@Z
     */
    MCAPI bool isExpired(struct Tick) const;

};