// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#include <Global.h>
#include "FilterTest.hpp"
#include "Json.hpp"
#define EXTRA_INCLUDE_PART_FILTERTESTGAMERULE
#include "Extra/FilterTestGameRuleAPI.hpp"
#undef EXTRA_INCLUDE_PART_FILTERTESTGAMERULE
class FilterTestGameRule : public FilterTest {
#include "Extra/FilterTestGameRuleAPI.hpp"
public:
    virtual ~FilterTestGameRule();
    virtual bool setup(struct FilterTest::Definition const&, struct FilterInputs const&);
    virtual bool evaluate(struct FilterContext const&) const;
    virtual void finalizeParsedValue(class IWorldRegistriesProvider&);
    virtual class gsl::basic_string_span<char const, -1> getName() const;
    virtual class Json::Value _serializeValue() const;
};