/**
 * @file  GoatHornItem.hpp
 * @note  This Header is auto generated by LiteLoaderBDS Toolchain.
 *
 */
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "Json.hpp"
#include "Item.hpp"

#define BEFORE_EXTRA
// Include Headers or Declare Types Here

#undef BEFORE_EXTRA

/**
 * @brief MC class GoatHornItem.
 *
 */
class GoatHornItem : public Item {

#define AFTER_EXTRA
// Add Member There

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_GOATHORNITEM
public:
    class GoatHornItem& operator=(class GoatHornItem const &) = delete;
    GoatHornItem(class GoatHornItem const &) = delete;
    GoatHornItem() = delete;
#endif

public:
    virtual ~GoatHornItem();
    virtual void __unk_vfn_7();
    virtual void __unk_vfn_11();
    virtual void __unk_vfn_14();
    virtual void __unk_vfn_16();
    virtual void __unk_vfn_52();
    virtual void __unk_vfn_54();
    virtual void appendFormattedHovertext(class ItemStackBase const &, class Level &, std::string &, bool) const;
    virtual void __unk_vfn_67();
    virtual void __unk_vfn_71();
    virtual void __unk_vfn_72();
    virtual void __unk_vfn_73();
    virtual void __unk_vfn_76();
    virtual void __unk_vfn_80();
    virtual void __unk_vfn_81();
    virtual class ItemStack & use(class ItemStack &, class Player &) const;
    virtual class HashedString const & getCooldownType() const;
    virtual int getCooldownTime() const;
    virtual bool canBeCharged() const;
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_GOATHORNITEM
#endif
    MCAPI GoatHornItem(std::string const &, int);
    MCAPI static void addGoatHornVarationSaveData(class Goat &, class ItemStack &);

};