/**
 * @file  ImitateMobSoundsComponent.hpp
 * @note  This Header is auto generated by LiteLoaderBDS Toolchain.
 *
 */
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA
// Include Headers or Declare Types Here

#undef BEFORE_EXTRA

/**
 * @brief MC class ImitateMobSoundsComponent.
 *
 */
class ImitateMobSoundsComponent {

#define AFTER_EXTRA
// Add Member There

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_IMITATEMOBSOUNDSCOMPONENT
public:
    class ImitateMobSoundsComponent& operator=(class ImitateMobSoundsComponent const &) = delete;
    ImitateMobSoundsComponent(class ImitateMobSoundsComponent const &) = delete;
    ImitateMobSoundsComponent() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_IMITATEMOBSOUNDSCOMPONENT
#endif
    MCAPI static enum LevelSoundEvent getRandomImitatedSound(class Randomize const &);
    MCAPI static bool imitateNearbyMobs(class Actor &, class Randomize const &);

//private:

private:
MCAPI static class std::unordered_map<enum ActorType, enum LevelSoundEvent, struct std::hash<enum ActorType>, struct std::equal_to<enum ActorType>, class std::allocator<struct std::pair<enum ActorType const, enum LevelSoundEvent>>> const imitateMobMap;

};