// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class InsideWebBlockSystem {

#define AFTER_EXTRA

#undef AFTER_EXTRA

#ifndef DISABLE_CONSTRUCTOR_PREVENTION_INSIDEWEBBLOCKSYSTEM
public:
    class InsideWebBlockSystem& operator=(class InsideWebBlockSystem const &) = delete;
    InsideWebBlockSystem(class InsideWebBlockSystem const &) = delete;
    InsideWebBlockSystem() = delete;
#endif

public:
    MCAPI static class Vec3 const SLOWDOWN_MULTIPLIER;

protected:

private:

};