// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#include <Global.h>
#define EXTRA_INCLUDE_PART_INSTANTDESPAWNSYSTEM
#include "Extra/InstantDespawnSystemAPI.hpp"
#undef EXTRA_INCLUDE_PART_INSTANTDESPAWNSYSTEM
class InstantDespawnSystem {
#include "Extra/InstantDespawnSystemAPI.hpp"
public:
    virtual ~InstantDespawnSystem();
    virtual void unk_vfn_1();
    virtual void tick(class EntityRegistry&);
};