// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#include <Global.h>
#include "Packet.hpp"
#define EXTRA_INCLUDE_PART
#include "Extra/InventoryTransactionPacketAPI.hpp"
#undef EXTRA_INCLUDE_PART
class InventoryTransactionPacket : public Packet {
#include "Extra/InventoryTransactionPacketAPI.hpp"
public:
    virtual ~InventoryTransactionPacket();
    virtual int /*enum MinecraftPacketIds*/ getId();
    virtual std::string getName();
    virtual void write(class BinaryStream&);
    virtual void unk_vfn_5();
    virtual int /*enum StreamReadResult*/ _read(class ReadOnlyBinaryStream&);

public:
    MCAPI InventoryTransactionPacket();
    MCAPI InventoryTransactionPacket(std::unique_ptr<class ComplexInventoryTransaction>, bool);
    MCAPI void postLoadItems(class BlockPalette&, bool) const;
};