// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#include <Global.h>
class IPacketHandlerDispatcher {
public:
    virtual ~IPacketHandlerDispatcher();
    virtual void unk_vfn_1();
};