// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#include "../Global.h"
#include "Feature.hpp"
#define EXTRA_INCLUDE_PART_LAKEFEATURE
#include "Extra/LakeFeatureAPI.hpp"
#undef EXTRA_INCLUDE_PART_LAKEFEATURE
class LakeFeature : public Feature {
#include "Extra/LakeFeatureAPI.hpp"
public:
    /*0*/ virtual ~LakeFeature();
    /*1*/ virtual void __unk_vfn_0();
    /*2*/ virtual bool place(class BlockSource&, class BlockPos const&, class Random&) const;


protected:

private:
    MCAPI bool _check(class BlockPos const&, class gsl::span<bool, 2048>) const;
};