// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#include <Global.h>
#define EXTRA_INCLUDE_PART_LOOMCONTAINERSCREENVALIDATOR
#include "Extra/LoomContainerScreenValidatorAPI.hpp"
#undef EXTRA_INCLUDE_PART_LOOMCONTAINERSCREENVALIDATOR
class LoomContainerScreenValidator {
#include "Extra/LoomContainerScreenValidatorAPI.hpp"
public:
    virtual ~LoomContainerScreenValidator();
};