/**
 * @file  MoveOutdoorsGoal.hpp
 * @note  This Header is auto generated by LiteLoaderBDS Toolchain.
 *
 */
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "BaseMoveToBlockGoal.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

/**
 * @brief MC class MoveOutdoorsGoal.
 *
 */
class MoveOutdoorsGoal : public BaseMoveToBlockGoal {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_MOVEOUTDOORSGOAL
public:
    class MoveOutdoorsGoal& operator=(class MoveOutdoorsGoal const &) = delete;
    MoveOutdoorsGoal(class MoveOutdoorsGoal const &) = delete;
    MoveOutdoorsGoal() = delete;
#endif

public:
    virtual ~MoveOutdoorsGoal();
    virtual bool canUse();
    virtual void __unk_vfn_3();
    virtual void start();
    virtual void tick();
    virtual void appendDebugInfo(std::string &) const;
    virtual void __unk_vfn_8();
    virtual void __unk_vfn_9();
    virtual bool isValidTarget(class BlockSource &, class BlockPos const &);
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_MOVEOUTDOORSGOAL
#endif
    MCAPI MoveOutdoorsGoal(class Mob &);

//private:
    MCAPI void _setNextTargetTick();

private:

};