// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#include "../Global.h"
#include "Json.hpp"
#define EXTRA_INCLUDE_PART_NAVIGATIONHOVERDESCRIPTION
#include "Extra/NavigationHoverDescriptionAPI.hpp"
#undef EXTRA_INCLUDE_PART_NAVIGATIONHOVERDESCRIPTION
class NavigationHoverDescription {
#include "Extra/NavigationHoverDescriptionAPI.hpp"
public:
    /*0*/ virtual char const* getJsonName() const;
    /*1*/ virtual ~NavigationHoverDescription();
    /*
    inline char const* getJsonName() const{
        char const* (NavigationHoverDescription::*rv)() const;
        *((void**)&rv) = dlsym("?getJsonName@NavigationHoverDescription@@UEBAPEBDXZ");
        return (this->*rv)();
    }
    */

protected:

private:
};