// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#include <Global.h>
#define EXTRA_INCLUDE_PART
#include "Extra/NetherNetInstanceAPI.hpp"
#undef EXTRA_INCLUDE_PART
class NetherNetInstance {
#include "Extra/NetherNetInstanceAPI.hpp"

public:
    MCAPI NetherNetInstance();
};