// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

struct OnPlayerPlacingTrigger {

#define AFTER_EXTRA

#undef AFTER_EXTRA

#ifndef DISABLE_CONSTRUCTOR_PREVENTION_ONPLAYERPLACINGTRIGGER
public:
    struct OnPlayerPlacingTrigger& operator=(struct OnPlayerPlacingTrigger const&) = delete;
    OnPlayerPlacingTrigger(struct OnPlayerPlacingTrigger const&) = delete;
    OnPlayerPlacingTrigger() = delete;
#endif

public:
    MCAPI ~OnPlayerPlacingTrigger();

protected:

private:

};