// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#include <Global.h>
#include "JsonUtil.hpp"
#define EXTRA_INCLUDE_PART_ONTARGETESCAPEDEFINITION
#include "Extra/OnTargetEscapeDefinitionAPI.hpp"
#undef EXTRA_INCLUDE_PART_ONTARGETESCAPEDEFINITION
struct OnTargetEscapeDefinition {
#include "Extra/OnTargetEscapeDefinitionAPI.hpp"

public:
    MCAPI static void buildSchema(class std::shared_ptr<class JsonUtil::JsonSchemaObjectNode<class JsonUtil::EmptyClass, struct OnTargetEscapeDefinition>>&);
};