/**
 * @file  OptionalString.hpp
 * @note  This Header is auto generated by LiteLoaderBDS Toolchain.
 *
 */
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

/**
 * @brief MC structure OptionalString.
 *
 */
struct OptionalString {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_OPTIONALSTRING
public:
    struct OptionalString& operator=(struct OptionalString const &) = delete;
    OptionalString(struct OptionalString const &) = delete;
    OptionalString() = delete;
#endif
public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_OPTIONALSTRING
#endif
    /**
     * @symbol ??1OptionalString@@QEAA@XZ
     */
    MCAPI ~OptionalString();

};