// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#include "../Global.h"
#include "ChunkLocalNoiseCache.hpp"
#define EXTRA_INCLUDE_PART_OVERWORLDNOISES3D
#include "Extra/OverworldNoises3dAPI.hpp"
#undef EXTRA_INCLUDE_PART_OVERWORLDNOISES3D
struct OverworldNoises3d {
#include "Extra/OverworldNoises3dAPI.hpp"
public:
    MCAPI struct ChunkLocalNoiseCache::CacheEntry computeNoiseValues(class DividedPos2d<4> const&) const;
    MCAPI struct std::pair<float, float> computeOffsetAndFactor(class DividedPos2d<4> const&) const;
    MCAPI struct TargetPoint sample(int, struct ChunkLocalNoiseCache::CacheEntry const&) const;
    MCAPI struct TargetPoint sample(class BlockPos) const;
    MCAPI static float computeInitialDensity(int, float, float, float);

protected:

private:
    MCAPI struct ChunkLocalNoiseCache::CacheEntry _computeBaseValueSetForCacheEntry(class DividedPos2d<4> const&) const;
};