// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class PersonaPiece {

#define AFTER_EXTRA

#undef AFTER_EXTRA

#ifndef DISABLE_CONSTRUCTOR_PREVENTION_PERSONAPIECE
public:
    class PersonaPiece& operator=(class PersonaPiece const &) = delete;
    PersonaPiece(class PersonaPiece const &) = delete;
#endif


public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_PERSONAPIECE
#endif
    MCAPI PersonaPiece();
    MCAPI ~PersonaPiece();
    MCAPI static class PersonaPiece const INVALID_PIECE;



};