// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

struct PlayerDropItemEvent {

#define AFTER_EXTRA

#undef AFTER_EXTRA

#ifndef DISABLE_CONSTRUCTOR_PREVENTION_PLAYERDROPITEMEVENT
public:
    struct PlayerDropItemEvent& operator=(struct PlayerDropItemEvent const&) = delete;
    PlayerDropItemEvent(struct PlayerDropItemEvent const&) = delete;
    PlayerDropItemEvent() = delete;
#endif

public:
    MCAPI ~PlayerDropItemEvent();

protected:

private:

};