// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#include <Global.h>
#define EXTRA_INCLUDE_PART_PLAYERSCOREBOARDID
#include "Extra/PlayerScoreboardIdAPI.hpp"
#undef EXTRA_INCLUDE_PART_PLAYERSCOREBOARDID
class PlayerScoreboardId {
#include "Extra/PlayerScoreboardIdAPI.hpp"

public:
    MCAPI PlayerScoreboardId();
    MCAPI PlayerScoreboardId(__int64);

    MCAPI static struct PlayerScoreboardId const INVALID;
};