// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#include <Global.h>
class PlayerActionComponent {

public:
    MCAPI void addAbortDestroyBlock(class BlockPos const&, int);
    MCAPI void addContinueDestroyBlock(class BlockPos const&, int);
    MCAPI void addStartDestroyBlock(class BlockPos const&, int);
    MCAPI void addStopDestroyBlock();
};