// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#include <Global.h>
#define EXTRA_INCLUDE_PART
#include "Extra/PosibleTransformationAPI.hpp"
#undef EXTRA_INCLUDE_PART
class PosibleTransformation {
#include "Extra/PosibleTransformationAPI.hpp"

public:
    MCAPI PosibleTransformation(struct PosibleTransformation const&);
    MCAPI ~PosibleTransformation();
};