// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"


#define BEFORE_EXTRA //DO NOT EDIT THIS LINE
// Include Headers or Declare Types Here

#undef BEFORE_EXTRA //DO NOT EDIT THIS LINE

class PushableComponent {

#define AFTER_EXTRA //DO NOT EDIT THIS LINE
// Add Member There

#undef AFTER_EXTRA //DO NOT EDIT THIS LINE

public:

    MCAPI PushableComponent();
    MCAPI void initFromDefinition(class Actor&);
    MCAPI void initFromDefinition(class Actor&, struct PushableDescription&);
    MCAPI bool isPushable();
    MCAPI bool isPushableByPiston();
    MCAPI void push(class Actor&, class Actor&, bool);
    MCAPI void push(class Actor&, class Vec3 const&);

protected:


private:

    MCAPI struct std::pair<class Vec3, class Vec3> _calculatePushVectorMinecart(class Actor&, class Actor&, bool);
};