// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#include <Global.h>
#include "BaseMoveToBlockGoal.hpp"
#define EXTRA_INCLUDE_PART_RAIDGARDENGOAL
#include "Extra/RaidGardenGoalAPI.hpp"
#undef EXTRA_INCLUDE_PART_RAIDGARDENGOAL
class RaidGardenGoal : public BaseMoveToBlockGoal {
#include "Extra/RaidGardenGoalAPI.hpp"
public:
    /*0*/ virtual ~RaidGardenGoal();
    /*1*/ virtual bool canUse();
    /*2*/ virtual bool canContinueToUse();
    /*3*/ virtual void unk_vfn_3();
    /*4*/ virtual void start();
    /*6*/ virtual void tick();
    /*7*/ virtual void appendDebugInfo(std::string&) const;
    /*8*/ virtual void unk_vfn_8();
    /*9*/ virtual void unk_vfn_9();
    /*11*/ virtual bool isValidTarget(class BlockSource&, class BlockPos const&);
    /*16*/ virtual unsigned __int64 _getRepathTime() const;
};