// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#include <Global.h>
#define EXTRA_INCLUDE_PART
#include "Extra/ResourceHelperAPI.hpp"
#undef EXTRA_INCLUDE_PART
namespace ResourceHelper {
#include "Extra/ResourceHelperAPI.hpp"

MCAPI bool deserializePackStackEntry(class Json::Value const&, struct PackInstanceId&, std::string const&);
MCAPI std::string stringifyResourceMetadataGeneratedWith(class ResourceMetadata const&);


} // namespace ResourceHelper