// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "Json.hpp"

#define BEFORE_EXTRA
// Include Headers or Declare Types Here

#undef BEFORE_EXTRA

namespace ResourceHelper {

#define AFTER_EXTRA
// Add Member There

#undef AFTER_EXTRA
    MCAPI bool deserializePackStackEntry(class Json::Value const&, struct PackInstanceId&, std::string const&);
    MCAPI std::string stringifyResourceMetadataGeneratedWith(class ResourceMetadata const&);

};