// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA
// Include Headers or Declare Types Here

#undef BEFORE_EXTRA

class ScriptEventCoordinator {

#define AFTER_EXTRA
// Add Member There

#undef AFTER_EXTRA

#ifndef DISABLE_CONSTRUCTOR_PREVENTION_SCRIPTEVENTCOORDINATOR
public:
    class ScriptEventCoordinator& operator=(class ScriptEventCoordinator const&) = delete;
    ScriptEventCoordinator(class ScriptEventCoordinator const&) = delete;
    ScriptEventCoordinator() = delete;
#endif

public:
    /*0*/ virtual ~ScriptEventCoordinator();
    MCAPI void sendScriptAddFilterToView(std::string const&);
    MCAPI void sendScriptBroadcastEvent(std::string const&, enum RegistrationType, bool);
    MCAPI void sendScriptError(std::string const&, std::string const&);
    MCAPI void sendScriptGetComponent(std::string const&, enum RegistrationType, bool);
    MCAPI void sendScriptInternalError(std::string const&);
    MCAPI void sendScriptListenForEvent(std::string const&);
    MCAPI void sendScriptLoaded(std::string const&, unsigned __int64);
    MCAPI void sendScriptRan(std::string const&, std::string const&, bool);
    MCAPI void sendScriptRegisterSpatialView(std::string const&);
    MCAPI void sendScriptRegisterView();

protected:

private:

};