// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#include "Scripting.hpp"

#define BEFORE_EXTRA //DO NOT EDIT THIS LINE
// Include Headers or Declare Types Here

#undef BEFORE_EXTRA //DO NOT EDIT THIS LINE

class ScriptObject {

#define AFTER_EXTRA //DO NOT EDIT THIS LINE
// Add Member There

#undef AFTER_EXTRA //DO NOT EDIT THIS LINE

public:
    /*0*/ virtual ~ScriptObject();
    /*1*/ virtual struct Scripting::Error _functionError(std::string const&) const;
    /*2*/ virtual struct Scripting::Error _getPropertyError(std::string const&) const;
    /*3*/ virtual struct Scripting::Error _setPropertyError(std::string const&) const;


    MCAPI ScriptObject(class Scripting::WeakLifetimeScope const&);

protected:


private:

};