// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#include <Global.h>
#define EXTRA_INCLUDE_PART_SCRIPTFEEDITEM
#include "Extra/ScriptFeedItemAPI.hpp"
#undef EXTRA_INCLUDE_PART_SCRIPTFEEDITEM
namespace ScriptFeedItem {
#include "Extra/ScriptFeedItemAPI.hpp"

public:
MCAPI static class Scripting::ClassBindingBuilder<struct FeedItem> bind(struct Scripting::Version);


} // namespace ScriptFeedItem