/**
 * @file  SerializedSkin.hpp
 * @note  This Header is auto generated by LiteLoaderBDS Toolchain.
 *
 */
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "persona.hpp"

#define BEFORE_EXTRA
// Include Headers or Declare Types Here

#undef BEFORE_EXTRA

/**
 * @brief MC class SerializedSkin.
 *
 */
class SerializedSkin {

#define AFTER_EXTRA
// Add Member There
    char filler[620];
#undef AFTER_EXTRA
public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_SERIALIZEDSKIN
#endif
    MCAPI SerializedSkin(class SubClientConnectionRequest const &);
    MCAPI SerializedSkin(class ConnectionRequest const &);
    MCAPI SerializedSkin(class SerializedSkin const &);
    MCAPI SerializedSkin(class SerializedSkin &&);
    MCAPI SerializedSkin();
    MCAPI float getAnimationFrames(enum persona::AnimatedTextureType) const;
    MCAPI std::string const & getName() const;
    MCAPI bool isTrustedSkin() const;
    MCAPI class SerializedSkin & operator=(class SerializedSkin const &);
    MCAPI bool read(class ReadOnlyBinaryStream &);
    MCAPI void setIsTrustedSkin(bool);
    MCAPI void updateGeometryName();
    MCAPI bool useBlinkingAnimation() const;
    MCAPI void write(class BinaryStream &) const;
    MCAPI ~SerializedSkin();
    MCAPI static class SerializedSkin createTrustedDefaultSerializedSkin();
    MCAPI static bool isSkinDisabled(class SerializedSkin const &, class LevelData const &);

};