// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

namespace ServerPlayerInputSystemUtils {

#define AFTER_EXTRA

#undef AFTER_EXTRA
    MCAPI void _tickPlayerMovement(struct PlayerCurrentTickComponent const &, struct ServerPlayerMovementComponent &, class EntityModifierT<class EntityRegistryBase, class StrictEntityContext, struct ServerPlayerCurrentMovementComponent> &, class StrictEntityContext &);

};