/**
 * @file  SHRightTurn.hpp
 * @note  This Header is auto generated by LiteLoaderBDS Toolchain.
 *
 */
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "StructurePiece.hpp"

#define BEFORE_EXTRA
// Include Headers or Declare Types Here

#undef BEFORE_EXTRA

/**
 * @brief MC class SHRightTurn.
 *
 */
class SHRightTurn : public StructurePiece {

#define AFTER_EXTRA
// Add Member There

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_SHRIGHTTURN
public:
    class SHRightTurn& operator=(class SHRightTurn const &) = delete;
    SHRightTurn(class SHRightTurn const &) = delete;
    SHRightTurn() = delete;
#endif

public:
    virtual ~SHRightTurn();
    virtual enum StructurePieceType getType() const;
    virtual void addChildren(class StructurePiece &, std::vector<std::unique_ptr<class StructurePiece>> &, class Random &);
    virtual bool postProcess(class BlockSource &, class Random &, class BoundingBox const &);
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_SHRIGHTTURN
#endif

};