// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#include <Global.h>
#define EXTRA_INCLUDE_PART_SHULKERBOXCONTAINERSCREENVALIDATOR
#include "Extra/ShulkerBoxContainerScreenValidatorAPI.hpp"
#undef EXTRA_INCLUDE_PART_SHULKERBOXCONTAINERSCREENVALIDATOR
class ShulkerBoxContainerScreenValidator {
#include "Extra/ShulkerBoxContainerScreenValidatorAPI.hpp"
public:
    /*0*/ virtual ~ShulkerBoxContainerScreenValidator();
};