// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#include <Global.h>
#define EXTRA_INCLUDE_PART_SIMPLETREETRUNK
#include "Extra/SimpleTreeTrunkAPI.hpp"
#undef EXTRA_INCLUDE_PART_SIMPLETREETRUNK
class SimpleTreeTrunk {
#include "Extra/SimpleTreeTrunkAPI.hpp"
public:
    virtual ~SimpleTreeTrunk();
    virtual class std::optional<class BlockPos> placeTrunk(class IBlockWorldGenAPI&, class BlockPos const&, class Random&, class RenderParams&, struct TreeHelper::TreeParams const&, class ITreeCanopy const*);
};