/**
 * @file  SmithingTableContainerManagerModel.hpp
 * @note  This Header is auto generated by LiteLoaderBDS Toolchain.
 *
 */
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "ContainerManagerModel.hpp"

#define BEFORE_EXTRA
// Include Headers or Declare Types Here

#undef BEFORE_EXTRA

/**
 * @brief MC class SmithingTableContainerManagerModel.
 *
 */
class SmithingTableContainerManagerModel : public ContainerManagerModel {

#define AFTER_EXTRA
// Add Member There

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_SMITHINGTABLECONTAINERMANAGERMODEL
public:
    class SmithingTableContainerManagerModel& operator=(class SmithingTableContainerManagerModel const &) = delete;
    SmithingTableContainerManagerModel(class SmithingTableContainerManagerModel const &) = delete;
    SmithingTableContainerManagerModel() = delete;
#endif

public:
    virtual ~SmithingTableContainerManagerModel();
    virtual std::vector<class ItemStack> getItemCopies() const;
    virtual void setSlot(int, class ItemStack const &, bool);
    virtual class ItemStack const & getSlot(int) const;
    virtual void setData(int, int);
    virtual void broadcastChanges();
    virtual bool isValid(float);
    virtual class ContainerScreenContext _postInit();
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_SMITHINGTABLECONTAINERMANAGERMODEL
#endif
    MCAPI SmithingTableContainerManagerModel(enum ContainerID, class Player &, class BlockPos const &);
MCAPI static int const INPUT_SLOT;
MCAPI static int const MATERIAL_SLOT;
MCAPI static int const RESULT_SLOT;

};