// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#include <Global.h>
#define EXTRA_INCLUDE_PART_STRENGTHDESCRIPTION
#include "Extra/StrengthDescriptionAPI.hpp"
#undef EXTRA_INCLUDE_PART_STRENGTHDESCRIPTION
class StrengthDescription {
#include "Extra/StrengthDescriptionAPI.hpp"
public:
    virtual char const* getJsonName();
    virtual ~StrengthDescription();
    virtual void deserializeData(struct DeserializeDataParams);
    virtual void serializeData(class Json::Value&);
};