/**
 * @file  TextureAtlasItem.hpp
 * @note  This Header is auto generated by LiteLoaderBDS Toolchain.
 *
 */
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

/**
 * @brief MC class TextureAtlasItem.
 *
 */
class TextureAtlasItem {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_TEXTUREATLASITEM
public:
    class TextureAtlasItem& operator=(class TextureAtlasItem const &) = delete;
    TextureAtlasItem(class TextureAtlasItem const &) = delete;
    TextureAtlasItem() = delete;
#endif

public:
    /**
     * @symbol ??1TextureAtlasItem@@QEAA@XZ
     * @hash   1107491949
     */
    MCAPI ~TextureAtlasItem();

};