// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#include <Global.h>
#include "Packet.hpp"
#define EXTRA_INCLUDE_PART_TRANSFERPACKET
#include "Extra/TransferPacketAPI.hpp"
#undef EXTRA_INCLUDE_PART_TRANSFERPACKET
class TransferPacket : public Packet {
#include "Extra/TransferPacketAPI.hpp"
public:
    virtual ~TransferPacket();
    virtual int /*enum MinecraftPacketIds*/ getId();
    virtual std::string getName();
    virtual void write(class BinaryStream&);
    virtual void unk_vfn_5();
    virtual int /*enum StreamReadResult*/ _read(class ReadOnlyBinaryStream&);

public:
    MCAPI TransferPacket();
    MCAPI TransferPacket(std::string const&, int);
};