// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#include <Global.h>
namespace VanillaTags {

MCAPI class HashedString const DiamondDiggable;
MCAPI class HashedString const Dirt;
MCAPI class HashedString const FertilizeArea;
MCAPI class HashedString const GoldDiggable;
MCAPI class HashedString const Grass;
MCAPI class HashedString const Gravel;
MCAPI class HashedString const IronDiggable;
MCAPI class HashedString const Metal;
MCAPI class HashedString const MobSpawner;
MCAPI class HashedString const NotFeatureReplaceable;
MCAPI class HashedString const Plant;
MCAPI class HashedString const Pumpkin;
MCAPI class HashedString const Rail;
MCAPI class HashedString const Sand;
MCAPI class HashedString const Snow;
MCAPI class HashedString const Stone;
MCAPI class HashedString const StoneDiggable;
MCAPI class HashedString const TextSign;
MCAPI class HashedString const Water;
MCAPI class HashedString const Wood;
MCAPI class HashedString const WoodDiggable;

} // namespace VanillaTags