// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#include <Global.h>
#define EXTRA_INCLUDE_PART_VANILLABLOCKS
#include "Extra/VanillaBlocksAPI.hpp"
#undef EXTRA_INCLUDE_PART_VANILLABLOCKS
namespace VanillaBlocks {
#include "Extra/VanillaBlocksAPI.hpp"

MCAPI void assignBlocks(class Experiments const&);
MCAPI void unassignBlocks();

} // namespace VanillaBlocks