// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#include <Global.h>
#define EXTRA_INCLUDE_PART_WORLDTEMPLATEMANAGERPROXYCALLBACKS
#include "Extra/WorldTemplateManagerProxyCallbacksAPI.hpp"
#undef EXTRA_INCLUDE_PART_WORLDTEMPLATEMANAGERPROXYCALLBACKS
class WorldTemplateManagerProxyCallbacks {
#include "Extra/WorldTemplateManagerProxyCallbacksAPI.hpp"

public:
    MCAPI ~WorldTemplateManagerProxyCallbacks();
};