// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#include "../Global.h"
#include "ZipPackAccessStrategy.hpp"
#include "Core.hpp"
#define EXTRA_INCLUDE_PART_ZIPPACKACCESSSTRATEGYOWNINGFILEACCCESS
#include "Extra/ZipPackAccessStrategyOwningFileAcccessAPI.hpp"
#undef EXTRA_INCLUDE_PART_ZIPPACKACCESSSTRATEGYOWNINGFILEACCCESS
class ZipPackAccessStrategyOwningFileAcccess : public ZipPackAccessStrategy {
#include "Extra/ZipPackAccessStrategyOwningFileAcccessAPI.hpp"
public:
    /*0*/ virtual ~ZipPackAccessStrategyOwningFileAcccess();
    /*1*/ virtual class ResourceLocation const& getPackLocation() const;
    /*2*/ virtual std::string const& getPackName() const;
    /*3*/ virtual void forEachInAssetSet(class Core::Path const&, class std::function<void (class Core::Path const& )>) const;
    /*4*/ virtual int /*enum enum PackAccessStrategyType*/ getStrategyType() const;
    /*5*/ virtual class Core::PathBuffer<std::string > const& getSubPath() const;
    /*6*/ virtual bool canRecurse() const;


protected:

private:
};