#pragma once

#include "mc/_HeaderOutputPredefine.h"

enum class MinecraftPacketIds : int {
    KeepAlive                                = 0,   // 心跳包，保持连接
    Login                                    = 1,   // 登录
    PlayStatus                               = 2,   // 游戏状态
    ServerToClientHandshake                  = 3,   // 服务端到客户端握手
    ClientToServerHandshake                  = 4,   // 客户端到服务端握手
    Disconnect                               = 5,   // 断开连接
    ResourcePacksInfo                        = 6,   // 资源包信息
    ResourcePackStack                        = 7,   // 资源包堆栈
    ResourcePackClientResponse               = 8,   // 资源包客户端响应
    Text                                     = 9,   // 文本消息
    SetTime                                  = 10,  // 设置时间
    StartGame                                = 11,  // 开始游戏
    AddPlayer                                = 12,  // 添加玩家
    AddActor                                 = 13,  // 添加实体
    RemoveActor                              = 14,  // 移除实体
    AddItemActor                             = 15,  // 添加物品实体
    ServerPlayerPostMovePosition             = 16,  // 服务端玩家移动后位置 (已废弃)
    TakeItemActor                            = 17,  // 拾取物品实体
    MoveAbsoluteActor                        = 18,  // 实体绝对移动
    MovePlayer                               = 19,  // 玩家移动
    PassengerJumpDeprecated                  = 20,  // 乘客跳跃 (已弃用)
    UpdateBlock                              = 21,  // 更新方块
    AddPainting                              = 22,  // 添加画
    TickSyncDeprecated                       = 23,  // 刻同步 (已弃用)
    LevelSoundEventV1Deprecated              = 24,  // 世界声音事件V1 (已弃用)
    LevelEvent                               = 25,  // 世界事件
    TileEvent                                = 26,  // 方块事件
    ActorEvent                               = 27,  // 实体事件
    MobEffect                                = 28,  // 生物效果
    UpdateAttributes                         = 29,  // 更新属性
    InventoryTransaction                     = 30,  // 物品栏事务
    PlayerEquipment                          = 31,  // 玩家装备
    MobArmorEquipment                        = 32,  // 生物盔甲装备
    Interact                                 = 33,  // 交互
    BlockPickRequest                         = 34,  // 方块拾取请求
    ActorPickRequest                         = 35,  // 实体拾取请求
    PlayerAction                             = 36,  // 玩家行为
    ActorFallDeprecated                      = 37,  // 实体坠落 (已弃用)
    HurtArmor                                = 38,  // 盔甲受损
    SetActorData                             = 39,  // 设置实体数据
    SetActorMotion                           = 40,  // 设置实体运动
    SetActorLink                             = 41,  // 设置实体链接
    SetHealth                                = 42,  // 设置生命值
    SetSpawnPosition                         = 43,  // 设置出生点
    Animate                                  = 44,  // 播放动画
    Respawn                                  = 45,  // 重生
    ContainerOpen                            = 46,  // 打开容器
    ContainerClose                           = 47,  // 关闭容器
    PlayerHotbar                             = 48,  // 玩家快捷栏
    InventoryContent                         = 49,  // 物品栏内容
    InventorySlot                            = 50,  // 物品栏槽位
    ContainerSetData                         = 51,  // 设置容器数据
    CraftingData                             = 52,  // 合成数据
    CraftingEventDeprecated                  = 53,  // 合成事件 (已弃用)
    GuiDataPickItem                          = 54,  // GUI数据拾取物品
    AdventureSettingsDeprecated              = 55,  // 冒险模式设置 (已弃用)
    BlockActorData                           = 56,  // 方块实体数据
    PlayerInputDeprecated                    = 57,  // 玩家输入 (已弃用)
    FullChunkData                            = 58,  // 完整区块数据
    SetCommandsEnabled                       = 59,  // 设置命令启用状态
    SetDifficulty                            = 60,  // 设置难度
    ChangeDimension                          = 61,  // 切换维度
    SetPlayerGameType                        = 62,  // 设置玩家游戏模式
    PlayerList                               = 63,  // 玩家列表
    SimpleEvent                              = 64,  // 简单事件
    LegacyTelemetryEvent                     = 65,  // 旧版遥测事件
    SpawnExperienceOrb                       = 66,  // 生成经验球
    MapData                                  = 67,  // 地图数据
    MapInfoRequest                           = 68,  // 地图信息请求
    RequestChunkRadius                       = 69,  // 请求区块半径
    ChunkRadiusUpdated                       = 70,  // 区块半径更新
    ItemFrameDropItemDeprecated              = 71,  // 物品展示框掉落物品 (已弃用)
    GameRulesChanged                         = 72,  // 游戏规则变更
    Camera                                   = 73,  // 相机
    BossEvent                                = 74,  // Boss事件
    ShowCredits                              = 75,  // 显示制作人员名单
    AvailableCommands                        = 76,  // 可用命令
    CommandRequest                           = 77,  // 命令请求
    CommandBlockUpdate                       = 78,  // 命令方块更新
    CommandOutput                            = 79,  // 命令输出
    UpdateTrade                              = 80,  // 更新交易
    UpdateEquip                              = 81,  // 更新装备
    ResourcePackDataInfo                     = 82,  // 资源包数据信息
    ResourcePackChunkData                    = 83,  // 资源包区块数据
    ResourcePackChunkRequest                 = 84,  // 资源包区块请求
    Transfer                                 = 85,  // 传送(跨服)
    PlaySound                                = 86,  // 播放声音
    StopSound                                = 87,  // 停止声音
    SetTitle                                 = 88,  // 设置标题
    AddBehaviorTree                          = 89,  // 添加行为树
    StructureBlockUpdate                     = 90,  // 结构方块更新
    ShowStoreOffer                           = 91,  // 显示商店优惠
    PurchaseReceipt                          = 92,  // 购买收据
    PlayerSkin                               = 93,  // 玩家皮肤
    SubclientLogin                           = 94,  // 子客户端登录
    AutomationClientConnect                  = 95,  // 自动化客户端连接
    SetLastHurtBy                            = 96,  // 设置最后伤害来源
    BookEdit                                 = 97,  // 书本编辑
    NPCRequest                               = 98,  // NPC请求
    PhotoTransfer                            = 99,  // 照片传输
    ShowModalForm                            = 100, // 显示模态表单
    ModalFormResponse                        = 101, // 模态表单响应
    ServerSettingsRequest                    = 102, // 服务器设置请求
    ServerSettingsResponse                   = 103, // 服务器设置响应
    ShowProfile                              = 104, // 显示个人资料
    SetDefaultGameType                       = 105, // 设置默认游戏模式
    RemoveObjective                          = 106, // 移除计分板目标
    SetDisplayObjective                      = 107, // 设置计分板显示目标
    SetScore                                 = 108, // 设置分数
    LabTable                                 = 109, // 实验台
    UpdateBlockSynced                        = 110, // 同步更新方块
    MoveDeltaActor                           = 111, // 实体增量移动
    SetScoreboardIdentity                    = 112, // 设置计分板身份
    SetLocalPlayerAsInit                     = 113, // 设置本地玩家为已初始化
    UpdateSoftEnum                           = 114, // 更新软枚举
    Ping                                     = 115, // Ping
    BlockPaletteDeprecated                   = 116, // 方块调色板 (已弃用)
    ScriptCustomEvent                        = 117, // 脚本自定义事件
    SpawnParticleEffect                      = 118, // 生成粒子效果
    AvailableActorIDList                     = 119, // 可用实体ID列表
    LevelSoundEventV2Deprecated              = 120, // 世界声音事件V2 (已弃用)
    NetworkChunkPublisherUpdate              = 121, // 网络区块发布者更新
    BiomeDefinitionList                      = 122, // 生物群系定义列表
    LevelSoundEvent                          = 123, // 世界声音事件
    LevelEventGeneric                        = 124, // 通用世界事件
    LecternUpdate                            = 125, // 讲台更新
    VideoStreamConnectDeprecated             = 126, // 视频流连接 (已弃用)
    AddEntityDeprecated                      = 127, // 添加实体 (已弃用)
    RemoveEntityDeprecated                   = 128, // 移除实体 (已弃用)
    ClientCacheStatus                        = 129, // 客户端缓存状态
    OnScreenTextureAnimation                 = 130, // 屏幕纹理动画
    MapCreateLockedCopy                      = 131, // 创建锁定的地图副本
    StructureTemplateDataExportRequest       = 132, // 结构模板数据导出请求
    StructureTemplateDataExportResponse      = 133, // 结构模板数据导出响应
    UnusedPlsUseMe                           = 134, // 未使用(占位)
    ClientCacheBlobStatusPacket              = 135, // 客户端缓存Blob状态包
    ClientCacheMissResponsePacket            = 136, // 客户端缓存未命中响应包
    EducationSettingsPacket                  = 137, // 教育版设置包
    Emote                                    = 138, // 表情
    MultiplayerSettingsPacket                = 139, // 多人游戏设置包
    SettingsCommandPacket                    = 140, // 设置命令包
    AnvilDamage                              = 141, // 铁砧损坏
    CompletedUsingItem                       = 142, // 完成物品使用
    NetworkSettings                          = 143, // 网络设置
    PlayerAuthInputPacket                    = 144, // 玩家验证输入包
    CreativeContent                          = 145, // 创造模式内容
    PlayerEnchantOptions                     = 146, // 玩家附魔选项
    ItemStackRequest                         = 147, // 物品堆栈请求
    ItemStackResponse                        = 148, // 物品堆栈响应
    PlayerArmorDamage                        = 149, // 玩家盔甲损坏
    CodeBuilderPacket                        = 150, // 代码构建器包
    UpdatePlayerGameType                     = 151, // 更新玩家游戏模式
    EmoteList                                = 152, // 表情列表
    PositionTrackingDBServerBroadcast        = 153, // 位置跟踪数据库服务端广播
    PositionTrackingDBClientRequest          = 154, // 位置跟踪数据库客户端请求
    DebugInfoPacket                          = 155, // 调试信息包
    PacketViolationWarning                   = 156, // 数据包违规警告
    MotionPredictionHints                    = 157, // 运动预测提示
    TriggerAnimation                         = 158, // 触发动画
    CameraShake                              = 159, // 相机晃动
    PlayerFogSetting                         = 160, // 玩家迷雾设置
    CorrectPlayerMovePredictionPacket        = 161, // 修正玩家移动预测包
    ItemRegistryPacket                       = 162, // 物品注册表包
    FilterTextPacketDeprecated               = 163, // 文本过滤包 (已弃用)
    ClientBoundDebugRendererPacket           = 164, // 客户端调试渲染器包
    SyncActorProperty                        = 165, // 同步实体属性
    AddVolumeEntityPacket                    = 166, // 添加体积实体包
    RemoveVolumeEntityPacket                 = 167, // 移除体积实体包
    SimulationTypePacket                     = 168, // 模拟类型包
    NpcDialoguePacket                        = 169, // NPC对话包
    EduUriResourcePacket                     = 170, // 教育版URI资源包
    CreatePhotoPacket                        = 171, // 创建照片包
    UpdateSubChunkBlocks                     = 172, // 更新子区块方块
    PhotoInfoRequestDeprecated               = 173, // 照片信息请求 (已弃用)
    SubChunkPacket                           = 174, // 子区块包
    SubChunkRequestPacket                    = 175, // 子区块请求包
    PlayerStartItemCooldown                  = 176, // 玩家物品冷却开始
    ScriptMessagePacket                      = 177, // 脚本消息包
    CodeBuilderSourcePacket                  = 178, // 代码构建器源码包
    TickingAreasLoadStatus                   = 179, // 常加载区域加载状态
    DimensionDataPacket                      = 180, // 维度数据包
    AgentAction                              = 181, // 代理(Agent)行为
    ChangeMobProperty                        = 182, // 更改生物属性
    LessonProgressPacket                     = 183, // 课程进度包
    RequestAbilityPacket                     = 184, // 请求能力包
    RequestPermissionsPacket                 = 185, // 请求权限包
    ToastRequest                             = 186, // 弹出消息请求
    UpdateAbilitiesPacket                    = 187, // 更新能力包
    UpdateAdventureSettingsPacket            = 188, // 更新冒险设置包
    DeathInfo                                = 189, // 死亡信息
    EditorNetworkPacket                      = 190, // 编辑器网络包
    FeatureRegistryPacket                    = 191, // 特性注册表包
    ServerStats                              = 192, // 服务器状态
    RequestNetworkSettings                   = 193, // 请求网络设置
    GameTestRequestPacket                    = 194, // 游戏测试请求包
    GameTestResultsPacket                    = 195, // 游戏测试结果包
    PlayerClientInputPermissions             = 196, // 玩家客户端输入权限
    ClientCheatAbilityPacketDeprecated       = 197, // 客户端作弊能力包 (已弃用)
    CameraPresets                            = 198, // 相机预设
    UnlockedRecipes                          = 199, // 已解锁配方
    TitleSpecificPacketsStart                = 200, // (保留范围开始)
    TitleSpecificPacketsEnd                  = 299, // (保留范围结束)
    CameraInstruction                        = 300, // 相机指令
    CompressedBiomeDefinitionListDeprecated  = 301, // 压缩的生物群系定义列表 (已弃用)
    TrimData                                 = 302, // 镶边数据
    OpenSign                                 = 303, // 打开告示牌
    AgentAnimation                           = 304, // 代理(Agent)动画
    RefreshEntitlementsPacket                = 305, // 刷新权益包
    PlayerToggleCrafterSlotRequestPacket     = 306, // 玩家切换合成器槽位请求包
    SetPlayerInventoryOptions                = 307, // 设置玩家物品栏选项
    SetHudPacket                             = 308, // 设置HUD包
    AwardAchievementPacket                   = 309, // 授予成就包
    ClientboundCloseScreen                   = 310, // 客户端关闭屏幕
    ClientboundLoadingScreenPacketDeprecated = 311, // 客户端加载屏幕包 (已弃用)
    ServerboundLoadingScreenPacket           = 312, // 服务端加载屏幕包
    JigsawStructureDataPacket                = 313, // 拼图结构数据包
    CurrentStructureFeaturePacket            = 314, // 当前结构特性包
    ServerboundDiagnosticsPacket             = 315, // 服务端诊断包
    CameraAimAssist                          = 316, // 相机辅助瞄准
    ContainerRegistryCleanup                 = 317, // 容器注册表清理
    MovementEffect                           = 318, // 移动效果
    SetMovementAuthorityModeDeprecated       = 319, // 设置移动权限模式 (已弃用)
    CameraAimAssistPresets                   = 320, // 相机辅助瞄准预设
    ClientCameraAimAssist                    = 321, // 客户端相机辅助瞄准
    ClientMovementPredictionSyncPacket       = 322, // 客户端移动预测同步包
    UpdateClientOptions                      = 323, // 更新客户端选项
    PlayerVideoCapturePacket                 = 324, // 玩家视频捕获包
    PlayerUpdateEntityOverridesPacket        = 325, // 玩家更新实体覆盖包
    PlayerLocation                           = 326, // 玩家位置
    ClientboundControlSchemeSetPacket        = 327, // 客户端控制方案设置包
    ServerScriptDebugDrawerPacket            = 328, // 服务端脚本调试绘制器包
    EndId                                    = 329, // 结束ID
};
