#pragma once

#include "mc/_HeaderOutputPredefine.h"

enum class SettingsTabIndex : int {
    Default               = 0,
    ServerTab             = 1,
    AccessibilityTab      = 2,
    HowToPlay             = 3,
    GameTab               = 4,
    ClassroomTab          = 5,
    EduCloudLevelTab      = 6,
    MultiplayerTab        = 7,
    RealmTab              = 8,
    MembersTab            = 9,
    SubscriptionTab       = 10,
    DevOptionsTab         = 11,
    RealmBackupTab        = 12,
    KeyboardAndMouseTab   = 13,
    ControllerTab         = 14,
    TouchTab              = 15,
    PartyTab              = 16,
    GeneralTab            = 17,
    AccountTab            = 18,
    CreatorTab            = 19,
    VideoTab              = 20,
    ViewSubscriptionsTab  = 21,
    SoundTab              = 22,
    GlobalResourcesTab    = 23,
    StorageTab            = 24,
    EduCloudStorageTab    = 25,
    LanguageTab           = 26,
    PreviewTab            = 27,
    DebugTab              = 28,
    DiscoveryDebugTab     = 29,
    UiDebugTab            = 30,
    EduDebugTab           = 31,
    MarketplaceDebugTab   = 32,
    GatheringsDebugTab    = 33,
    FlightingDebugTab     = 34,
    RealmsDebugTab        = 35,
    AutomationTab         = 36,
    LevelTexturePackTab   = 37,
    BroadcastTab          = 38,
    AddonTab              = 39,
    InviteLinksTab        = 40,
    GeneralInviteLinkTab  = 41,
    AdvancedInviteLinkTab = 42,
    Count                 = 43,
};
