#ifndef PCH_H
#define PCH_H
#include <liteloader.h>
#include <loader/Loader.h>
#include <iostream>
#include "framework.h"
// LiteLoader.cpp
#include <api/regCommandHelper.h>
#include <api/xuidreg/xuidreg.h>
#include <lbpch.h>
#include <filesystem>
#include <map>
#include "framework.h"
// CheckUpdate.cpp
#include <rapidjson/document.h>
#include <rapidjson/rapidjson.h>
#include <iostream>
#include <string>
#include <stl/logger.h>
#endif  // PCH_H