#pragma once
#include <LLAPI.h>

#define LITELOADER_VERSION_MAJOR 2
#define LITELOADER_VERSION_MINOR 0
#define LITELOADER_VERSION_REVISION 1

#define LITELOADER_VERSION_STATUS Beta

#define LITELOADER_VERSION LL::Version(LITELOADER_VERSION_MAJOR, LITELOADER_VERSION_MINOR, LITELOADER_VERSION_REVISION, LL::Version::Status::LITELOADER_VERSION_STATUS)