#pragma once
#include <LLAPI.h>

#define LITELOADER_VERSION_MAJOR 2
#define LITELOADER_VERSION_MINOR 0
#define LITELOADER_VERSION_REVISION 0

#define LITELOADER_VERSION LL::Version(LITELOADER_VERSION_MAJOR, LITELOADER_VERSION_MINOR, LITELOADER_VERSION_REVISION)

#define LITELOADER_VERSION_STATUS Release