#pragma once

#include "mc/_HeaderOutputPredefine.h"

enum class EncyclopediaTopicIndex : int {
    Armor = 0,
    ArmorStand = 1,
    Banners = 2,
    Beacons = 3,
    Beds = 4,
    Blocks = 5,
    BookAndQuill = 6,
    Chests = 7,
    Conduits = 8,
    Dyes = 9,
    Farming = 10,
    Fireworks = 11,
    Fishing = 12,
    JigsawBlocks = 13,
    Mounts = 14,
    Navigation = 15,
    NetherPortals = 16,
    Pets = 17,
    Raids = 18,
    Ranching = 19,
    Scaffolding = 20,
    StructureBlocks = 21,
    Tools = 22,
    Transportation = 23,
    Trading = 24,
    Weapons = 25,
    Anvil = 26,
    BrewingStand = 27,
    Cauldron = 28,
    CraftingTable = 29,
    EnchantingTable = 30,
    Furnace = 31,
    Loom = 32,
    SmithingTable = 33,
    Droppers = 34,
    Dispensers = 35,
    Hoppers = 36,
    Jukebox = 37,
    Redstone = 38,
    TheEnd = 39,
    EyeOfEnder = 40,
    EndCities = 41,
    Elytra = 42,
    ShulkerBoxes = 43,
    GameSettings = 44,
    Difficulty = 45,
    AdventureMode = 46,
    CreativeMode = 47,
    Commands = 48,
    HostAndPlayerOptions = 49,
    CommandBlocks = 50,
    RealmsStories = 51,
    TopicCount = 52,
};
