#pragma once

#include "mc/_HeaderOutputPredefine.h"

namespace ui {

enum class GameEventNotification : uint {
    Empty = 0,
    PlayerDeath = 1,
    PlayerListChanged = 2,
    PlayerSignedIn = 3,
    PlayerSignedOut = 4,
    PlayerDisconnected = 5,
    NewMessage = 6,
    NewConsoleMessage = 7,
    ResourcePackConfirmation = 8,
    ResourcePackDownloadFinished = 9,
    PlayerExperienceChanged = 10,
    PlayerArmorChanged = 11,
    TitleChanged = 12,
    TitleCleared = 13,
    SubtitleChanged = 14,
    ServerSettingsChanged = 15,
    ActionBarMessageChanged = 16,
    StoreUpdated = 17,
    StoreSalesUpdated = 18,
    LanguageChanged = 19,
    ScreenPushed = 20,
    ScreenPopped = 21,
    ScreenSizeChanged = 22,
    SavingStart = 23,
    SavingFinished = 24,
    StructureRendered = 25,
    StructureNotRendered = 26,
    AnimationsEnabledChanged = 27,
    CurrencyPurchaseMinecoinPackFound = 28,
    NewContentLogMessage = 29,
    ContentMessagesCleared = 30,
    NewPerfTurtleMessage = 31,
    IdentityGained = 32,
    PersonaSynced = 33,
    StructureDataExportSuccess = 34,
    StructureDataExportFailed = 35,
    StructureDataImport = 36,
    StructureDataQuerySuccess = 37,
    StructureDataQueryFailed = 38,
    WebviewDismissed = 39,
    EntitlementsChanged = 40,
    PlayerRespawnBlocked = 41,
    PlayerReadyToRespawn = 42,
    EduResourceUriModified = 43,
    OnScreenKeyboardTruncation = 44,
    RevertToLegacyWorldPackDownloader = 45,
    HudElementVisibilityUpdated = 46,
};

}
