#pragma once

#include "mc/_HeaderOutputPredefine.h"

enum class SettingsTabIndex : int {
    Default = 0,
    ServerTab = 1,
    AccessibilityTab = 2,
    HowToPlay = 3,
    GameTab = 4,
    ClassroomTab = 5,
    EduCloudLevelTab = 6,
    MultiplayerTab = 7,
    RealmTab = 8,
    MembersTab = 9,
    RealmsSavesTab = 10,
    SubscriptionTab = 11,
    RealmBackupTab = 12,
    DevOptionsTab = 13,
    KeyboardAndMouseTab = 14,
    ControllerTab = 15,
    TouchTab = 16,
    PartyTab = 17,
    GeneralTab = 18,
    AccountTab = 19,
    CreatorTab = 20,
    VideoTab = 21,
    ViewSubscriptionsTab = 22,
    SoundTab = 23,
    GlobalResourcesTab = 24,
    StorageTab = 25,
    EduCloudStorageTab = 26,
    LanguageTab = 27,
    PreviewTab = 28,
    DebugTab = 29,
    DiscoveryDebugTab = 30,
    UiDebugTab = 31,
    EduDebugTab = 32,
    MarketplaceDebugTab = 33,
    GatheringsDebugTab = 34,
    FlightingDebugTab = 35,
    RealmsDebugTab = 36,
    AutomationTab = 37,
    LevelTexturePackTab = 38,
    BroadcastTab = 39,
    AddonTab = 40,
    InviteLinksTab = 41,
    GeneralInviteLinkTab = 42,
    AdvancedInviteLinkTab = 43,
    RealmsAdvancedTab = 44,
    Count = 45,
};
