#pragma once

#include "mc/_HeaderOutputPredefine.h"

namespace Remapping {

enum class ActionEnum : int {
    Attack                                 = 0,
    PickItem                               = 1,
    Use                                    = 2,
    Drop                                   = 3,
    Hotbar1                                = 4,
    Hotbar2                                = 5,
    Hotbar3                                = 6,
    Hotbar4                                = 7,
    Hotbar5                                = 8,
    Hotbar6                                = 9,
    Hotbar7                                = 10,
    Hotbar8                                = 11,
    Hotbar9                                = 12,
    Inventory                              = 13,
    TogglePerspective                      = 14,
    LookUpSlight                           = 15,
    LookDownSlight                         = 16,
    LookUpRight                            = 17,
    LookUp                                 = 18,
    LookUpLeft                             = 19,
    LookRight                              = 20,
    LookCenter                             = 21,
    LookLeft                               = 22,
    LookDownRight                          = 23,
    LookDown                               = 24,
    LookDownLeft                           = 25,
    LookUpSmooth                           = 26,
    LookDownSmooth                         = 27,
    LookLeftSmooth                         = 28,
    LookRightSmooth                        = 29,
    Jump                                   = 30,
    Sneak                                  = 31,
    Sprint                                 = 32,
    Left                                   = 33,
    Right                                  = 34,
    Back                                   = 35,
    Forward                                = 36,
    Chat                                   = 37,
    Crafting                               = 38,
    CycleItemLeft                          = 39,
    CycleItemRight                         = 40,
    Pause                                  = 41,
    FlyUpSlow                              = 42,
    FlyDownSlow                            = 43,
    MobEffects                             = 44,
    ToastInteract                          = 45,
    Command                                = 46,
    MenuTabLeft                            = 47,
    MenuTabRight                           = 48,
    MenuCancel                             = 49,
    CodeBuilder                            = 50,
    ImmersiveReader                        = 51,
    Emote                                  = 52,
    EmoteExpediate0                        = 53,
    EmoteExpediate1                        = 54,
    EmoteExpediate2                        = 55,
    EmoteExpediate3                        = 56,
    ToggleControlHUD                       = 57,
    SocialDrawerMobEffectsAndToastInteract = 58,
    MobEffectsAndToastInteract             = 59,
    ScriptToggle                           = 60,
    ScriptCancel                           = 61,
    ScriptOpenMap                          = 62,
    ScriptOpenChat                         = 63,
    ScriptOpenInventory                    = 64,
    ScriptOpenMission                      = 65,
    CopyCoordinates                        = 66,
    CopyFacingCoordinates                  = 67,
    Screenshot                             = 68,
    SocialDrawer                           = 69,
    CommandMacro0                          = 70,
    CommandMacro1                          = 71,
    CommandMacro2                          = 72,
    CommandMacro3                          = 73,
    CommandMacro4                          = 74,
    CommandMacro5                          = 75,
    CommandMacro6                          = 76,
    CommandMacro7                          = 77,
    CommandMacro8                          = 78,
    CommandMacro9                          = 79,
    DescribeBlock                          = 80,
    Count                                  = 81,
};

}
