#pragma once

#include "mc/_HeaderOutputPredefine.h"

namespace Editor::Settings {

enum class ThemeSettingsColorKey : int {
    TitleBarBackground = 0,
    PanelBackground = 1,
    HeaderBackground = 2,
    PanelBorder = 3,
    ElementBorder = 4,
    PrimaryActive = 5,
    PrimaryDefault = 6,
    PrimaryMute = 7,
    PrimaryDisable = 8,
    PrimaryBackground1 = 9,
    PrimaryBackground2 = 10,
    PrimaryBackground3 = 11,
    PrimaryBackground4 = 12,
    SecondaryActive = 13,
    SecondaryDefault = 14,
    SecondaryMute = 15,
    SecondaryDisable = 16,
    SecondaryBackground1 = 17,
    SecondaryBackground2 = 18,
    SecondaryBackground3 = 19,
    DropDown1 = 20,
    DropDown2 = 21,
    DropDown3 = 22,
    ScrollBar = 23,
    FocusOutline = 24,
    FocusErrorOutline = 25,
    Warning = 26,
    Error = 27,
    HotbarOutline = 28,
    ViewportOutline = 29,
    DisableBackground = 30,
    DisableOutline = 31,
    DisableText = 32,
    DisableFill = 33,
    Coordinate1 = 34,
    Coordinate2 = 35,
    Coordinate3 = 36,
    ConfirmFill = 37,
    Confirm1 = 38,
    Confirm2 = 39,
    Confirm3 = 40,
    DestroyFill = 41,
    Destroy1 = 42,
    Destroy2 = 43,
    Destroy3 = 44,
    InfoFill = 45,
    Info1 = 46,
    Info2 = 47,
    Info3 = 48,
    Caret = 49,
    CursorVolumeBorder = 50,
    CursorVolumeFill = 51,
    SelectionVolumeBorder = 52,
    SelectionVolumeFill = 53,
    SelectionVolumeOutlineBorder = 54,
    SelectionVolumeOutlineFill = 55,
    PrefillVolumeBorder = 56,
    PrefillVolumeFill = 57,
    PlacementVolumeBorder = 58,
    PlacementVolumeFill = 59,
    ControlsGeneralFill = 60,
    ControlsGeneralHighlight = 61,
    CoordinateControlX = 62,
    CoordinateControlY = 63,
    CoordinateControlZ = 64,
};

}
