#pragma once

#include "mc/_HeaderOutputPredefine.h"

namespace GameEventConfig {

enum class GameEventType : int {
    Invalid                     = 0,
    BlockActivate               = 1,
    BlockAttach                 = 2,
    BlockChange                 = 3,
    BlockClose                  = 4,
    BlockDeactivate             = 5,
    BlockDestroy                = 6,
    BlockDetach                 = 7,
    BlockOpen                   = 8,
    BlockPlace                  = 9,
    ContainerClose              = 10,
    ContainerOpen               = 11,
    DispenseFail                = 12,
    Drink                       = 13,
    Eat                         = 14,
    ElytraGlide                 = 15,
    EntityDamage                = 16,
    EntityDie                   = 17,
    EntityDismount              = 18,
    EntityInteract              = 19,
    EntityMount                 = 20,
    EntityMove                  = 21,
    EntityPlace                 = 22,
    EntityRoar                  = 23,
    EntityAct                   = 24,
    Equip                       = 25,
    Explode                     = 26,
    Flap                        = 27,
    FluidPickup                 = 28,
    FluidPlace                  = 29,
    HitGround                   = 30,
    ItemInteractFinish          = 31,
    ItemInteractStart           = 32,
    LightningStrike             = 33,
    NoteBlockPlay               = 34,
    PistonContract              = 35,
    PistonExtend                = 36,
    PrimeFuse                   = 37,
    ProjectileLand              = 38,
    ProjectileShoot             = 39,
    Resonate1                   = 40,
    Resonate2                   = 41,
    Resonate3                   = 42,
    Resonate4                   = 43,
    Resonate5                   = 44,
    Resonate6                   = 45,
    Resonate7                   = 46,
    Resonate8                   = 47,
    Resonate9                   = 48,
    Resonate10                  = 49,
    Resonate11                  = 50,
    Resonate12                  = 51,
    Resonate13                  = 52,
    Resonate14                  = 53,
    Resonate15                  = 54,
    SculkTouch                  = 55,
    SculkSensorTendrilsClicking = 56,
    Shear                       = 57,
    Shriek                      = 58,
    Splash                      = 59,
    Swim                        = 60,
    Teleport                    = 61,
    Unequip                     = 62,
    Count                       = 63,
};

}
