#pragma once

#include "mc/_HeaderOutputPredefine.h"

enum class CompoundType : uchar {
    Salt = 0,
    SodiumOxide = 1,
    SodiumHydroxide = 2,
    MagnesiumNitrate = 3,
    IronSulfide = 4,
    LithiumHydride = 5,
    SodiumHydride = 6,
    CalciumBromide = 7,
    MagnesiumOxide = 8,
    SodiumAcetate = 9,
    Luminol = 10,
    Charcoal = 11,
    Sugar = 12,
    AluminumOxide = 13,
    BoronTrioxide = 14,
    Soap = 15,
    Polyethylene = 16,
    Garbage = 17,
    MagnesiumSalts = 18,
    Sulfate = 19,
    BariumSulfate = 20,
    PotassiumChloride = 21,
    MercuricChloride = 22,
    CeriumChloride = 23,
    TungstenChloride = 24,
    CalciumChloride = 25,
    Water = 26,
    Glue = 27,
    Hypochlorite = 28,
    CrudeOil = 29,
    Latex = 30,
    PotassiumIodide = 31,
    SodiumFluoride = 32,
    Benzene = 33,
    Ink = 34,
    HydrogenPeroxide = 35,
    Ammonia = 36,
    SodiumHypochlorite = 37,
    Invalid = 38,
};
