/**
 * @file  ChargeableItemComponent.hpp
 * @note  This Header is auto generated by LiteLoaderBDS Toolchain.
 *
 */
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

/**
 * @brief MC class ChargeableItemComponent.
 *
 */
class ChargeableItemComponent {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_CHARGEABLEITEMCOMPONENT
public:
    class ChargeableItemComponent& operator=(class ChargeableItemComponent const &) = delete;
    ChargeableItemComponent(class ChargeableItemComponent const &) = delete;
    ChargeableItemComponent() = delete;
#endif

public:
    /**
     * @vftbl  0
     * @hash   1266614282
     */
    virtual ~ChargeableItemComponent();
    /**
     * @vftbl  1
     * @symbol ?isNetworkComponent@ChargeableItemComponent@@UEBA_NXZ
     * @hash   155367061
     */
    virtual bool isNetworkComponent() const;
    /**
     * @vftbl  2
     * @hash   -1365271070
     */
    virtual void __unk_vfn_2();
    /**
     * @vftbl  3
     * @hash   -1357612861
     */
    virtual void __unk_vfn_3();
    /**
     * @vftbl  4
     * @hash   -1405708028
     */
    virtual void __unk_vfn_4();
    /**
     * @vftbl  5
     * @symbol ?buildNetworkTag@ChargeableItemComponent@@UEBA?AV?$unique_ptr@VCompoundTag@@U?$default_delete@VCompoundTag@@@std@@@std@@XZ
     * @hash   319239591
     */
    virtual std::unique_ptr<class CompoundTag> buildNetworkTag() const;
    /**
     * @vftbl  6
     * @symbol ?initializeFromNetwork@ChargeableItemComponent@@UEAA_NAEBVCompoundTag@@@Z
     * @hash   -463860119
     */
    virtual bool initializeFromNetwork(class CompoundTag const &);
    /**
     * @symbol ?getMovementModifier@ChargeableItemComponent@@QEBAMXZ
     * @hash   -287287730
     */
    MCAPI float getMovementModifier() const;
    /**
     * @symbol ?use@ChargeableItemComponent@@QEBA_NAEAVItemStack@@AEAVPlayer@@@Z
     * @hash   -1979731160
     */
    MCAPI bool use(class ItemStack &, class Player &) const;
    /**
     * @symbol ?useTimeDepleted@ChargeableItemComponent@@QEBAXAEAVItemStack@@AEAVPlayer@@AEAVLevel@@@Z
     * @hash   -1551673554
     */
    MCAPI void useTimeDepleted(class ItemStack &, class Player &, class Level &) const;
    /**
     * @symbol ?bindType@ChargeableItemComponent@@SAXXZ
     * @hash   -697614673
     */
    MCAPI static void bindType();
    /**
     * @symbol ?getIdentifier@ChargeableItemComponent@@SAAEBVHashedString@@XZ
     * @hash   2122313440
     */
    MCAPI static class HashedString const & getIdentifier();

};