#pragma once

#include "mc/_HeaderOutputPredefine.h"

enum class MobEffectIds : uint {
    Empty               = 0,
    MovementSpeed       = 1,
    MovementSlowdown    = 2,
    DigSpeed            = 3,
    DigSlowdown         = 4,
    DamageBoost         = 5,
    Heal                = 6,
    Harm                = 7,
    Jump                = 8,
    Confusion           = 9,
    Regeneration        = 10,
    DamageResistance    = 11,
    FireResistance      = 12,
    WaterBreathing      = 13,
    Invisibility        = 14,
    Blindness           = 15,
    NightVision         = 16,
    Hunger              = 17,
    Weakness            = 18,
    Poison              = 19,
    Wither              = 20,
    HealthBoost         = 21,
    Absorption          = 22,
    Saturation          = 23,
    Levitation          = 24,
    FatalPoison         = 25,
    ConduitPower        = 26,
    SlowFalling         = 27,
    BadOmen             = 28,
    VillageHero         = 29,
    Darkness            = 30,
    TrialOmen           = 31,
    WindCharged         = 32,
    Weaving             = 33,
    Oozing              = 34,
    Infested            = 35,
    RaidOmen            = 36,
    BreathOfTheNautilus = 37,
    Count               = 38,
};
