#pragma once

#include "mc/_HeaderOutputPredefine.h"

enum class BlockProperty : uint64 {
    None                         = 0,
    Stair                        = 1ull << 0,
    HalfSlab                     = 1ull << 1,
    Hopper                       = 1ull << 2,
    TopSnow                      = 1ull << 3,
    FenceGate                    = 1ull << 4,
    Leaf                         = 1ull << 5,
    ThinConnects2D               = 1ull << 6,
    Connects2D                   = 1ull << 7,
    Carpet                       = 1ull << 8,
    Button                       = 1ull << 9,
    Door                         = 1ull << 10,
    Portal                       = 1ull << 11,
    Heavy                        = 1ull << 12,
    Snow                         = 1ull << 13,
    Trap                         = 1ull << 14,
    Sign                         = 1ull << 15,
    Walkable                     = 1ull << 16,
    PressurePlate                = 1ull << 17,
    PistonBlockGrabber           = 1ull << 18,
    TopSolidBlocking             = 1ull << 19,
    SolidBlocking                = 1ull << 20,
    CubeShaped                   = 1ull << 21,
    Power_NO                     = 1ull << 22,
    Power_BlockDown              = 1ull << 23,
    Immovable                    = 1ull << 24,
    BreakOnPush                  = 1ull << 25,
    Piston                       = 1ull << 26,
    InfiniBurn                   = 1ull << 27,
    RequiresWorldBuilder         = 1ull << 28,
    CausesDamage                 = 1ull << 29,
    BreaksWhenFallenOnByHeavy    = 1ull << 30,
    OnlyPistonPush               = 1ull << 31,
    Liquid                       = 1ull << 32,
    CanBeBuiltOver               = 1ull << 33,
    SnowRecoverable              = 1ull << 34,
    Scaffolding                  = 1ull << 35,
    CanSupportCenterHangingBlock = 1ull << 36,
    BreaksWhenHitByArrow         = 1ull << 37,
    Unwalkable                   = 1ull << 38,
    UNUSED                       = 1ull << 39,
    Hollow                       = 1ull << 40,
    OperatorBlock                = 1ull << 41,
    SupportedByFlowerPot         = 1ull << 42,
    PreventsJumping              = 1ull << 43,
    ContainsHoney                = 1ull << 44,
    Slime                        = 1ull << 45,
    SculkReplaceable             = 1ull << 46,
    Climbable                    = 1ull << 47,
    CanHaltWhenClimbing          = 1ull << 48,
};
