#pragma once

#include "mc/_HeaderOutputPredefine.h"

enum class BlockActorType : int {
    Undefined             = 0x0,
    Furnace               = 0x1,
    Chest                 = 0x2,
    NetherReactor         = 0x3,
    Sign                  = 0x4,
    MobSpawner            = 0x5,
    Skull                 = 0x6,
    FlowerPot             = 0x7,
    BrewingStand          = 0x8,
    EnchantingTable       = 0x9,
    DaylightDetector      = 0xA,
    Music                 = 0xB,
    Comparator            = 0xC,
    Dispenser             = 0xD,
    Dropper               = 0xE,
    Hopper                = 0xF,
    Cauldron              = 0x10,
    ItemFrame             = 0x11,
    PistonArm             = 0x12,
    MovingBlock           = 0x13,
    Chalkboard            = 0x14,
    Beacon                = 0x15,
    EndPortal             = 0x16,
    EnderChest            = 0x17,
    EndGateway            = 0x18,
    ShulkerBox            = 0x19,
    CommandBlock          = 0x1A,
    Bed                   = 0x1B,
    Banner                = 0x1C,
    StructureBlock        = 0x20,
    Jukebox               = 0x21,
    ChemistryTable        = 0x22,
    Conduit               = 0x23,
    JigsawBlock           = 0x24,
    Lectern               = 0x25,
    BlastFurnace          = 0x26,
    Smoker                = 0x27,
    Bell                  = 0x28,
    Campfire              = 0x29,
    BarrelBlock           = 0x2A,
    Beehive               = 0x2B,
    Lodestone             = 0x2C,
    SculkSensor           = 0x2D,
    SporeBlossom          = 0x2E,
    GlowItemFrame         = 0x2F,
    SculkCatalyst         = 0x30,
    SculkShrieker         = 0x31,
    HangingSign           = 0x32,
    ChiseledBookshelf     = 0x33,
    BrushableBlock        = 0x34,
    DecoratedPot          = 0x35,
    CalibratedSculkSensor = 0x36,
    Count                 = 0x37,
};
