#include "mc/world/level/block/utils/StaticVanillaBlocks.h"
#include "liteloader/api/memory/Hook.h"
#include "mc/world/level/block/registry/BlockTypeRegistry.h"
#include "mc/world/level/block/utils/VanillaBlockTypeIds.h"

namespace StaticVanillaBlocks {

std::array<class Block const*, 119> mElements{};

class Block const* mAcaciaButton;
class Block const* mAcaciaDoor;
class Block const* mAcaciaFence;
class Block const* mAcaciaFenceGate;
class Block const* mAcaciaHangingSign;
class Block const* mAcaciaLog;
class Block const* mAcaciaPressurePlate;
class Block const* mAcaciaStairs;
class Block const* mAcaciaStandingSign;
class Block const* mAcaciaTrapdoor;
class Block const* mAcaciaWallSign;
class Block const* mActivatorRail;
class Block const* mAllow;
class Block const* mAmethystBlock;
class Block const* mAmethystCluster;
class Block const* mAncientDebris;
class Block const* mAndesiteStairs;
class Block const* mAnvil;
class Block const* mAzalea;
class Block const* mAzaleaLeaves;
class Block const* mAzaleaLeavesFlowered;
class Block const* mBamboo;
class Block const* mBambooBlock;
class Block const* mBambooButton;
class Block const* mBambooDoor;
class Block const* mBambooDoubleSlab;
class Block const* mBambooFence;
class Block const* mBambooFenceGate;
class Block const* mBambooHangingSign;
class Block const* mBambooMosaic;
class Block const* mBambooMosaicDoubleSlab;
class Block const* mBambooMosaicSlab;
class Block const* mBambooMosaicStairs;
class Block const* mBambooPlanks;
class Block const* mBambooPressurePlate;
class Block const* mBambooSapling;
class Block const* mBambooSlab;
class Block const* mBambooStairs;
class Block const* mBambooStandingSign;
class Block const* mBambooTrapdoor;
class Block const* mBambooWallSign;
class Block const* mBarrel;
class Block const* mBarrier;
class Block const* mBasalt;
class Block const* mBeacon;
class Block const* mBed;
class Block const* mBedrock;
class Block const* mBeeNest;
class Block const* mBeehive;
class Block const* mBeetroot;
class Block const* mBell;
class Block const* mBigDripleaf;
class Block const* mBirchButton;
class Block const* mBirchDoor;
class Block const* mBirchFence;
class Block const* mBirchFenceGate;
class Block const* mBirchHangingSign;
class Block const* mBirchLog;
class Block const* mBirchPressurePlate;
class Block const* mBirchStairs;
class Block const* mBirchStandingSign;
class Block const* mBirchTrapdoor;
class Block const* mBirchWallSign;
class Block const* mBlackCandle;
class Block const* mBlackCandleCake;
class Block const* mBlackCarpet;
class Block const* mBlackConcrete;
class Block const* mBlackGlazedTerracotta;
class Block const* mBlackShulkerBox;
class Block const* mBlackWool;
class Block const* mBlackstone;
class Block const* mBlackstoneDoubleSlab;
class Block const* mBlackstoneSlab;
class Block const* mBlackstoneStairs;
class Block const* mBlackstoneWall;
class Block const* mBlastFurnace;
class Block const* mBlueCandle;
class Block const* mBlueCandleCake;
class Block const* mBlueCarpet;
class Block const* mBlueConcrete;
class Block const* mBlueGlazedTerracotta;
class Block const* mBlueIce;
class Block const* mBlueShulkerBox;
class Block const* mBlueWool;
class Block const* mBoneBlock;
class Block const* mBookshelf;
class Block const* mBorderBlock;
class Block const* mBrainCoral;
class Block const* mBrewingStand;
class Block const* mBrickBlock;
class Block const* mBrickStairs;
class Block const* mBrownCandle;
class Block const* mBrownCandleCake;
class Block const* mBrownCarpet;
class Block const* mBrownConcrete;
class Block const* mBrownGlazedTerracotta;
class Block const* mBrownMushroom;
class Block const* mBrownMushroomBlock;
class Block const* mBrownShulkerBox;
class Block const* mBrownWool;
class Block const* mBubbleColumn;
class Block const* mBubbleCoral;
class Block const* mBuddingAmethyst;
class Block const* mCactus;
class Block const* mCake;
class Block const* mCalcite;
class Block const* mCalibratedSculkSensor;
class Block const* mCamera;
class Block const* mCampFire;
class Block const* mCandle;
class Block const* mCandleCake;
class Block const* mCarrots;
class Block const* mCartographyTable;
class Block const* mCarvedPumpkin;
class Block const* mCauldron;
class Block const* mCaveVines;
class Block const* mCaveVinesBodyWithBerries;
class Block const* mCaveVinesHeadWithBerries;
class Block const* mChain;
class Block const* mChainCommandBlock;
class Block const* mChalkboard;
class Block const* mChemicalHeat;
class Block const* mChemistryTable;
class Block const* mCherryButton;
class Block const* mCherryDoor;
class Block const* mCherryDoubleSlab;
class Block const* mCherryFence;
class Block const* mCherryFenceGate;
class Block const* mCherryHangingSign;
class Block const* mCherryLeaves;
class Block const* mCherryLog;
class Block const* mCherryPlanks;
class Block const* mCherryPressurePlate;
class Block const* mCherrySapling;
class Block const* mCherrySlab;
class Block const* mCherryStairs;
class Block const* mCherryStandingSign;
class Block const* mCherryTrapdoor;
class Block const* mCherryWallSign;
class Block const* mCherryWood;
class Block const* mChest;
class Block const* mChiseledBookshelf;
class Block const* mChiseledDeepslate;
class Block const* mChiseledNetherBricks;
class Block const* mChiseledPolishedBlackstone;
class Block const* mChorusFlower;
class Block const* mChorusPlant;
class Block const* mClay;
class Block const* mClientRequestPlaceholderBlock;
class Block const* mCoalBlock;
class Block const* mCoalOre;
class Block const* mCobbledDeepslate;
class Block const* mCobbledDeepslateDoubleSlab;
class Block const* mCobbledDeepslateSlab;
class Block const* mCobbledDeepslateStairs;
class Block const* mCobbledDeepslateWall;
class Block const* mCobblestone;
class Block const* mCobblestoneWall;
class Block const* mCocoa;
class Block const* mColoredTorchBp;
class Block const* mColoredTorchRg;
class Block const* mCommandBlock;
class Block const* mComposter;
class Block const* mConcretePowder;
class Block const* mConduit;
class Block const* mCopperBlock;
class Block const* mCopperOre;
class Block const* mCoralBlock;
class Block const* mCoralFan;
class Block const* mCoralFanDead;
class Block const* mCoralFanHang;
class Block const* mCoralFanHang2;
class Block const* mCoralFanHang3;
class Block const* mCrackedDeepslateBricks;
class Block const* mCrackedDeepslateTiles;
class Block const* mCrackedNetherBricks;
class Block const* mCrackedPolishedBlackstoneBricks;
class Block const* mCraftingTable;
class Block const* mCrimsonButton;
class Block const* mCrimsonDoor;
class Block const* mCrimsonDoubleSlab;
class Block const* mCrimsonFence;
class Block const* mCrimsonFenceGate;
class Block const* mCrimsonFungus;
class Block const* mCrimsonHangingSign;
class Block const* mCrimsonHyphae;
class Block const* mCrimsonNylium;
class Block const* mCrimsonPlanks;
class Block const* mCrimsonPressurePlate;
class Block const* mCrimsonRoots;
class Block const* mCrimsonSlab;
class Block const* mCrimsonStairs;
class Block const* mCrimsonStandingSign;
class Block const* mCrimsonStem;
class Block const* mCrimsonTrapdoor;
class Block const* mCrimsonWallSign;
class Block const* mCryingObsidian;
class Block const* mCutCopper;
class Block const* mCutCopperSlab;
class Block const* mCutCopperStairs;
class Block const* mCyanCandle;
class Block const* mCyanCandleCake;
class Block const* mCyanCarpet;
class Block const* mCyanConcrete;
class Block const* mCyanGlazedTerracotta;
class Block const* mCyanShulkerBox;
class Block const* mCyanWool;
class Block const* mDarkOakButton;
class Block const* mDarkOakDoor;
class Block const* mDarkOakFence;
class Block const* mDarkOakFenceGate;
class Block const* mDarkOakLog;
class Block const* mDarkOakPressurePlate;
class Block const* mDarkOakStairs;
class Block const* mDarkOakTrapdoor;
class Block const* mDarkPrismarineStairs;
class Block const* mDarkoakHangingSign;
class Block const* mDarkoakStandingSign;
class Block const* mDarkoakWallSign;
class Block const* mDaylightDetector;
class Block const* mDaylightDetectorInverted;
class Block const* mDeadBrainCoral;
class Block const* mDeadBubbleCoral;
class Block const* mDeadFireCoral;
class Block const* mDeadHornCoral;
class Block const* mDeadTubeCoral;
class Block const* mDeadbush;
class Block const* mDecoratedPot;
class Block const* mDeepslate;
class Block const* mDeepslateBrickDoubleSlab;
class Block const* mDeepslateBrickSlab;
class Block const* mDeepslateBrickStairs;
class Block const* mDeepslateBrickWall;
class Block const* mDeepslateBricks;
class Block const* mDeepslateCoalOre;
class Block const* mDeepslateCopperOre;
class Block const* mDeepslateDiamondOre;
class Block const* mDeepslateEmeraldOre;
class Block const* mDeepslateGoldOre;
class Block const* mDeepslateIronOre;
class Block const* mDeepslateLapisOre;
class Block const* mDeepslateRedstoneOre;
class Block const* mDeepslateTileDoubleSlab;
class Block const* mDeepslateTileSlab;
class Block const* mDeepslateTileStairs;
class Block const* mDeepslateTileWall;
class Block const* mDeepslateTiles;
class Block const* mDeny;
class Block const* mDetectorRail;
class Block const* mDiamondBlock;
class Block const* mDiamondOre;
class Block const* mDioriteStairs;
class Block const* mDirt;
class Block const* mDirtWithRoots;
class Block const* mDispenser;
class Block const* mDoubleCutCopperSlab;
class Block const* mDoublePlant;
class Block const* mDoubleStoneSlab;
class Block const* mDoubleStoneSlab2;
class Block const* mDoubleStoneSlab3;
class Block const* mDoubleStoneSlab4;
class Block const* mDoubleWoodenSlab;
class Block const* mDragonEgg;
class Block const* mDriedKelpBlock;
class Block const* mDripstone;
class Block const* mDropper;
class Block const* mEmeraldBlock;
class Block const* mEmeraldOre;
class Block const* mEnchantingTable;
class Block const* mEndBrickStairs;
class Block const* mEndBricks;
class Block const* mEndGateway;
class Block const* mEndPortal;
class Block const* mEndPortalFrame;
class Block const* mEndRod;
class Block const* mEndStone;
class Block const* mEnderChest;
class Block const* mExposedCopper;
class Block const* mExposedCutCopper;
class Block const* mExposedCutCopperSlab;
class Block const* mExposedCutCopperStairs;
class Block const* mExposedDoubleCutCopperSlab;
class Block const* mFarmlandBlock;
class Block const* mFenceGate;
class Block const* mFire;
class Block const* mFireCoral;
class Block const* mFletchingTable;
class Block const* mFlowerPot;
class Block const* mFloweringAzalea;
class Block const* mFlowingLava;
class Block const* mFlowingWater;
class Block const* mFrogSpawn;
class Block const* mFrostedIce;
class Block const* mFurnace;
class Block const* mGildedBlackstone;
class Block const* mGlass;
class Block const* mGlassPane;
class Block const* mGlowItemFrame;
class Block const* mGlowLichen;
class Block const* mGlowingObsidian;
class Block const* mGlowstone;
class Block const* mGoldBlock;
class Block const* mGoldOre;
class Block const* mGoldenRail;
class Block const* mGraniteStairs;
class Block const* mGrass;
class Block const* mGrassPath;
class Block const* mGravel;
class Block const* mGrayCandle;
class Block const* mGrayCandleCake;
class Block const* mGrayCarpet;
class Block const* mGrayConcrete;
class Block const* mGrayGlazedTerracotta;
class Block const* mGrayShulkerBox;
class Block const* mGrayWool;
class Block const* mGreenCandle;
class Block const* mGreenCandleCake;
class Block const* mGreenCarpet;
class Block const* mGreenConcrete;
class Block const* mGreenGlazedTerracotta;
class Block const* mGreenShulkerBox;
class Block const* mGreenWool;
class Block const* mGrindstone;
class Block const* mHangingRoots;
class Block const* mHardGlass;
class Block const* mHardGlassPane;
class Block const* mHardStainedGlass;
class Block const* mHardStainedGlassPane;
class Block const* mHardenedClay;
class Block const* mHayBlock;
class Block const* mHeavyWeightedPressurePlate;
class Block const* mHoneyBlock;
class Block const* mHoneycombBlock;
class Block const* mHopper;
class Block const* mHornCoral;
class Block const* mIce;
class Block const* mInfestedDeepslate;
class Block const* mInfoUpdate;
class Block const* mInfoUpdate2;
class Block const* mInvisibleBedrock;
class Block const* mIronBars;
class Block const* mIronBlock;
class Block const* mIronDoor;
class Block const* mIronOre;
class Block const* mIronTrapdoor;
class Block const* mItemFrame;
class Block const* mJigsaw;
class Block const* mJukebox;
class Block const* mJungleButton;
class Block const* mJungleDoor;
class Block const* mJungleFence;
class Block const* mJungleFenceGate;
class Block const* mJungleHangingSign;
class Block const* mJungleLog;
class Block const* mJunglePressurePlate;
class Block const* mJungleStairs;
class Block const* mJungleStandingSign;
class Block const* mJungleTrapdoor;
class Block const* mJungleWallSign;
class Block const* mKelp;
class Block const* mLadder;
class Block const* mLantern;
class Block const* mLapisBlock;
class Block const* mLapisOre;
class Block const* mLargeAmethystBud;
class Block const* mLava;
class Block const* mLeaves;
class Block const* mLeaves2;
class Block const* mLectern;
class Block const* mLever;
class Block const* mLightBlock;
class Block const* mLightBlueCandle;
class Block const* mLightBlueCandleCake;
class Block const* mLightBlueCarpet;
class Block const* mLightBlueConcrete;
class Block const* mLightBlueGlazedTerracotta;
class Block const* mLightBlueShulkerBox;
class Block const* mLightBlueWool;
class Block const* mLightGrayCandle;
class Block const* mLightGrayCandleCake;
class Block const* mLightGrayCarpet;
class Block const* mLightGrayConcrete;
class Block const* mLightGrayShulkerBox;
class Block const* mLightGrayWool;
class Block const* mLightWeightedPressurePlate;
class Block const* mLightningRod;
class Block const* mLimeCandle;
class Block const* mLimeCandleCake;
class Block const* mLimeCarpet;
class Block const* mLimeConcrete;
class Block const* mLimeGlazedTerracotta;
class Block const* mLimeShulkerBox;
class Block const* mLimeWool;
class Block const* mLitBlastFurnace;
class Block const* mLitDeepslateRedstoneOre;
class Block const* mLitFurnace;
class Block const* mLitPumpkin;
class Block const* mLitRedstoneLamp;
class Block const* mLitRedstoneOre;
class Block const* mLitSmoker;
class Block const* mLodestone;
class Block const* mLoom;
class Block const* mMagentaCandle;
class Block const* mMagentaCandleCake;
class Block const* mMagentaCarpet;
class Block const* mMagentaConcrete;
class Block const* mMagentaGlazedTerracotta;
class Block const* mMagentaShulkerBox;
class Block const* mMagentaWool;
class Block const* mMagma;
class Block const* mMangroveButton;
class Block const* mMangroveDoor;
class Block const* mMangroveDoubleSlab;
class Block const* mMangroveFence;
class Block const* mMangroveFenceGate;
class Block const* mMangroveHangingSign;
class Block const* mMangroveLeaves;
class Block const* mMangroveLog;
class Block const* mMangrovePlanks;
class Block const* mMangrovePressurePlate;
class Block const* mMangrovePropagule;
class Block const* mMangroveRoots;
class Block const* mMangroveSlab;
class Block const* mMangroveStairs;
class Block const* mMangroveStandingSign;
class Block const* mMangroveTrapdoor;
class Block const* mMangroveWallSign;
class Block const* mMangroveWood;
class Block const* mMediumAmethystBud;
class Block const* mMelonBlock;
class Block const* mMelonStem;
class Block const* mMobSpawner;
class Block const* mMonsterEgg;
class Block const* mMossBlock;
class Block const* mMossCarpet;
class Block const* mMossyCobblestone;
class Block const* mMossyCobblestoneStairs;
class Block const* mMossyStoneBrickStairs;
class Block const* mMovingBlock;
class Block const* mMud;
class Block const* mMudBrickDoubleSlab;
class Block const* mMudBrickSlab;
class Block const* mMudBrickStairs;
class Block const* mMudBrickWall;
class Block const* mMudBricks;
class Block const* mMuddyMangroveRoots;
class Block const* mMycelium;
class Block const* mMysteriousFrame;
class Block const* mMysteriousFrameSlot;
class Block const* mNetherBrickBlockName;
class Block const* mNetherBrickFence;
class Block const* mNetherBrickStairs;
class Block const* mNetherGoldOre;
class Block const* mNetherSprouts;
class Block const* mNetherWart;
class Block const* mNetherWartBlock;
class Block const* mNetheriteBlock;
class Block const* mNetherrack;
class Block const* mNetherreactor;
class Block const* mNormalStoneStairs;
class Block const* mNoteblock;
class Block const* mOakFence;
class Block const* mOakHangingSign;
class Block const* mOakLog;
class Block const* mOakStairs;
class Block const* mObserver;
class Block const* mObsidian;
class Block const* mOchreFroglight;
class Block const* mOrangeCandle;
class Block const* mOrangeCandleCake;
class Block const* mOrangeCarpet;
class Block const* mOrangeConcrete;
class Block const* mOrangeGlazedTerracotta;
class Block const* mOrangeShulkerBox;
class Block const* mOrangeWool;
class Block const* mOxidizedCopper;
class Block const* mOxidizedCutCopper;
class Block const* mOxidizedCutCopperSlab;
class Block const* mOxidizedCutCopperStairs;
class Block const* mOxidizedDoubleCutCopperSlab;
class Block const* mPackedIce;
class Block const* mPackedMud;
class Block const* mPearlescentFroglight;
class Block const* mPinkCandle;
class Block const* mPinkCandleCake;
class Block const* mPinkCarpet;
class Block const* mPinkConcrete;
class Block const* mPinkGlazedTerracotta;
class Block const* mPinkPetals;
class Block const* mPinkShulkerBox;
class Block const* mPinkWool;
class Block const* mPiston;
class Block const* mPistonArmCollision;
class Block const* mPitcherCrop;
class Block const* mPitcherPlant;
class Block const* mPlanks;
class Block const* mPodzol;
class Block const* mPointedDripstone;
class Block const* mPolishedAndesiteStairs;
class Block const* mPolishedBasalt;
class Block const* mPolishedBlackstone;
class Block const* mPolishedBlackstoneBrickDoubleSlab;
class Block const* mPolishedBlackstoneBrickSlab;
class Block const* mPolishedBlackstoneBrickStairs;
class Block const* mPolishedBlackstoneBrickWall;
class Block const* mPolishedBlackstoneBricks;
class Block const* mPolishedBlackstoneButton;
class Block const* mPolishedBlackstoneDoubleSlab;
class Block const* mPolishedBlackstonePressurePlate;
class Block const* mPolishedBlackstoneSlab;
class Block const* mPolishedBlackstoneStairs;
class Block const* mPolishedBlackstoneWall;
class Block const* mPolishedDeepslate;
class Block const* mPolishedDeepslateDoubleSlab;
class Block const* mPolishedDeepslateSlab;
class Block const* mPolishedDeepslateStairs;
class Block const* mPolishedDeepslateWall;
class Block const* mPolishedDioriteStairs;
class Block const* mPolishedGraniteStairs;
class Block const* mPortal;
class Block const* mPotatoes;
class Block const* mPowderSnow;
class Block const* mPoweredComparator;
class Block const* mPoweredRepeater;
class Block const* mPrismarine;
class Block const* mPrismarineBricksStairs;
class Block const* mPrismarineStairs;
class Block const* mPumpkin;
class Block const* mPumpkinStem;
class Block const* mPurpleCandle;
class Block const* mPurpleCandleCake;
class Block const* mPurpleCarpet;
class Block const* mPurpleConcrete;
class Block const* mPurpleGlazedTerracotta;
class Block const* mPurpleShulkerBox;
class Block const* mPurpleWool;
class Block const* mPurpurBlock;
class Block const* mPurpurStairs;
class Block const* mQuartzBlock;
class Block const* mQuartzBricks;
class Block const* mQuartzOre;
class Block const* mQuartzStairs;
class Block const* mRail;
class Block const* mRawCopperBlock;
class Block const* mRawGoldBlock;
class Block const* mRawIronBlock;
class Block const* mRedCandle;
class Block const* mRedCandleCake;
class Block const* mRedCarpet;
class Block const* mRedConcrete;
class Block const* mRedFlower;
class Block const* mRedGlazedTerracotta;
class Block const* mRedMushroom;
class Block const* mRedMushroomBlock;
class Block const* mRedNetherBrick;
class Block const* mRedNetherBrickStairs;
class Block const* mRedSandstone;
class Block const* mRedSandstoneStairs;
class Block const* mRedShulkerBox;
class Block const* mRedWool;
class Block const* mRedstoneBlock;
class Block const* mRedstoneLamp;
class Block const* mRedstoneOre;
class Block const* mRedstoneTorch;
class Block const* mRedstoneWire;
class Block const* mReeds;
class Block const* mReinforcedDeepslate;
class Block const* mRepeatingCommandBlock;
class Block const* mReserved6;
class Block const* mRespawnAnchor;
class Block const* mSand;
class Block const* mSandstone;
class Block const* mSandstoneStairs;
class Block const* mSapling;
class Block const* mScaffolding;
class Block const* mSculk;
class Block const* mSculkCatalyst;
class Block const* mSculkSensor;
class Block const* mSculkShrieker;
class Block const* mSculkVein;
class Block const* mSeaLantern;
class Block const* mSeaPickle;
class Block const* mSeagrass;
class Block const* mShroomlight;
class Block const* mSilverGlazedTerracotta;
class Block const* mSkull;
class Block const* mSlimeBlock;
class Block const* mSmallAmethystBud;
class Block const* mSmallDripleaf;
class Block const* mSmithingTable;
class Block const* mSmoker;
class Block const* mSmoothBasalt;
class Block const* mSmoothQuartzStairs;
class Block const* mSmoothRedSandstoneStairs;
class Block const* mSmoothSandstoneStairs;
class Block const* mSmoothStone;
class Block const* mSnifferEgg;
class Block const* mSnow;
class Block const* mSnowLayer;
class Block const* mSoulCampfire;
class Block const* mSoulFire;
class Block const* mSoulLantern;
class Block const* mSoulSand;
class Block const* mSoulSoil;
class Block const* mSoulTorch;
class Block const* mSponge;
class Block const* mSporeBlossom;
class Block const* mSpruceButton;
class Block const* mSpruceDoor;
class Block const* mSpruceFence;
class Block const* mSpruceFenceGate;
class Block const* mSpruceHangingSign;
class Block const* mSpruceLog;
class Block const* mSprucePressurePlate;
class Block const* mSpruceStairs;
class Block const* mSpruceStandingSign;
class Block const* mSpruceTrapdoor;
class Block const* mSpruceWallSign;
class Block const* mStainedGlass;
class Block const* mStainedGlassPane;
class Block const* mStainedHardenedClay;
class Block const* mStandingBanner;
class Block const* mStandingSign;
class Block const* mStickyPiston;
class Block const* mStickyPistonArmCollision;
class Block const* mStone;
class Block const* mStoneBrickStairs;
class Block const* mStoneBricks;
class Block const* mStoneButton;
class Block const* mStonePressurePlate;
class Block const* mStoneSlab;
class Block const* mStoneSlab2;
class Block const* mStoneSlab3;
class Block const* mStoneSlab4;
class Block const* mStoneStairs;
class Block const* mStonecutter;
class Block const* mStonecutterBlock;
class Block const* mStrippedAcaciaLog;
class Block const* mStrippedBambooBlock;
class Block const* mStrippedBirchLog;
class Block const* mStrippedCherryLog;
class Block const* mStrippedCherryWood;
class Block const* mStrippedCrimsonHyphae;
class Block const* mStrippedCrimsonStem;
class Block const* mStrippedDarkOakLog;
class Block const* mStrippedJungleLog;
class Block const* mStrippedMangroveLog;
class Block const* mStrippedMangroveWood;
class Block const* mStrippedOakLog;
class Block const* mStrippedSpruceLog;
class Block const* mStrippedWarpedHyphae;
class Block const* mStrippedWarpedStem;
class Block const* mStructureBlock;
class Block const* mStructureVoid;
class Block const* mSuspiciousGravel;
class Block const* mSuspiciousSand;
class Block const* mSweetBerryBush;
class Block const* mTallGrass;
class Block const* mTarget;
class Block const* mTintedGlass;
class Block const* mTnt;
class Block const* mTorch;
class Block const* mTorchflower;
class Block const* mTorchflowerCrop;
class Block const* mTrapdoor;
class Block const* mTrappedChest;
class Block const* mTripWire;
class Block const* mTripWireHook;
class Block const* mTubeCoral;
class Block const* mTuff;
class Block const* mTurtleEgg;
class Block const* mTwistingVines;
class Block const* mUnderwaterTorch;
class Block const* mUndyedShulkerBox;
class Block const* mUnlitRedstoneTorch;
class Block const* mUnpoweredComparator;
class Block const* mUnpoweredRepeater;
class Block const* mVerdantFroglight;
class Block const* mVine;
class Block const* mWallBanner;
class Block const* mWallSign;
class Block const* mWarpedButton;
class Block const* mWarpedDoor;
class Block const* mWarpedDoubleSlab;
class Block const* mWarpedFence;
class Block const* mWarpedFenceGate;
class Block const* mWarpedFungus;
class Block const* mWarpedHangingSign;
class Block const* mWarpedHyphae;
class Block const* mWarpedNylium;
class Block const* mWarpedPlanks;
class Block const* mWarpedPressurePlate;
class Block const* mWarpedRoots;
class Block const* mWarpedSlab;
class Block const* mWarpedStairs;
class Block const* mWarpedStandingSign;
class Block const* mWarpedStem;
class Block const* mWarpedTrapdoor;
class Block const* mWarpedWallSign;
class Block const* mWarpedWartBlock;
class Block const* mWater;
class Block const* mWaterLily;
class Block const* mWaxedCopper;
class Block const* mWaxedCutCopper;
class Block const* mWaxedCutCopperSlab;
class Block const* mWaxedCutCopperStairs;
class Block const* mWaxedDoubleCutCopperSlab;
class Block const* mWaxedExposedCopper;
class Block const* mWaxedExposedCutCopper;
class Block const* mWaxedExposedCutCopperSlab;
class Block const* mWaxedExposedCutCopperStairs;
class Block const* mWaxedExposedDoubleCutCopperSlab;
class Block const* mWaxedOxidizedCopper;
class Block const* mWaxedOxidizedCutCopper;
class Block const* mWaxedOxidizedCutCopperSlab;
class Block const* mWaxedOxidizedCutCopperStairs;
class Block const* mWaxedOxidizedDoubleCutCopperSlab;
class Block const* mWaxedWeatheredCopper;
class Block const* mWaxedWeatheredCutCopper;
class Block const* mWaxedWeatheredCutCopperSlab;
class Block const* mWaxedWeatheredCutCopperStairs;
class Block const* mWaxedWeatheredDoubleCutCopperSlab;
class Block const* mWeatheredCopper;
class Block const* mWeatheredCutCopper;
class Block const* mWeatheredCutCopperSlab;
class Block const* mWeatheredCutCopperStairs;
class Block const* mWeatheredDoubleCutCopperSlab;
class Block const* mWeb;
class Block const* mWeepingVines;
class Block const* mWheat;
class Block const* mWhiteCandle;
class Block const* mWhiteCandleCake;
class Block const* mWhiteCarpet;
class Block const* mWhiteConcrete;
class Block const* mWhiteGlazedTerracotta;
class Block const* mWhiteShulkerBox;
class Block const* mWhiteWool;
class Block const* mWitherRose;
class Block const* mWood;
class Block const* mWoodenButton;
class Block const* mWoodenDoor;
class Block const* mWoodenPressurePlate;
class Block const* mWoodenSlab;
class Block const* mYellowCandle;
class Block const* mYellowCandleCake;
class Block const* mYellowCarpet;
class Block const* mYellowConcrete;
class Block const* mYellowFlower;
class Block const* mYellowGlazedTerracotta;
class Block const* mYellowShulkerBox;
class Block const* mYellowWool;

#define INIT_BLOCK(x) (m##x = &BlockTypeRegistry::getDefaultBlockState(VanillaBlockTypeIds::x, true))

void assignBlocks() {

    for (int32_t i = 0; i < 119; ++i) {
        INIT_BLOCK(Elements[i]);
    }

    INIT_BLOCK(AcaciaButton);
    INIT_BLOCK(AcaciaDoor);
    INIT_BLOCK(AcaciaFence);
    INIT_BLOCK(AcaciaFenceGate);
    INIT_BLOCK(AcaciaHangingSign);
    INIT_BLOCK(AcaciaLog);
    INIT_BLOCK(AcaciaPressurePlate);
    INIT_BLOCK(AcaciaStairs);
    INIT_BLOCK(AcaciaStandingSign);
    INIT_BLOCK(AcaciaTrapdoor);
    INIT_BLOCK(AcaciaWallSign);
    INIT_BLOCK(ActivatorRail);
    INIT_BLOCK(Allow);
    INIT_BLOCK(AmethystBlock);
    INIT_BLOCK(AmethystCluster);
    INIT_BLOCK(AncientDebris);
    INIT_BLOCK(AndesiteStairs);
    INIT_BLOCK(Anvil);
    INIT_BLOCK(Azalea);
    INIT_BLOCK(AzaleaLeaves);
    INIT_BLOCK(AzaleaLeavesFlowered);
    INIT_BLOCK(Bamboo);
    INIT_BLOCK(BambooBlock);
    INIT_BLOCK(BambooButton);
    INIT_BLOCK(BambooDoor);
    INIT_BLOCK(BambooDoubleSlab);
    INIT_BLOCK(BambooFence);
    INIT_BLOCK(BambooFenceGate);
    INIT_BLOCK(BambooHangingSign);
    INIT_BLOCK(BambooMosaic);
    INIT_BLOCK(BambooMosaicDoubleSlab);
    INIT_BLOCK(BambooMosaicSlab);
    INIT_BLOCK(BambooMosaicStairs);
    INIT_BLOCK(BambooPlanks);
    INIT_BLOCK(BambooPressurePlate);
    INIT_BLOCK(BambooSapling);
    INIT_BLOCK(BambooSlab);
    INIT_BLOCK(BambooStairs);
    INIT_BLOCK(BambooStandingSign);
    INIT_BLOCK(BambooTrapdoor);
    INIT_BLOCK(BambooWallSign);
    INIT_BLOCK(Barrel);
    INIT_BLOCK(Barrier);
    INIT_BLOCK(Basalt);
    INIT_BLOCK(Beacon);
    INIT_BLOCK(Bed);
    INIT_BLOCK(Bedrock);
    INIT_BLOCK(BeeNest);
    INIT_BLOCK(Beehive);
    INIT_BLOCK(Beetroot);
    INIT_BLOCK(Bell);
    INIT_BLOCK(BigDripleaf);
    INIT_BLOCK(BirchButton);
    INIT_BLOCK(BirchDoor);
    INIT_BLOCK(BirchFence);
    INIT_BLOCK(BirchFenceGate);
    INIT_BLOCK(BirchHangingSign);
    INIT_BLOCK(BirchLog);
    INIT_BLOCK(BirchPressurePlate);
    INIT_BLOCK(BirchStairs);
    INIT_BLOCK(BirchStandingSign);
    INIT_BLOCK(BirchTrapdoor);
    INIT_BLOCK(BirchWallSign);
    INIT_BLOCK(BlackCandle);
    INIT_BLOCK(BlackCandleCake);
    INIT_BLOCK(BlackCarpet);
    INIT_BLOCK(BlackConcrete);
    INIT_BLOCK(BlackGlazedTerracotta);
    INIT_BLOCK(BlackShulkerBox);
    INIT_BLOCK(BlackWool);
    INIT_BLOCK(Blackstone);
    INIT_BLOCK(BlackstoneDoubleSlab);
    INIT_BLOCK(BlackstoneSlab);
    INIT_BLOCK(BlackstoneStairs);
    INIT_BLOCK(BlackstoneWall);
    INIT_BLOCK(BlastFurnace);
    INIT_BLOCK(BlueCandle);
    INIT_BLOCK(BlueCandleCake);
    INIT_BLOCK(BlueCarpet);
    INIT_BLOCK(BlueConcrete);
    INIT_BLOCK(BlueGlazedTerracotta);
    INIT_BLOCK(BlueIce);
    INIT_BLOCK(BlueShulkerBox);
    INIT_BLOCK(BlueWool);
    INIT_BLOCK(BoneBlock);
    INIT_BLOCK(Bookshelf);
    INIT_BLOCK(BorderBlock);
    INIT_BLOCK(BrainCoral);
    INIT_BLOCK(BrewingStand);
    INIT_BLOCK(BrickBlock);
    INIT_BLOCK(BrickStairs);
    INIT_BLOCK(BrownCandle);
    INIT_BLOCK(BrownCandleCake);
    INIT_BLOCK(BrownCarpet);
    INIT_BLOCK(BrownConcrete);
    INIT_BLOCK(BrownGlazedTerracotta);
    INIT_BLOCK(BrownMushroom);
    INIT_BLOCK(BrownMushroomBlock);
    INIT_BLOCK(BrownShulkerBox);
    INIT_BLOCK(BrownWool);
    INIT_BLOCK(BubbleColumn);
    INIT_BLOCK(BubbleCoral);
    INIT_BLOCK(BuddingAmethyst);
    INIT_BLOCK(Cactus);
    INIT_BLOCK(Cake);
    INIT_BLOCK(Calcite);
    INIT_BLOCK(CalibratedSculkSensor);
    INIT_BLOCK(Camera);
    INIT_BLOCK(CampFire);
    INIT_BLOCK(Candle);
    INIT_BLOCK(CandleCake);
    INIT_BLOCK(Carrots);
    INIT_BLOCK(CartographyTable);
    INIT_BLOCK(CarvedPumpkin);
    INIT_BLOCK(Cauldron);
    INIT_BLOCK(CaveVines);
    INIT_BLOCK(CaveVinesBodyWithBerries);
    INIT_BLOCK(CaveVinesHeadWithBerries);
    INIT_BLOCK(Chain);
    INIT_BLOCK(ChainCommandBlock);
    INIT_BLOCK(Chalkboard);
    INIT_BLOCK(ChemicalHeat);
    INIT_BLOCK(ChemistryTable);
    INIT_BLOCK(CherryButton);
    INIT_BLOCK(CherryDoor);
    INIT_BLOCK(CherryDoubleSlab);
    INIT_BLOCK(CherryFence);
    INIT_BLOCK(CherryFenceGate);
    INIT_BLOCK(CherryHangingSign);
    INIT_BLOCK(CherryLeaves);
    INIT_BLOCK(CherryLog);
    INIT_BLOCK(CherryPlanks);
    INIT_BLOCK(CherryPressurePlate);
    INIT_BLOCK(CherrySapling);
    INIT_BLOCK(CherrySlab);
    INIT_BLOCK(CherryStairs);
    INIT_BLOCK(CherryStandingSign);
    INIT_BLOCK(CherryTrapdoor);
    INIT_BLOCK(CherryWallSign);
    INIT_BLOCK(CherryWood);
    INIT_BLOCK(Chest);
    INIT_BLOCK(ChiseledBookshelf);
    INIT_BLOCK(ChiseledDeepslate);
    INIT_BLOCK(ChiseledNetherBricks);
    INIT_BLOCK(ChiseledPolishedBlackstone);
    INIT_BLOCK(ChorusFlower);
    INIT_BLOCK(ChorusPlant);
    INIT_BLOCK(Clay);
    INIT_BLOCK(ClientRequestPlaceholderBlock);
    INIT_BLOCK(CoalBlock);
    INIT_BLOCK(CoalOre);
    INIT_BLOCK(CobbledDeepslate);
    INIT_BLOCK(CobbledDeepslateDoubleSlab);
    INIT_BLOCK(CobbledDeepslateSlab);
    INIT_BLOCK(CobbledDeepslateStairs);
    INIT_BLOCK(CobbledDeepslateWall);
    INIT_BLOCK(Cobblestone);
    INIT_BLOCK(CobblestoneWall);
    INIT_BLOCK(Cocoa);
    INIT_BLOCK(ColoredTorchBp);
    INIT_BLOCK(ColoredTorchRg);
    INIT_BLOCK(CommandBlock);
    INIT_BLOCK(Composter);
    INIT_BLOCK(ConcretePowder);
    INIT_BLOCK(Conduit);
    INIT_BLOCK(CopperBlock);
    INIT_BLOCK(CopperOre);
    INIT_BLOCK(CoralBlock);
    INIT_BLOCK(CoralFan);
    INIT_BLOCK(CoralFanDead);
    INIT_BLOCK(CoralFanHang);
    INIT_BLOCK(CoralFanHang2);
    INIT_BLOCK(CoralFanHang3);
    INIT_BLOCK(CrackedDeepslateBricks);
    INIT_BLOCK(CrackedDeepslateTiles);
    INIT_BLOCK(CrackedNetherBricks);
    INIT_BLOCK(CrackedPolishedBlackstoneBricks);
    INIT_BLOCK(CraftingTable);
    INIT_BLOCK(CrimsonButton);
    INIT_BLOCK(CrimsonDoor);
    INIT_BLOCK(CrimsonDoubleSlab);
    INIT_BLOCK(CrimsonFence);
    INIT_BLOCK(CrimsonFenceGate);
    INIT_BLOCK(CrimsonFungus);
    INIT_BLOCK(CrimsonHangingSign);
    INIT_BLOCK(CrimsonHyphae);
    INIT_BLOCK(CrimsonNylium);
    INIT_BLOCK(CrimsonPlanks);
    INIT_BLOCK(CrimsonPressurePlate);
    INIT_BLOCK(CrimsonRoots);
    INIT_BLOCK(CrimsonSlab);
    INIT_BLOCK(CrimsonStairs);
    INIT_BLOCK(CrimsonStandingSign);
    INIT_BLOCK(CrimsonStem);
    INIT_BLOCK(CrimsonTrapdoor);
    INIT_BLOCK(CrimsonWallSign);
    INIT_BLOCK(CryingObsidian);
    INIT_BLOCK(CutCopper);
    INIT_BLOCK(CutCopperSlab);
    INIT_BLOCK(CutCopperStairs);
    INIT_BLOCK(CyanCandle);
    INIT_BLOCK(CyanCandleCake);
    INIT_BLOCK(CyanCarpet);
    INIT_BLOCK(CyanConcrete);
    INIT_BLOCK(CyanGlazedTerracotta);
    INIT_BLOCK(CyanShulkerBox);
    INIT_BLOCK(CyanWool);
    INIT_BLOCK(DarkOakButton);
    INIT_BLOCK(DarkOakDoor);
    INIT_BLOCK(DarkOakFence);
    INIT_BLOCK(DarkOakFenceGate);
    INIT_BLOCK(DarkOakLog);
    INIT_BLOCK(DarkOakPressurePlate);
    INIT_BLOCK(DarkOakStairs);
    INIT_BLOCK(DarkOakTrapdoor);
    INIT_BLOCK(DarkPrismarineStairs);
    INIT_BLOCK(DarkoakHangingSign);
    INIT_BLOCK(DarkoakStandingSign);
    INIT_BLOCK(DarkoakWallSign);
    INIT_BLOCK(DaylightDetector);
    INIT_BLOCK(DaylightDetectorInverted);
    INIT_BLOCK(DeadBrainCoral);
    INIT_BLOCK(DeadBubbleCoral);
    INIT_BLOCK(DeadFireCoral);
    INIT_BLOCK(DeadHornCoral);
    INIT_BLOCK(DeadTubeCoral);
    INIT_BLOCK(Deadbush);
    INIT_BLOCK(DecoratedPot);
    INIT_BLOCK(Deepslate);
    INIT_BLOCK(DeepslateBrickDoubleSlab);
    INIT_BLOCK(DeepslateBrickSlab);
    INIT_BLOCK(DeepslateBrickStairs);
    INIT_BLOCK(DeepslateBrickWall);
    INIT_BLOCK(DeepslateBricks);
    INIT_BLOCK(DeepslateCoalOre);
    INIT_BLOCK(DeepslateCopperOre);
    INIT_BLOCK(DeepslateDiamondOre);
    INIT_BLOCK(DeepslateEmeraldOre);
    INIT_BLOCK(DeepslateGoldOre);
    INIT_BLOCK(DeepslateIronOre);
    INIT_BLOCK(DeepslateLapisOre);
    INIT_BLOCK(DeepslateRedstoneOre);
    INIT_BLOCK(DeepslateTileDoubleSlab);
    INIT_BLOCK(DeepslateTileSlab);
    INIT_BLOCK(DeepslateTileStairs);
    INIT_BLOCK(DeepslateTileWall);
    INIT_BLOCK(DeepslateTiles);
    INIT_BLOCK(Deny);
    INIT_BLOCK(DetectorRail);
    INIT_BLOCK(DiamondBlock);
    INIT_BLOCK(DiamondOre);
    INIT_BLOCK(DioriteStairs);
    INIT_BLOCK(Dirt);
    INIT_BLOCK(DirtWithRoots);
    INIT_BLOCK(Dispenser);
    INIT_BLOCK(DoubleCutCopperSlab);
    INIT_BLOCK(DoublePlant);
    INIT_BLOCK(DoubleStoneSlab);
    INIT_BLOCK(DoubleStoneSlab2);
    INIT_BLOCK(DoubleStoneSlab3);
    INIT_BLOCK(DoubleStoneSlab4);
    INIT_BLOCK(DoubleWoodenSlab);
    INIT_BLOCK(DragonEgg);
    INIT_BLOCK(DriedKelpBlock);
    INIT_BLOCK(Dripstone);
    INIT_BLOCK(Dropper);
    INIT_BLOCK(EmeraldBlock);
    INIT_BLOCK(EmeraldOre);
    INIT_BLOCK(EnchantingTable);
    INIT_BLOCK(EndBrickStairs);
    INIT_BLOCK(EndBricks);
    INIT_BLOCK(EndGateway);
    INIT_BLOCK(EndPortal);
    INIT_BLOCK(EndPortalFrame);
    INIT_BLOCK(EndRod);
    INIT_BLOCK(EndStone);
    INIT_BLOCK(EnderChest);
    INIT_BLOCK(ExposedCopper);
    INIT_BLOCK(ExposedCutCopper);
    INIT_BLOCK(ExposedCutCopperSlab);
    INIT_BLOCK(ExposedCutCopperStairs);
    INIT_BLOCK(ExposedDoubleCutCopperSlab);
    INIT_BLOCK(FarmlandBlock);
    INIT_BLOCK(FenceGate);
    INIT_BLOCK(Fire);
    INIT_BLOCK(FireCoral);
    INIT_BLOCK(FletchingTable);
    INIT_BLOCK(FlowerPot);
    INIT_BLOCK(FloweringAzalea);
    INIT_BLOCK(FlowingLava);
    INIT_BLOCK(FlowingWater);
    INIT_BLOCK(FrogSpawn);
    INIT_BLOCK(FrostedIce);
    INIT_BLOCK(Furnace);
    INIT_BLOCK(GildedBlackstone);
    INIT_BLOCK(Glass);
    INIT_BLOCK(GlassPane);
    INIT_BLOCK(GlowItemFrame);
    INIT_BLOCK(GlowLichen);
    INIT_BLOCK(GlowingObsidian);
    INIT_BLOCK(Glowstone);
    INIT_BLOCK(GoldBlock);
    INIT_BLOCK(GoldOre);
    INIT_BLOCK(GoldenRail);
    INIT_BLOCK(GraniteStairs);
    INIT_BLOCK(Grass);
    INIT_BLOCK(GrassPath);
    INIT_BLOCK(Gravel);
    INIT_BLOCK(GrayCandle);
    INIT_BLOCK(GrayCandleCake);
    INIT_BLOCK(GrayCarpet);
    INIT_BLOCK(GrayConcrete);
    INIT_BLOCK(GrayGlazedTerracotta);
    INIT_BLOCK(GrayShulkerBox);
    INIT_BLOCK(GrayWool);
    INIT_BLOCK(GreenCandle);
    INIT_BLOCK(GreenCandleCake);
    INIT_BLOCK(GreenCarpet);
    INIT_BLOCK(GreenConcrete);
    INIT_BLOCK(GreenGlazedTerracotta);
    INIT_BLOCK(GreenShulkerBox);
    INIT_BLOCK(GreenWool);
    INIT_BLOCK(Grindstone);
    INIT_BLOCK(HangingRoots);
    INIT_BLOCK(HardGlass);
    INIT_BLOCK(HardGlassPane);
    INIT_BLOCK(HardStainedGlass);
    INIT_BLOCK(HardStainedGlassPane);
    INIT_BLOCK(HardenedClay);
    INIT_BLOCK(HayBlock);
    INIT_BLOCK(HeavyWeightedPressurePlate);
    INIT_BLOCK(HoneyBlock);
    INIT_BLOCK(HoneycombBlock);
    INIT_BLOCK(Hopper);
    INIT_BLOCK(HornCoral);
    INIT_BLOCK(Ice);
    INIT_BLOCK(InfestedDeepslate);
    INIT_BLOCK(InfoUpdate);
    INIT_BLOCK(InfoUpdate2);
    INIT_BLOCK(InvisibleBedrock);
    INIT_BLOCK(IronBars);
    INIT_BLOCK(IronBlock);
    INIT_BLOCK(IronDoor);
    INIT_BLOCK(IronOre);
    INIT_BLOCK(IronTrapdoor);
    INIT_BLOCK(ItemFrame);
    INIT_BLOCK(Jigsaw);
    INIT_BLOCK(Jukebox);
    INIT_BLOCK(JungleButton);
    INIT_BLOCK(JungleDoor);
    INIT_BLOCK(JungleFence);
    INIT_BLOCK(JungleFenceGate);
    INIT_BLOCK(JungleHangingSign);
    INIT_BLOCK(JungleLog);
    INIT_BLOCK(JunglePressurePlate);
    INIT_BLOCK(JungleStairs);
    INIT_BLOCK(JungleStandingSign);
    INIT_BLOCK(JungleTrapdoor);
    INIT_BLOCK(JungleWallSign);
    INIT_BLOCK(Kelp);
    INIT_BLOCK(Ladder);
    INIT_BLOCK(Lantern);
    INIT_BLOCK(LapisBlock);
    INIT_BLOCK(LapisOre);
    INIT_BLOCK(LargeAmethystBud);
    INIT_BLOCK(Lava);
    INIT_BLOCK(Leaves);
    INIT_BLOCK(Leaves2);
    INIT_BLOCK(Lectern);
    INIT_BLOCK(Lever);
    INIT_BLOCK(LightBlock);
    INIT_BLOCK(LightBlueCandle);
    INIT_BLOCK(LightBlueCandleCake);
    INIT_BLOCK(LightBlueCarpet);
    INIT_BLOCK(LightBlueConcrete);
    INIT_BLOCK(LightBlueGlazedTerracotta);
    INIT_BLOCK(LightBlueShulkerBox);
    INIT_BLOCK(LightBlueWool);
    INIT_BLOCK(LightGrayCandle);
    INIT_BLOCK(LightGrayCandleCake);
    INIT_BLOCK(LightGrayCarpet);
    INIT_BLOCK(LightGrayConcrete);
    INIT_BLOCK(LightGrayShulkerBox);
    INIT_BLOCK(LightGrayWool);
    INIT_BLOCK(LightWeightedPressurePlate);
    INIT_BLOCK(LightningRod);
    INIT_BLOCK(LimeCandle);
    INIT_BLOCK(LimeCandleCake);
    INIT_BLOCK(LimeCarpet);
    INIT_BLOCK(LimeConcrete);
    INIT_BLOCK(LimeGlazedTerracotta);
    INIT_BLOCK(LimeShulkerBox);
    INIT_BLOCK(LimeWool);
    INIT_BLOCK(LitBlastFurnace);
    INIT_BLOCK(LitDeepslateRedstoneOre);
    INIT_BLOCK(LitFurnace);
    INIT_BLOCK(LitPumpkin);
    INIT_BLOCK(LitRedstoneLamp);
    INIT_BLOCK(LitRedstoneOre);
    INIT_BLOCK(LitSmoker);
    INIT_BLOCK(Lodestone);
    INIT_BLOCK(Loom);
    INIT_BLOCK(MagentaCandle);
    INIT_BLOCK(MagentaCandleCake);
    INIT_BLOCK(MagentaCarpet);
    INIT_BLOCK(MagentaConcrete);
    INIT_BLOCK(MagentaGlazedTerracotta);
    INIT_BLOCK(MagentaShulkerBox);
    INIT_BLOCK(MagentaWool);
    INIT_BLOCK(Magma);
    INIT_BLOCK(MangroveButton);
    INIT_BLOCK(MangroveDoor);
    INIT_BLOCK(MangroveDoubleSlab);
    INIT_BLOCK(MangroveFence);
    INIT_BLOCK(MangroveFenceGate);
    INIT_BLOCK(MangroveHangingSign);
    INIT_BLOCK(MangroveLeaves);
    INIT_BLOCK(MangroveLog);
    INIT_BLOCK(MangrovePlanks);
    INIT_BLOCK(MangrovePressurePlate);
    INIT_BLOCK(MangrovePropagule);
    INIT_BLOCK(MangroveRoots);
    INIT_BLOCK(MangroveSlab);
    INIT_BLOCK(MangroveStairs);
    INIT_BLOCK(MangroveStandingSign);
    INIT_BLOCK(MangroveTrapdoor);
    INIT_BLOCK(MangroveWallSign);
    INIT_BLOCK(MangroveWood);
    INIT_BLOCK(MediumAmethystBud);
    INIT_BLOCK(MelonBlock);
    INIT_BLOCK(MelonStem);
    INIT_BLOCK(MobSpawner);
    INIT_BLOCK(MonsterEgg);
    INIT_BLOCK(MossBlock);
    INIT_BLOCK(MossCarpet);
    INIT_BLOCK(MossyCobblestone);
    INIT_BLOCK(MossyCobblestoneStairs);
    INIT_BLOCK(MossyStoneBrickStairs);
    INIT_BLOCK(MovingBlock);
    INIT_BLOCK(Mud);
    INIT_BLOCK(MudBrickDoubleSlab);
    INIT_BLOCK(MudBrickSlab);
    INIT_BLOCK(MudBrickStairs);
    INIT_BLOCK(MudBrickWall);
    INIT_BLOCK(MudBricks);
    INIT_BLOCK(MuddyMangroveRoots);
    INIT_BLOCK(Mycelium);
    INIT_BLOCK(MysteriousFrame);
    INIT_BLOCK(MysteriousFrameSlot);
    INIT_BLOCK(NetherBrickBlockName);
    INIT_BLOCK(NetherBrickFence);
    INIT_BLOCK(NetherBrickStairs);
    INIT_BLOCK(NetherGoldOre);
    INIT_BLOCK(NetherSprouts);
    INIT_BLOCK(NetherWart);
    INIT_BLOCK(NetherWartBlock);
    INIT_BLOCK(NetheriteBlock);
    INIT_BLOCK(Netherrack);
    INIT_BLOCK(Netherreactor);
    INIT_BLOCK(NormalStoneStairs);
    INIT_BLOCK(Noteblock);
    INIT_BLOCK(OakFence);
    INIT_BLOCK(OakHangingSign);
    INIT_BLOCK(OakLog);
    INIT_BLOCK(OakStairs);
    INIT_BLOCK(Observer);
    INIT_BLOCK(Obsidian);
    INIT_BLOCK(OchreFroglight);
    INIT_BLOCK(OrangeCandle);
    INIT_BLOCK(OrangeCandleCake);
    INIT_BLOCK(OrangeCarpet);
    INIT_BLOCK(OrangeConcrete);
    INIT_BLOCK(OrangeGlazedTerracotta);
    INIT_BLOCK(OrangeShulkerBox);
    INIT_BLOCK(OrangeWool);
    INIT_BLOCK(OxidizedCopper);
    INIT_BLOCK(OxidizedCutCopper);
    INIT_BLOCK(OxidizedCutCopperSlab);
    INIT_BLOCK(OxidizedCutCopperStairs);
    INIT_BLOCK(OxidizedDoubleCutCopperSlab);
    INIT_BLOCK(PackedIce);
    INIT_BLOCK(PackedMud);
    INIT_BLOCK(PearlescentFroglight);
    INIT_BLOCK(PinkCandle);
    INIT_BLOCK(PinkCandleCake);
    INIT_BLOCK(PinkCarpet);
    INIT_BLOCK(PinkConcrete);
    INIT_BLOCK(PinkGlazedTerracotta);
    INIT_BLOCK(PinkPetals);
    INIT_BLOCK(PinkShulkerBox);
    INIT_BLOCK(PinkWool);
    INIT_BLOCK(Piston);
    INIT_BLOCK(PistonArmCollision);
    INIT_BLOCK(PitcherCrop);
    INIT_BLOCK(PitcherPlant);
    INIT_BLOCK(Planks);
    INIT_BLOCK(Podzol);
    INIT_BLOCK(PointedDripstone);
    INIT_BLOCK(PolishedAndesiteStairs);
    INIT_BLOCK(PolishedBasalt);
    INIT_BLOCK(PolishedBlackstone);
    INIT_BLOCK(PolishedBlackstoneBrickDoubleSlab);
    INIT_BLOCK(PolishedBlackstoneBrickSlab);
    INIT_BLOCK(PolishedBlackstoneBrickStairs);
    INIT_BLOCK(PolishedBlackstoneBrickWall);
    INIT_BLOCK(PolishedBlackstoneBricks);
    INIT_BLOCK(PolishedBlackstoneButton);
    INIT_BLOCK(PolishedBlackstoneDoubleSlab);
    INIT_BLOCK(PolishedBlackstonePressurePlate);
    INIT_BLOCK(PolishedBlackstoneSlab);
    INIT_BLOCK(PolishedBlackstoneStairs);
    INIT_BLOCK(PolishedBlackstoneWall);
    INIT_BLOCK(PolishedDeepslate);
    INIT_BLOCK(PolishedDeepslateDoubleSlab);
    INIT_BLOCK(PolishedDeepslateSlab);
    INIT_BLOCK(PolishedDeepslateStairs);
    INIT_BLOCK(PolishedDeepslateWall);
    INIT_BLOCK(PolishedDioriteStairs);
    INIT_BLOCK(PolishedGraniteStairs);
    INIT_BLOCK(Portal);
    INIT_BLOCK(Potatoes);
    INIT_BLOCK(PowderSnow);
    INIT_BLOCK(PoweredComparator);
    INIT_BLOCK(PoweredRepeater);
    INIT_BLOCK(Prismarine);
    INIT_BLOCK(PrismarineBricksStairs);
    INIT_BLOCK(PrismarineStairs);
    INIT_BLOCK(Pumpkin);
    INIT_BLOCK(PumpkinStem);
    INIT_BLOCK(PurpleCandle);
    INIT_BLOCK(PurpleCandleCake);
    INIT_BLOCK(PurpleCarpet);
    INIT_BLOCK(PurpleConcrete);
    INIT_BLOCK(PurpleGlazedTerracotta);
    INIT_BLOCK(PurpleShulkerBox);
    INIT_BLOCK(PurpleWool);
    INIT_BLOCK(PurpurBlock);
    INIT_BLOCK(PurpurStairs);
    INIT_BLOCK(QuartzBlock);
    INIT_BLOCK(QuartzBricks);
    INIT_BLOCK(QuartzOre);
    INIT_BLOCK(QuartzStairs);
    INIT_BLOCK(Rail);
    INIT_BLOCK(RawCopperBlock);
    INIT_BLOCK(RawGoldBlock);
    INIT_BLOCK(RawIronBlock);
    INIT_BLOCK(RedCandle);
    INIT_BLOCK(RedCandleCake);
    INIT_BLOCK(RedCarpet);
    INIT_BLOCK(RedConcrete);
    INIT_BLOCK(RedFlower);
    INIT_BLOCK(RedGlazedTerracotta);
    INIT_BLOCK(RedMushroom);
    INIT_BLOCK(RedMushroomBlock);
    INIT_BLOCK(RedNetherBrick);
    INIT_BLOCK(RedNetherBrickStairs);
    INIT_BLOCK(RedSandstone);
    INIT_BLOCK(RedSandstoneStairs);
    INIT_BLOCK(RedShulkerBox);
    INIT_BLOCK(RedWool);
    INIT_BLOCK(RedstoneBlock);
    INIT_BLOCK(RedstoneLamp);
    INIT_BLOCK(RedstoneOre);
    INIT_BLOCK(RedstoneTorch);
    INIT_BLOCK(RedstoneWire);
    INIT_BLOCK(Reeds);
    INIT_BLOCK(ReinforcedDeepslate);
    INIT_BLOCK(RepeatingCommandBlock);
    INIT_BLOCK(Reserved6);
    INIT_BLOCK(RespawnAnchor);
    INIT_BLOCK(Sand);
    INIT_BLOCK(Sandstone);
    INIT_BLOCK(SandstoneStairs);
    INIT_BLOCK(Sapling);
    INIT_BLOCK(Scaffolding);
    INIT_BLOCK(Sculk);
    INIT_BLOCK(SculkCatalyst);
    INIT_BLOCK(SculkSensor);
    INIT_BLOCK(SculkShrieker);
    INIT_BLOCK(SculkVein);
    INIT_BLOCK(SeaLantern);
    INIT_BLOCK(SeaPickle);
    INIT_BLOCK(Seagrass);
    INIT_BLOCK(Shroomlight);
    INIT_BLOCK(SilverGlazedTerracotta);
    INIT_BLOCK(Skull);
    INIT_BLOCK(SlimeBlock);
    INIT_BLOCK(SmallAmethystBud);
    INIT_BLOCK(SmallDripleaf);
    INIT_BLOCK(SmithingTable);
    INIT_BLOCK(Smoker);
    INIT_BLOCK(SmoothBasalt);
    INIT_BLOCK(SmoothQuartzStairs);
    INIT_BLOCK(SmoothRedSandstoneStairs);
    INIT_BLOCK(SmoothSandstoneStairs);
    INIT_BLOCK(SmoothStone);
    INIT_BLOCK(SnifferEgg);
    INIT_BLOCK(Snow);
    INIT_BLOCK(SnowLayer);
    INIT_BLOCK(SoulCampfire);
    INIT_BLOCK(SoulFire);
    INIT_BLOCK(SoulLantern);
    INIT_BLOCK(SoulSand);
    INIT_BLOCK(SoulSoil);
    INIT_BLOCK(SoulTorch);
    INIT_BLOCK(Sponge);
    INIT_BLOCK(SporeBlossom);
    INIT_BLOCK(SpruceButton);
    INIT_BLOCK(SpruceDoor);
    INIT_BLOCK(SpruceFence);
    INIT_BLOCK(SpruceFenceGate);
    INIT_BLOCK(SpruceHangingSign);
    INIT_BLOCK(SpruceLog);
    INIT_BLOCK(SprucePressurePlate);
    INIT_BLOCK(SpruceStairs);
    INIT_BLOCK(SpruceStandingSign);
    INIT_BLOCK(SpruceTrapdoor);
    INIT_BLOCK(SpruceWallSign);
    INIT_BLOCK(StainedGlass);
    INIT_BLOCK(StainedGlassPane);
    INIT_BLOCK(StainedHardenedClay);
    INIT_BLOCK(StandingBanner);
    INIT_BLOCK(StandingSign);
    INIT_BLOCK(StickyPiston);
    INIT_BLOCK(StickyPistonArmCollision);
    INIT_BLOCK(Stone);
    INIT_BLOCK(StoneBrickStairs);
    INIT_BLOCK(StoneBricks);
    INIT_BLOCK(StoneButton);
    INIT_BLOCK(StonePressurePlate);
    INIT_BLOCK(StoneSlab);
    INIT_BLOCK(StoneSlab2);
    INIT_BLOCK(StoneSlab3);
    INIT_BLOCK(StoneSlab4);
    INIT_BLOCK(StoneStairs);
    INIT_BLOCK(Stonecutter);
    INIT_BLOCK(StonecutterBlock);
    INIT_BLOCK(StrippedAcaciaLog);
    INIT_BLOCK(StrippedBambooBlock);
    INIT_BLOCK(StrippedBirchLog);
    INIT_BLOCK(StrippedCherryLog);
    INIT_BLOCK(StrippedCherryWood);
    INIT_BLOCK(StrippedCrimsonHyphae);
    INIT_BLOCK(StrippedCrimsonStem);
    INIT_BLOCK(StrippedDarkOakLog);
    INIT_BLOCK(StrippedJungleLog);
    INIT_BLOCK(StrippedMangroveLog);
    INIT_BLOCK(StrippedMangroveWood);
    INIT_BLOCK(StrippedOakLog);
    INIT_BLOCK(StrippedSpruceLog);
    INIT_BLOCK(StrippedWarpedHyphae);
    INIT_BLOCK(StrippedWarpedStem);
    INIT_BLOCK(StructureBlock);
    INIT_BLOCK(StructureVoid);
    INIT_BLOCK(SuspiciousGravel);
    INIT_BLOCK(SuspiciousSand);
    INIT_BLOCK(SweetBerryBush);
    INIT_BLOCK(TallGrass);
    INIT_BLOCK(Target);
    INIT_BLOCK(TintedGlass);
    INIT_BLOCK(Tnt);
    INIT_BLOCK(Torch);
    INIT_BLOCK(Torchflower);
    INIT_BLOCK(TorchflowerCrop);
    INIT_BLOCK(Trapdoor);
    INIT_BLOCK(TrappedChest);
    INIT_BLOCK(TripWire);
    INIT_BLOCK(TripWireHook);
    INIT_BLOCK(TubeCoral);
    INIT_BLOCK(Tuff);
    INIT_BLOCK(TurtleEgg);
    INIT_BLOCK(TwistingVines);
    INIT_BLOCK(UnderwaterTorch);
    INIT_BLOCK(UndyedShulkerBox);
    INIT_BLOCK(UnlitRedstoneTorch);
    INIT_BLOCK(UnpoweredComparator);
    INIT_BLOCK(UnpoweredRepeater);
    INIT_BLOCK(VerdantFroglight);
    INIT_BLOCK(Vine);
    INIT_BLOCK(WallBanner);
    INIT_BLOCK(WallSign);
    INIT_BLOCK(WarpedButton);
    INIT_BLOCK(WarpedDoor);
    INIT_BLOCK(WarpedDoubleSlab);
    INIT_BLOCK(WarpedFence);
    INIT_BLOCK(WarpedFenceGate);
    INIT_BLOCK(WarpedFungus);
    INIT_BLOCK(WarpedHangingSign);
    INIT_BLOCK(WarpedHyphae);
    INIT_BLOCK(WarpedNylium);
    INIT_BLOCK(WarpedPlanks);
    INIT_BLOCK(WarpedPressurePlate);
    INIT_BLOCK(WarpedRoots);
    INIT_BLOCK(WarpedSlab);
    INIT_BLOCK(WarpedStairs);
    INIT_BLOCK(WarpedStandingSign);
    INIT_BLOCK(WarpedStem);
    INIT_BLOCK(WarpedTrapdoor);
    INIT_BLOCK(WarpedWallSign);
    INIT_BLOCK(WarpedWartBlock);
    INIT_BLOCK(Water);
    INIT_BLOCK(WaterLily);
    INIT_BLOCK(WaxedCopper);
    INIT_BLOCK(WaxedCutCopper);
    INIT_BLOCK(WaxedCutCopperSlab);
    INIT_BLOCK(WaxedCutCopperStairs);
    INIT_BLOCK(WaxedDoubleCutCopperSlab);
    INIT_BLOCK(WaxedExposedCopper);
    INIT_BLOCK(WaxedExposedCutCopper);
    INIT_BLOCK(WaxedExposedCutCopperSlab);
    INIT_BLOCK(WaxedExposedCutCopperStairs);
    INIT_BLOCK(WaxedExposedDoubleCutCopperSlab);
    INIT_BLOCK(WaxedOxidizedCopper);
    INIT_BLOCK(WaxedOxidizedCutCopper);
    INIT_BLOCK(WaxedOxidizedCutCopperSlab);
    INIT_BLOCK(WaxedOxidizedCutCopperStairs);
    INIT_BLOCK(WaxedOxidizedDoubleCutCopperSlab);
    INIT_BLOCK(WaxedWeatheredCopper);
    INIT_BLOCK(WaxedWeatheredCutCopper);
    INIT_BLOCK(WaxedWeatheredCutCopperSlab);
    INIT_BLOCK(WaxedWeatheredCutCopperStairs);
    INIT_BLOCK(WaxedWeatheredDoubleCutCopperSlab);
    INIT_BLOCK(WeatheredCopper);
    INIT_BLOCK(WeatheredCutCopper);
    INIT_BLOCK(WeatheredCutCopperSlab);
    INIT_BLOCK(WeatheredCutCopperStairs);
    INIT_BLOCK(WeatheredDoubleCutCopperSlab);
    INIT_BLOCK(Web);
    INIT_BLOCK(WeepingVines);
    INIT_BLOCK(Wheat);
    INIT_BLOCK(WhiteCandle);
    INIT_BLOCK(WhiteCandleCake);
    INIT_BLOCK(WhiteCarpet);
    INIT_BLOCK(WhiteConcrete);
    INIT_BLOCK(WhiteGlazedTerracotta);
    INIT_BLOCK(WhiteShulkerBox);
    INIT_BLOCK(WhiteWool);
    INIT_BLOCK(WitherRose);
    INIT_BLOCK(Wood);
    INIT_BLOCK(WoodenButton);
    INIT_BLOCK(WoodenDoor);
    INIT_BLOCK(WoodenPressurePlate);
    INIT_BLOCK(WoodenSlab);
    INIT_BLOCK(YellowCandle);
    INIT_BLOCK(YellowCandleCake);
    INIT_BLOCK(YellowCarpet);
    INIT_BLOCK(YellowConcrete);
    INIT_BLOCK(YellowFlower);
    INIT_BLOCK(YellowGlazedTerracotta);
    INIT_BLOCK(YellowShulkerBox);
    INIT_BLOCK(YellowWool);
}

}; // namespace StaticVanillaBlocks


LL_AUTO_STATIC_HOOK(StaticVanillaBlockAssign, HookPriority::Normal, BedrockBlocks::assignBlocks, void) {
    origin();
    StaticVanillaBlocks::assignBlocks();
}