#pragma once

#include "mc/_HeaderOutputPredefine.h"

enum class PackParseErrorType : int {
    None                              = 0,
    NoPackAccess                      = 1,
    UnsupportedFileFormat             = 2,
    IncompletePack                    = 3,
    NoManifest                        = 4,
    ParseError                        = 5,
    MissingProperty                   = 6,
    MissingPropertyUpgraded           = 7,
    WrongTypeProperty                 = 8,
    EmptyProperty                     = 9,
    EmptyPropertyUpgraded             = 10,
    InvalidProperty                   = 11,
    MalformedPropertyUUID             = 12,
    MalformedPropertyUUIDUpgraded     = 13,
    MalformedPropertyVERSION          = 14,
    MalformedPropertyVERSIONUpgraded  = 15,
    DuplicateUUIDUpgraded             = 16,
    DuplicateUUID                     = 17,
    InvalidPackTypeUpgraded           = 18,
    MissingModules                    = 19,
    MissingDependency                 = 20,
    MultipleModules                   = 21,
    MultipleModulesUpgraded           = 22,
    UnsupportedFormatVersion          = 23,
    PackUpgraded                      = 24,
    InvalidCapability                 = 25,
    UnsupportedBaseGameVersionPatch   = 26,
    IgnoredProperty                   = 27,
    VersionTooHigh                    = 28,
    VersionTooLow                     = 29,
    MinEngineVersionCapFormatVersion1 = 30,
    FolderStructureTooDeep            = 31,
    Count                             = 32,
};
