#ifndef PCH_H
#define PCH_H
#include <LoaderApi.h>
#include <Loader.h>
#include <iostream>
#include "framework.h"
// LiteLoader.cpp
//#include <api/regCommandHelper.h>
//#include <api/xuidreg/xuidreg.h>
//#include <lbpch.h>
#include <filesystem>
#include <map>
#include "framework.h"
// CheckUpdate.cpp
#include <rapidjson/include/document.h>
#include <rapidjson/include/rapidjson.h>
#include <iostream>
#include <string>
#include <Utils/Logger.h>
#endif  // PCH_H