site_name: LeviLamina Docs
repo_url: https://github.com/LiteLDev/LeviLamina
docs_dir: contents

nav:
  - Home: index.md
  - FAQ: faq.md

  - User Guides:
      - Install on Server:
          - user_guides/install.md
          - user_guides/install_on_docker.md
      - user_guides/install_on_client.md
      - user_guides/troubleshooting.md
      - common_guides/usage_guidelines.md

  - Developer Guides:
      - Tutorials:
          - developer_guides/tutorials/create_your_first_mod.md
          - developer_guides/tutorials/publish_your_first_mod.md
          - developer_guides/tutorials/publish_your_first_pack.md

      - How-to Guides:
          - developer_guides/how_to_guides/event_guide.md
          - developer_guides/how_to_guides/interface_export_guide.md
          - developer_guides/how_to_guides/find_function_guide.md
          - developer_guides/how_to_guides/form_guide.md
          - developer_guides/how_to_guides/hook_guide.md
          - developer_guides/how_to_guides/i18n_guide.md
          - developer_guides/how_to_guides/item_guide.md
          - developer_guides/how_to_guides/command_guide.md
          - developer_guides/how_to_guides/coro_guide.md
          - developer_guides/how_to_guides/build_guide.md

      - Architecture: developer_guides/architecture.md

      - API Reference:
          - api_reference/index.md
          - Base: api_reference/base.md
          - Chrono: api_reference/chrono.md
          - Command: api_reference/command.md
          - Config: api_reference/config.md
          - Coroutine: api_reference/coro.md
          - Data: api_reference/data.md
          - Event: api_reference/event.md
          - Expected: api_reference/expected.md
          - Form: api_reference/form.md
          - I18n: api_reference/i18n.md
          - IO & Logger: api_reference/io.md
          - Memory & Hook: api_reference/memory.md
          - Mod: api_reference/mod.md
          - Network: api_reference/network.md
          - Reflection: api_reference/reflection.md
          - Service: api_reference/service.md
          - Thread: api_reference/thread.md
          - Utils: api_reference/utils.md
          - Input (Client): api_reference/input.md

      - Doxygen API 🔗: https://lamina.levimc.org/api

  - Maintainer Guides:
      - maintainer_guides/cpp_style_guide.md

  - Supported Versions: versions.md

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  favicon: favicon.ico
  logo: logo.svg
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - tables
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight:
      auto_title: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist

plugins:
  - i18n:
      languages:
        - locale: en
          default: true
          name: English

        - locale: zh
          name: 中文
          nav_translations:
            Home: 主页
            FAQ: 常见问题
            User Guides: 用户指南
            Install on Server: 在服务器上安装
            Install on Client: 在客户端上安装
            Install on Docker: 在Docker上安装
            Developer Guides: 开发者指南
            Tutorials: 教程
            How-to Guides: 如何做到······
            Architecture: 项目架构
            API Reference: API 参考
            Base: 基础类型
            Chrono: 游戏时间
            Command: 命令系统
            Config: 配置系统
            Coroutine: 协程
            Data: 数据结构
            Event: 事件系统
            Expected: 错误处理
            Form: 表单 UI
            I18n: 国际化
            IO & Logger: 日志系统
            Memory & Hook: 内存与钩子
            Mod: 模组系统
            Network: 网络
            Reflection: 反射
            Service: 服务系统
            Thread: 线程工具
            Utils: 工具函数
            Input (Client): 输入系统（客户端）
            Doxygen API 🔗: Doxygen API 🔗
            Maintainer Guides: 维护者指南
            Supported Versions: 支持的版本

  - search
