name: Add a new GitHub Project card linked to a GitHub issue to the specified project column
on: 
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened
jobs:
  github-actions-automate-projects:
    runs-on: ubuntu-latest
    steps:
    - name: add-new-issue-or-pr-to-project
      uses: docker://takanabe/github-actions-automate-projects:v0.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.AUTO_ADD_INTO_PROJECT_TOKEN }}
        GITHUB_PROJECT_URL: https://github.com/LiteLDev/LiteLoaderBDS/projects/3
        GITHUB_PROJECT_COLUMN_NAME: Normal Property
